### PR TITLE
changed dash to underscore in registry/_tags

### PR DESCRIPTION
**Pull request by anurag629**
##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
@anurag629, thanks for the contribution!

But note, you have to replace the strings also *in all other occurrences throughout the codebase*, since these are used as universal reference strings to the tag.

I would suggest, pick just one, and consistently track down all occurrences in the codebase consistently. That will make it easier to review and debug.

**Comment by anurag629** [comment]
sorry, i will try again.
I am new in open source contribution that's why it is little bit hard for me.

**Comment by anurag629** [comment]
changed

**Comment by anurag629** [comment]
I am confused please help me with how I can contribute.
I am new here to contribute and I have not contributed to any open source project earlier.

**Comment by fkiraly** [comment]
apologies, @anurag629, I did not see your message, probably since you closed the pull request.
I've been going through PR and found this.

Are you still intending to work on this? If so, consider joining one of the Friday community collaboration sessions on discord, and I'm happy to help with an explanation of which other occurrences in the code base I meant.

**Comment by anurag629** [comment]
> apologies, @anurag629, I did not see your message, probably since you closed the pull request.
> I've been going through PR and found this.
> 
> Are you still intending to work on this? If so, consider joining one of the Friday community collaboration sessions on discord, and I'm happy to help with an explanation of which other occurrences in the code base I meant.

From where i can get Friday community link

**Comment by fkiraly** [comment]
You can find the link on the README page, look for the discord badge.

**Pull request closed without merging**
