### PR TITLE
Rename check_is to check_is_mtype

### LINKED ISSUE #1533: [ENH] rename `check_is` to `check_is_mtype`
@mloning suggested to rename `check_is` to `check_is_mtype` to be more descriptive.

It's perhaps best to wait for @chrisholder's PR #1423 first.

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
Fixes #1533

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Agreed with the rename (as discussed before), but we need to do proper deprecation!

Please leave `check_is` in, and let it call `check_is_mtype` plus raise a deprecation message for 0.10.0 (or 0.11.0, depending when this goes in).

**Comment by mloning** [comment]
This is what I've done?

**Comment by fkiraly** [comment]
>This is what I've done?

Yes, you're right, sorry I overlooked it.

**Review by fkiraly — APPROVED** [review]
Looks good, this is rename with deprecation.
Change request was made in error.

**Pull request merged**
