### PR TITLE
[ENH] test parameter refactor: `TSInterpolator`

### PR DESCRIPTION
**Pull request by NoaBenAmi**
Reference Issue:
Estimator Test Parameters Refactor https://github.com/alan-turing-institute/sktime/issues/1678

Refactored TSInterpolator by creating get_test_params method as explained in issue and removed params from tests/_config.py

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
A wild linting failure appears, click here to see how it can be defeated:
image

Jokes aside, thanks for your contribution, appreciated!
Apart from the linting issue, all is good.
We lint our code at sktime, so consider adding linting to your developer set-up:
https://www.sktime.org/en/stable/developer_guide/coding_standards.html#id2

**Comment by fkiraly** [comment]
Generally, this happens when there is legacy code that wasn´t documented by the author, before we started enforcing doc checks.

In your case, it should be easy: I had recently worked on `TSInterpolator` and already added the docstrings in this PR https://github.com/alan-turing-institute/sktime/pull/2259 - so all should be fine if you merge it into yours (that way it will become dependent on #2259 though)

**Comment by fkiraly** [comment]
FYI, @NoaBenAmi, I just merged a larger refactor of sktime transformers which enables hierarchical functionality for them, including for TSInterpolator, I believe. I recommend to update to the latest main.

**Comment by NoaBenAmi** [comment]
Thanks for the help Franz!
Is there anything else I need to do on my end?

**Review by fkiraly — APPROVED** [review]
No, looks like it's all done, no adverse ramifications from the merge.

Thanks!

**Pull request merged**
