### PR TITLE
[DOC] Fixes in class description ExpandingWindowSplitter

### PR DESCRIPTION
**Pull request by keepersas**
#### What does this implement/fix? Explain your changes.
Minor fixes in class description 'ExpandingWindowSplitter'. No code changes.

#### Does your contribution introduce a new dependency? If yes, which one?
No

##### For all contributions
- [ x] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Nice, thanks!

I was looking at it as well today and got confused.

Btw, do you know what happens if `start_with_window` is `False`?
I didn't understand what that parameter does. Might be worth explaining that better, in case you know what it does.

**Comment by keepersas** [comment]
> Nice, thanks!
> 
> I was looking at it as well today and got confused.
> 
> Btw, do you know what happens if `start_with_window` is `False`? I didn't understand what that parameter does. Might be worth explaining that better, in case you know what it does.

It will make like 'initial window = 0'. However, 'initial window' must be > 1.
start_with_window = False

Reference example wit 'start_with_window = True':
start_with_window = True

I'll try to update the documentation to cover this option.

**Comment by fkiraly** [comment]
> It will make like 'initial window = 0'. However, 'initial window' must be > 1.

That sounds pretty weird, it sounds like an unnecessary parameter.
Shouldn't this be controlled simply by `initial_window` then??

We should open an issue and possibly fix this in a separate PR.

**Comment by fkiraly** [comment]
I opened an issue here:
https://github.com/alan-turing-institute/sktime/issues/2678
thanks for explaining what that strange parameter did!

**Comment by fkiraly** [comment]
@keepersas, feel free to add yourself to allcontributor.src with a `doc` contribution!

**Pull request merged**
