### PR TITLE
Address Bug #640

### PR DESCRIPTION
**Pull request by patrickzib**
#### Reference Issues/PRs

Partially fixes Bug #640

#### What does this implement/fix? Explain your changes.

Removes Numba-signatures to add compatibility for PLAID, ASCF1, etc datasets with variable-length data

### CODE REVIEW

**Review by mloning — APPROVED** [review]
Thanks @patrickzib for the quick fix!

**Comment by patrickzib** [comment]
@mloning there seems to be a bug related to forecasting? do you known anything about it?

```
=========================== short test summary info ============================
1156
FAILED forecasting/tests/test_naive.py::test_strategy_mean_seasonal[5-3-1] - ...
1157
FAILED forecasting/tests/test_naive.py::test_strategy_mean_seasonal[5-3-fh1]
1158
FAILED forecasting/tests/test_naive.py::test_strategy_mean_seasonal[None-3-1]
1159
FAILED forecasting/tests/test_naive.py::test_strategy_mean_seasonal[None-3-fh1]
1160
FAILED forecasting/tests/test_naive.py::test_strategy_mean_seasonal[None-12-1]
1161
FAILED forecasting/tests/test_naive.py::test_strategy_mean_seasonal[None-12-fh1]
1162
========= 6 failed, 3209 passed, 35590 warnings in 1141.84s (0:19:01) ==========
1163
Error: Process completed with exit code 1.
```

**Comment by mloning** [comment]
A fix for the failing master is on its way: #643

**Comment by patrickzib** [comment]
@mloning I think, the checks have passed? though one shows pending but has actually completed?

**Comment by mloning** [comment]
@patrickzib now merged - thanks for the quick fix!

**Pull request merged**
