### PR TITLE
Adding AutoThetaForcaster class

### LINKED ISSUE #517: [ENH] Implement AutoTheta
**Describe the solution you'd like**
Translate code from the [R implementation](https://github.com/vangspiliot/AutoTheta) into Python. 

**Describe alternatives you've considered**
Consider implementing it as part of statsmodels rather than sktime and then interface it in sktime.

### PR DESCRIPTION
**Pull request by Aditya-Sihmar**
#### Reference Issues/PRs
Fixes #517 

#### What does this implement/fix? Explain your changes.

Implementing AutoTheta

#### Any other comments?

@mloning I tried the `NaiveForcaster` provided in sktime but it seems to be working with univariate time series while the R implementation works for multivariate data. Is there anything I am missing or shall I limit the input data to univariate?

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by mloning** [comment]
@Aditya-Sihmar the target variable`y` is always assumed to be univariate, the exogenous data `X` can be multivariate.

**Review by mloning — COMMENTED** [review]
@Aditya-Sihmar you need to make sure to follow the common API for forecasters. We're currently writing up some extension guidelines to make this clearer. For now, take a look at the `ThetaForecaster` as a template. I'd start by implementing `fit` and `predict`.

**Comment by Aditya-Sihmar** [comment]
Yeah @mloning, I will follow the API design

**Comment by mloning** [comment]
Hi @Aditya-Sihmar are you still planning on finishing this PR?

**Comment by Aditya-Sihmar** [comment]
Hello @mloning,
Sorry, I have been very busy lately so I am not able to work on the PR as
of now. If anyone wants to take up the task they welcome to do that or else
I will complete this once I get some time.

**Comment by Lovkush-A** [comment]
@mloning @Aditya-Sihmar This PR might need to be closed, based on new designs for the AutoThetaForecaster #854

**Comment by mloning** [comment]
Closed in favour of https://github.com/alan-turing-institute/sktime/discussions/854 - thanks @Lovkush-A

**Comment by Aditya-Sihmar** [comment]
Sorry @mloning I don't think I will be able to contribute anytime soon.

**Pull request closed without merging**
