### PR TITLE
[ENH] Kalman filter - transformers

### PR DESCRIPTION
**Pull request by NoaBenAmi**
#### Reference Issues/PRs

https://github.com/alan-turing-institute/sktime/issues/1011

#### What does this implement/fix? Explain your changes.
I have created two Kalman filter transformers, interfacing python libraries `pykalman` and `FilterPy`. 

#### Does your contribution introduce a new dependency? If yes, which one?

python libraries `pykalman` and `FilterPy`. 

#### What should a reviewer concentrate their feedback on?

Adaptation of `sktime` coding standards and suggestions for improving code quality.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by NoaBenAmi** [comment]
Hi @fkiraly :)
Here is the Kalman Filter draft PR we spoke about.

About denoising (given control variables [u], measurements [z], produce denoised z) with Kalman Filter -
Can it be implemented by first using `filter()` from `pykalman`, then using the output as input for the `rts_smoother()` (implementation of the Rauch-Tung-Striebal Kalman smoother)  from `FilterPy`?
Lines 347-358 in file `kalman_filter.py` 

By your advice about making one class per interfaced package, 'FilterPy' is only used in the lines mentioned above and can be removed easily.

**Comment by fkiraly** [comment]
> Can it be implemented by first using filter() from pykalman, then using the output as input for the rts_smoother() 

In theory, that would probably work, looking at the docs.

However, I would strongly advise against using both packages in the same class. Hopefully there is a way to smoothe/denoise using `pykalman` alone?

**Comment by fkiraly** [comment]
PS: the tests are failing since you didn't implement `get_test_params`.

**Comment by fkiraly** [comment]
All tests pass, great!

**Comment by fkiraly** [comment]
(let me know when you think this is ready for review)

**Review by fkiraly — APPROVED** [review]
Really nice contribution, @NoaBenAmi, @lielleravid, thanks a lot!
Much requested feature that a lot of people will be happy about.

**Comment by NoaBenAmi** [comment]
We were happy to do it🙂
Thank you for all the help, it is much appreciated.

**Pull request merged**
