### PR TITLE
Add aggregate argument to EnsembleForecaster

### PR DESCRIPTION
**Pull request by Ifeanyi30**
#### Reference Issues/PRs

fixes the issue #583

#### What does this implement/fix? Explain your changes.

 Adds the argument 'aggregate' to the predict method to select aggregate options.
#### Does your contribution introduce a new dependency? If yes, which one?

No
#### What should a reviewer concentrate their feedback on?
- [x] The predict method and the documentation in the fit method

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
@Ifeanyi30, thanks for your work!

Now, upon quick review, I notice you added the parameters to a private method (`_predict`).
There are two problems with this:
* this is not a method you would call as a user
* it breaks the "common interface pattern", i.e., all forecasters should have the same arguments and (key) methods.

Instead, parameters that control the behaviour of specific algorithms should be hyper-parameters, appear in the constructor and be settable there (see also discussion in #583). Would you kindly make that change? I.e., remove the `aggregate` argument` from `_predict` and move it to `__init__`, and add its description to the docstring.

**Comment by Ifeanyi30** [comment]
Thanks, I totally missed that.

**Comment by mloning** [comment]
For the code quality checks, please take a look at the contributing guidelines: https://github.com/alan-turing-institute/sktime/blob/09067a01bae159f4f08be2d687761e321928d6e5/CONTRIBUTING.md

**Review by mloning — COMMENTED** [review]
Hi @Ifeanyi30 - thanks again for the PR. 

In line with my comment on PR #773, could you revert the formatting changes and only include the files that actually changed?

**Comment by Ifeanyi30** [comment]
Hi Markus, I tried changing just that one file but the build test kept
failing I heard to change them the pre-commit to go through.

**Comment by mloning** [comment]
Hi @Ifeanyi30 - the code quality CI check run only  on the changed files, not the entire repo, so it shouldn't be a problem. I suggest you revert the other changes and let me know which tests fail on the files you changed.

**Comment by Ifeanyi30** [comment]
I have done it but then the code failed.

**Comment by mloning** [comment]
@Ifeanyi30 we can still salvage the PRs I think, I can help! Which ones are the files that you wanted to change?

**Comment by Ifeanyi30** [comment]
I closed the pull request and opened another one "Added the agg argument to
EnsembleForecaster".

**Comment by Ifeanyi30** [comment]
The problem was from my end

**Comment by mloning** [comment]
Closed in favour of #774

**Comment by Ifeanyi30** [comment]
Yeah

**Pull request closed without merging**
