### PR TITLE
Added ability to load from csv containing long-formatted data

### PR DESCRIPTION
**Pull request by AidenRushbrooke**
#### Reference Issues/PRs
Related to #434 and functionality requested by @TonyBagnall 

#### What does this implement/fix? Explain your changes.
I have implemented a function to allow for the reading of .csv files containing long-formatted data. It checks that the data is of the assumed format to be converted to an sktime usable format. I have also implemented some testing to ensure that it correctly reads the csv, and the format checks work.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

#### Any other comments?
Future improvements could include converting incorrectly formatted long-format data into the requried format automatically.

### CODE REVIEW

**Comment by mloning** [comment]
Happy to merge this, just a general note, we need to sort out the naming convention, "data frame" is ambiguous that's why I tried to refer to the nested pandas data frame for panel data simply as `nested` wherever possible

**Review by mloning — APPROVED** [review]
Happy to merge this - and thanks @AidenRushbrooke for working on this! 

Just a few general comments:

* we need to sort out the naming convention, "data frame" is ambiguous that's why I tried to refer to the nested pandas data frame for panel data simply as `nested` wherever possible 
* having almost 1k lines of code for testing loading functionality seems a bit odd, not sure why this is needed, perhaps that could be cleaned up as well 
* the `generate_example_long_data` should also be made private at least or be moved to the test file

**Comment by TonyBagnall** [comment]
thanks Aiden, if you update to master we can merge it

**Review by TonyBagnall — APPROVED** [review]
looks good

**Pull request merged**
