### PR TITLE
Refine the Docstrings for BOSS Classifiers

### PR DESCRIPTION
**Pull request by RNKuhns**
#### Reference Issues/PRs

This is a portion of #1148 and related to #1164 

#### What does this implement/fix? Explain your changes.

Refines the docstrings for the BOSS classifiers to make them consistently match our preferred format and render better  in our API reference via Sphinx. 

#### Does your contribution introduce a new dependency? If yes, which one?

None

#### What should a reviewer concentrate their feedback on?

Whether the docstrings conform to our preferred format (See #1148) and importantly whether the information in the docstrings are correct. 

Also we may prefer the classifier docstring examples from #1164. May want to take a quick look there and see if that looks reasonable and we can merge this after that (assuming that looks good and is a quick merge). 

#### Any other comments?

I've got a few placeholders that are requesting information to finish populating the docstring from the reviewers. 

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by RNKuhns** [comment]
@TonyBagnall or @MatthewMiddlehurst can you take a look at this and make sure the info in the docstrings is factually correct? 

Also, you'll notice in `IndividualBOSS` that I've put in a placeholders in a few spots where I need some information to complete the docstrings. If you can post a comment with that, I'll add an additional commit to include it (we clearly want to get rid of the placeholder info before merging).

**Review by TonyBagnall — DISMISSED** [review]
look fine to me, fair play for your attention to detail!

**Comment by TonyBagnall** [comment]
norm : bool, default = False
whether to normalise the series prior to word extraction
    alphabet_size : default = 4
number of possible values for any letter in a word
    save_words : bool, default = True
not sure actually, will let matt answer that!

**Review by MatthewMiddlehurst — COMMENTED** [review]
I like this, I noticed some of the pages were not some great when googling them (i.e. https://www.sktime.org/en/latest/api_reference/modules/auto_generated/sktime.classification.dictionary_based.BOSSEnsemble.html), so it would be good to see if this makes an improvement so it can be applied elsewhere.

I have left a few comments for the missing parts, your examples will conflict with a previous PR into main, but it should not be that difficult to resolve. The examples seem to be the reason for the test failures also?

**Comment by RNKuhns** [comment]
@MatthewMiddlehurst can you take one more quick look. I've incorporated your comments and the examples from main. 

I've noticed (under details in the docs/readthedocs.org:sktime CI check section above) that the See Also section isn't rendering exactly how I expected. In the performance_metrics API reference that is showing up with links to the other metrics listed there, but that isn't working here. 

Other than any comments from you, I'll figure out how to fix the issue in See Also ahead of merging this. 

Then we can start to roll this format out to all the classifiers.

**Review by MatthewMiddlehurst — APPROVED** [review]

**Review by TonyBagnall — APPROVED** [review]
looks good, thanks for doing this

**Pull request merged**
