### PR TITLE
Add date-time support for forecasting framework

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
#347, #220

#### What does this implement/fix? Explain your changes.
* Support for `pd.DatetimeIndex`, `pd.PeriodIndex` in data and forecasting horizon, including helper functions to patch mathematical operations on pandas date/time objects for our purposes (mostly returning integers for known time unit, rather than time delta objects)
* Included forecasting data sets are now returned with `pd.PeriodIndex`
* Support for absolute forecasting horizon specification via refactored `ForecastingHorizon` class
* Easy importing via `sktime.forecasting.all` module enabling `from sktime.forecasting.all import *` following [fastai](https://www.fast.ai/2020/02/13/fastai-A-Layered-API-for-Deep-Learning/)
* A few minor changes (typos, formatting, etc)
* Corresponding updates to forecasting notebook
* New unit tests for supported combinations of data index types and forecasting types

#### Does your contribution introduce a new dependency? If yes, which one? 
* seaborn (soft dependency, for plotting) 

#### Key files to review 
Since the forecasting horizon was used in basically every forecasting algorithm, this PR makes changes to many files. Key changes include:

* `sktime/forecasting/base/_fh.py` (implementation of forecasting horizon class)
* `sktime/forecasting/base/tests/test_fh.py` (unit tests for forecasting horizon class)
* `sktime/forecasting/tests/_config.py` (check SUPPORTED_INDEX_FH_COMBINATIONS)
* `sktime/forecasting/tests/test_all_forecasters.py` (unit testing framework for all forecasters)
* `sktime/utils/datetime.py` (date/time helper functions)

#### Comments
* Supporting only `pd.PeriodIndex` and not `pd.DatetimeIndex` would make the code a bit simpler as `pd.DatetimeIndex` requires additional patches to return integers for durations/time deltas and additional type distinctions (dispatch), however it seems like `pd.DatetimeIndex` supports some functionality which is not supported by `pd.PeriodIndex` (e.g. `is_month_end`)

#### Future work
* refactor `BaseLastWindowForecaster` and reduce inheritance as much as possible

### CODE REVIEW

**Comment by mloning** [comment]
@fkiraly I've made some changes after our conversation, mostly refactored the helpers functions, and added a list of key files to review.

**Review by fkiraly — COMMENTED** [review]
All in all, this seems to be working.
Some comments below, as discussion/questions.
One comment for other reviewers: I think the changes in `_sktime` are also important to look at.

On the design level, I am a bit worried about:
(i) unclear scityping
(ii) no support for time like relative indices

I'd suggest to have a uniform external interface, which has only the following distinctions in the type:
* relative/absolute
* time like vs index like

and think about machine type defaults. Subclassing, maybe?
Currently, there is a lot of overhead due to what I think is not a very clear distinction between index like and time like.

More detailed comments:

`_fh.py`
* there are a lot of type based case distinctions in the code. Would it be cleaner, and more extensible, to use `functools.singledispatch`?
* I'm disturbed by the fact that I cannot come up with a combination of decorators or inheritance that would solve the problem with delegating methods and wrapping of the pandas objects - maybe @big-o has an idea?
It seems to work though.
* my gut feeling is also a bit mixed about the decision to have multiple internal representations (the `SUPPORTED_INDEX_TYPES`, instead a "standardized internal state". Though again, it is hard to come up with cases or types that do not somehow duplicate the separation in different types of indices in `pandas`.
* do we not want to support time or time difference like indices for relative indices? Any reason why we don't want `timedelta` to be an option in relative?
* as a side effect to disallowing relative time like horizons, we get `_coerce_duration_to_int`, is that correct?
* instead of manually looping through `__len__` and `__getitem__`, should these not be added to `DELEGATED_METHODS`?
* for partial downwards compatibility, should `to_out_of_sample` remain `out_of_sample`?
* instead of `len(fh_oos) == len(fh):` check etc, perhaps introduce a `is_past` or so check?

`utils.datetime`
* this is very hard to read, since there are no docstring, and the devil is in the details: which argument types (integer, datetime) is expected, which are supported? It's easy to introduce subtle bugs, and lack of specs makes maintenance by others very difficult.
* again, due to numerous case distinctions by type, seems a candidate for `functools.singledispatch`?

**Comment by mloning** [comment]
Thanks @fkiraly for the review. 

* Re adding support for more types like `pd.TimeDelta`: (1) it would add more case distinctions (e.g. because pandas does not consistently handle collections of duration types (see below)), (2) specifying a forecasting horizon with durations seems redundant as the time unit will always be specified in the data, (3) I don't think using duration types is very intuitive from a user's perspective and can't think of a situation where I would prefer passing duration types rather than integers
* We need `_coerce_duration_to_int()` because some of our algorithms internally and other package we interface require integer forecasting horizons, not duration types.  
* One reason why we need so many case distinctions is that pandas doesn't seem to be very consistent with the typing. For example, multiple pd.TimeDelta (duration for timestamp type) are collected in a pd.TimeDeltaIndex, but multiple pd.DateOffsets (from duration for pd.Period type) are collected in a simple pd.Index with individual pd.DateOffsets inside. 
* I'm going to move `__getitem__` and `__len__` to `DELEGATED_METHODS`
* Re downward compatibility, at this stage I prefer consistency of method names over compatibility, adding deprecation cycles will complicate and slow dev work considerably I think, also the ForecastingHorizon was mainly used internally, it was included in the notebooks for example
*  I'm going to add some unit tests for the date-time utility functions and better docstrings
* I'm going to add something like `has_out_of_sample_values` and `has_in_sample_values` and caching to avoid computing the same things twice

**Comment by mloning** [comment]
I've implemented a few suggested changes. Let me know if there's anything else you would definitively change.

**Review by fkiraly — APPROVED** [review]
Tentatively happy with the state and recent changes.

Even if issues remain (unspotted etc), it´s downwards compatible in signature, and this will allow us to get feedback from users.

**Pull request merged**
