### PR TITLE
[BUG] changed wrong docstring default value of `start_with_window` in `SlidingWindowSplitter` to actual default value

### LINKED ISSUE #3315: [DOC] Docstring lists wrong default for `SlidingWindowSplitter` parameter `start_with_window`
Default for this argument is actually True.

https://github.com/alan-turing-institute/sktime/blob/824804c785fb97e20c29045ee058181ceeb9418b/sktime/forecasting/model_selection/_split.py#L1107

### PR DESCRIPTION
**Pull request by bugslayer-332**
#### Reference Issues/PRs

Fixes #3315.

#### What does this implement/fix? Explain your changes.

The default value was mentioned to be False, but it should be True, in the code, it has been rightly used but, in the comments, there was an error. Changed the default value.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — DISMISSED** [review]
Straightforward fix, thanks!

**Comment by fkiraly** [comment]
the bug has been slayed, but the linter is dismayed

**Comment by fkiraly** [comment]
... or, slain?

**Comment by bugslayer-332** [comment]
I am not sure why are these tests are failing :(. Can you tell what can I do now?

**Comment by fkiraly** [comment]
code formatting. Click here to see the code quality checker report:
image

You can also set this up locally - very helpful, see sktime developer gude here:
https://www.sktime.org/en/stable/developer_guide/coding_standards.html

Side note: it is in code that you didn't change, but it rechecks entire files where changes occur. There was a change in the linter defaults around exponent spacing recently, so now it notices it for the file you changed.

**Comment by bugslayer-332** [comment]
@fkiraly do i need to create a new PR now ?

**Comment by fkiraly** [comment]
>@fkiraly do i need to create a new PR now ?

No, just push new commits to your branch, and the PR will update, too.

**Comment by bugslayer-332** [comment]
@fkiraly, have done. Can you see once.

**Comment by bugslayer-332** [comment]
@aiwalter Can you take a look?

**Comment by bugslayer-332** [comment]
@fkiraly, @aiwalter  code satisfying the coding standards. Still, the tests are failing. Does this mean that this code might not work on those Operating systems? If yes, what might be the fix, I have observed similar tests failing in other PRs as well.

**Comment by fkiraly** [comment]
Failures are not your fault, related to another estimator that made it onto `main` by accident (the one failing the test), see here: https://github.com/alan-turing-institute/sktime/pull/3350

if you update your branch from `main`, it should all be fine.

**Comment by bugslayer-332** [comment]
@fkiraly, I have been updating from the main itself. Now should I change something or can this be merged?

**Comment by bugslayer-332** [comment]
@fkiraly, can you approve the running workflow?

**Comment by bugslayer-332** [comment]
@fkiraly all the tests have passed. Now can you please merge the code?

**Pull request merged**
