### PR TITLE
removing tests for data downloader dependent on third party website, change in test dataset for test_time_series_neighbors

### PR DESCRIPTION
**Pull request by TonyBagnall**
Two testing improvements:

1. Remove test for data downloads that is dependent on a third party website #1257 

2. Change test dataset in test_time_series_neighbors to use UnitTest instead of ItalyPowerDemand.  #1235

### CODE REVIEW

**Review by fkiraly — DISMISSED** [review]
makes sense for me - it's really mysterious why the download test is suddenly failing for me.
Perhaps the website is thinking it's ddos...

**Review by MatthewMiddlehurst — APPROVED** [review]

**Comment by fkiraly** [comment]
Oh look, it's this again https://github.com/alan-turing-institute/sktime/issues/1194
@aiwalter, @RNKuhns

**Comment by TonyBagnall** [comment]
Sporadic, so I'll rerun the whole lot!

**Comment by TonyBagnall** [comment]
ran again and it goes away

**Pull request merged**
