### PR TITLE
[BUG] Fixing forecast horizon index bugs

### LINKED ISSUE #1435: [BUG] ForecastingHorizon does not work for periods of N time units, N>1, e.g., 30min `PeriodIndex`
**Describe the bug**
Although the example in the documentation works, AutoETS and ExponentialSmoothing errors out when we use a sub-daily frequency of data

Error Message:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-49-df19e8e04e62> in <module>()
      1 forecaster = AutoETS(sp=12, auto=True,n_jobs=-1)
      2 forecaster.fit(y)
----> 3 y_pred = forecaster.predict(fh=[1,2,3])

6 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1296             if missing == len(indexer):
   1297                 axis_name = self.obj._get_axis_name(axis)
-> 1298                 raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   1299 
   1300             # We (temporarily) allow for some missing keys with .loc, except in

KeyError: "None of [PeriodIndex(['2021-09-20 01:00', '2021-09-20 01:30', '2021-09-20 02:00'], dtype='period[30T]', freq='30T')] are in the [index]"
```
**To Reproduce**

```python
import numpy as np
import pandas as pd
from sktime.forecasting.ets import AutoETS

freq = "30T"
_y = np.arange(50) + np.random.rand(50) + np.sin(np.arange(50)/4)*10
t = pd.date_range("2021-09-19", periods=50, freq=freq)
y = pd.Series(_y, index=t)
y.index = y.index.to_period(freq=freq)
forecaster = AutoETS(sp=12, auto=True,n_jobs=-1)
forecaster.fit(y)
y_pred = forecaster.predict(fh=[1,2,3])
```

**Expected behavior**

Forecast for the future without an error

**Additional context**

**Versions**
<details>

System:
    python: 3.7.12 (default, Sep 10 2021, 00:21:48)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic

Python dependencies:
          pip: 21.1.3
   setuptools: 57.4.0
      sklearn: 0.24.2
       sktime: 0.8.0
  statsmodels: 0.12.2
        numpy: 1.19.5
        scipy: 1.7.1
       Cython: 0.29.24
       pandas: 1.1.5
   matplotlib: 3.4.3
       joblib: 1.0.1
        numba: 0.54.0
     pmdarima: 1.8.2
      tsfresh: 0.18.0

</details>

### LINKED ISSUE #1876: [BUG] Forecasting does not work with 10 minute interval data in PeriodIndex form
**Describe the bug**
When data has a period index at 10 minute intervals, the prediction does not work.

Most likely related to 
Seems to be some issue with the indexing - most likely related to `ForecastingHorizon.to_absolute_int()` and how `integers` are computed.

```python
# Inside to_absolute_int, the following line does not seem to be giving the right integers
integers = absolute - start
```

**To Reproduce**
```python
import pandas as pd
from sktime.datasets import load_airline
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
y = load_airline()

# Change index to 10 min interval
time_range = pd.date_range(
    pd.to_datetime("2019-01-01 00:00"), pd.to_datetime("2019-01-01 23:55"), freq="10Min"
)

# # Datetime Index works
# y.index = time_range

# Period Index does not work
y.index = time_range.to_period()

forecaster = ExponentialSmoothing(trend="add", seasonal="multiplicative", sp=12)
forecaster.fit(y, fh=[1, 2, 3, 4, 5, 6])
y_pred = forecaster.predict()
```

```python
File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Nikhil\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Nikhil\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\Nikhil\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Nikhil\OneDrive\my_libraries\my_python_libraries\pycaret\pycaret_dev\time_series_debug.py", line 33, in <module>
    y_pred = forecaster.predict()
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\sktime\forecasting\base\_base.py", line 242, in predict
    alpha=alpha,
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\sktime\forecasting\base\adapters\_statsmodels.py", line 92, in _predict
    return y_pred.loc[fh.to_absolute(self.cutoff).to_pandas()]
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\lib\site-packages\pandas\core\indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [PeriodIndex(['2019-01-02 00:00', '2019-01-02 00:10', '2019-01-02 00:20',\n             '2019-01-02 00:30', '2019-01-02 00:40', '2019-01-02 00:50'],\n            dtype='period[10T]')] are in the [index]"
```

**Expected behavior**
Should produce the right forecasts (6 future values at 10 minute intervals - i.e. [PeriodIndex(['2019-01-02 00:00', '2019-01-02 00:10', '2019-01-02 00:20', '2019-01-02 00:30', '2019-01-02 00:40', '2019-01-02 00:50'])

**Additional context**

**Versions**
<details>

System:
    python: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_0p7\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 21.1.3
   setuptools: 52.0.0.post20210125
      sklearn: 0.24.2
       sktime: 0.8.0
  statsmodels: 0.12.2
        numpy: 1.19.5
        scipy: 1.5.4
       Cython: 0.29.14
       pandas: 1.3.0
   matplotlib: 3.4.2
       joblib: 1.0.1
        numba: 0.53.1
     pmdarima: 1.8.2
      tsfresh: None

</details>

### LINKED ISSUE #1935: [BUG] `ForecastingHorizon.to_relative` wrongly converts `pd.index` with frequencies that are base frequency multiples to `int`s
**Describe the bug**

`ForecastHorizon.to_relative` is wrong when using pandas date ranges with frequencies that are multiples of base frequencies (e.g "2H", "30T", "10D").
I believe the cause is the function `_coerce_duration_to_int`.

Seems to be related to #1435 and #1876 (sorry if this is a duplicate)

**To Reproduce**

```python
import pandas as pd
from sktime.forecasting.base import ForecastingHorizon

freq = '2H'
t = pd.date_range(start='2021-01-01', freq=freq, periods=5)
fh_abs = ForecastingHorizon(t, is_relative=False)
fh_rel = fh_abs.to_relative(cutoff=t.min())
print(fh_rel)
```
Output:
```
ForecastingHorizon([0, 4, 8, 12, 16], dtype='int64', is_relative=True)
```

**Expected behavior**

Output should be:
```
ForecastingHorizon([0, 1, 2, 3, 4], dtype='int64', is_relative=True)
```
no matter what `freq` is.

To see this bug in action, consider the following example of using a NaiveForecaster to predict a perfectly periodic time series:
```python
import pandas as pd
import numpy as np
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.naive import NaiveForecaster

sp = 5  # period
n = sp * 2  # number of samples

y = pd.Series(
    index=pd.date_range(start='2021-01-01', freq='2H', periods=n),
    data=np.mod(np.arange(n), sp),
)

y_train, y_test = temporal_train_test_split(y, test_size=sp)
fh = ForecastingHorizon(y_test.index, is_relative=False)
forecaster = NaiveForecaster(strategy="last", sp=sp)
forecaster.fit(y_train)
y_pred = forecaster.predict(fh)
print(y_test, y_pred, np.abs(y_pred - y_test).max(), sep='\n\n')
```

Output:
```
2021-01-01 10:00:00    0
2021-01-01 12:00:00    1
2021-01-01 14:00:00    2
2021-01-01 16:00:00    3
2021-01-01 18:00:00    4
Freq: 2H, dtype: int64

2021-01-01 10:00:00    3.0
2021-01-01 12:00:00    2.0
2021-01-01 14:00:00    1.0
2021-01-01 16:00:00    0.0
2021-01-01 18:00:00    4.0
dtype: float64

3.0
```
**Versions**
<details>

Python 3.9.5 (default, May 18 2021, 12:31:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.0.1
System:
    python: 3.9.5 (default, May 18 2021, 12:31:01)  [Clang 10.0.0 ]
executable: /Users/tomshlomo/miniconda3/envs/playground-395/bin/python
   machine: macOS-10.15.7-x86_64-i386-64bit
Python dependencies:
          pip: 21.1.1
   setuptools: 52.0.0.post20210125
      sklearn: 1.0.2
       sktime: 0.9.0
  statsmodels: 0.13.1
        numpy: 1.20.2
        scipy: 1.6.2
       Cython: 0.29.26
       pandas: 1.2.4
   matplotlib: 3.3.4
       joblib: 1.0.1
        numba: 0.54.1
     pmdarima: None
      tsfresh: 0.17.0
</details>

### PR DESCRIPTION
**Pull request by eenticott-shell**
#### Reference Issues/PRs
Fixes #1935. Fixes #1435. Fixes #1876. 

#### What does this implement/fix? Explain your changes.
Within the forecasting horizon methods `to_relative` and `to_absolute_int` coerces absolute and cutoff to the same type to avoid an error that can occur in `pandas` where time differences are multiplied by the frequency multiple (i.e. 2H multiplies the difference by 2). This caused numerous index errors.

 #### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
Whether forcing the type of the input to change could have unintended consequences.

### CODE REVIEW

**Comment by fkiraly** [comment]
Ouch - the notebook failure is, I guess, one of these "unintended consequences"? 😄

**Comment by eenticott-shell** [comment]
Yes, although it was expected that it might fail somewhere due to these changes, now I just need to work out how to fix the bugs without breaking anything else!

**Comment by khrapovs** [comment]
It seems to me that if we fix this test, then we would fix all of the mentioned bugs, and a broken notebook.
```
@pytest.mark.parametrize("idx", range(5))
@pytest.mark.parametrize(
    "freq", ["10Min", "H", "1D", "2D", "W-WED", "W-SUN", "W-SAT", "M"]
)
def test_to_absolute_int(idx: int, freq: str):
    """Test converting between relative and absolute."""
    # Converts from relative to absolute and back to relative
    train = pd.Series(1, index=pd.date_range("2021-10-06", freq=freq, periods=5))
    fh = ForecastingHorizon([1, 2, 3])
    absolute_int = fh.to_absolute_int(start=train.index[0], cutoff=train.index[idx])
    assert_array_equal(fh + idx, absolute_int)
```

**Comment by fkiraly** [comment]
>It seems to me that if we fix this test, then we would fix all of the mentioned bugs, and the broken notebook.

That's only half correct ... the challenge may be fixing this test *without breaking all the others* 😄

**Pull request closed without merging**
