### PR TITLE
fixed the issue with 'docs/source/developer_guide/testing_framework.rst'

### LINKED ISSUE #2283: [DOC] typo in `testing_framework.rst`
Typo or formatting issue in `testing_framework.rst`, should be easy to fix:

image

(this should be a bullet point list, starting at "an `args` parameter")

### PR DESCRIPTION
**Pull request by 0saurabh0**
#### Reference Issues/PRs
Fixes  #2283

#### What does this implement/fix? Explain your changes.
fixed the bullet issue.

#### Any other comments?
 hopefully it'll work, otherwise if any changes required let me know.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [DOC] or [BUG] indicating wether the PR topic is related to enhancement, documentation or bug

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks a lot!

Quick note, linting is failing for some lines - whitespaces, perhaps.

**Comment by 0saurabh0** [comment]
looks good ?

**Comment by fkiraly** [comment]
yes, great!
Linting is failing unfortunately, if you need instructions, see here: https://github.com/alan-turing-institute/sktime/pull/2289

**Comment by 0saurabh0** [comment]
fixed the linting issues.
kindly approve.??

**Comment by 0saurabh0** [comment]
It's all done ??

**Comment by fkiraly** [comment]
Excellent, thanks for your hard work!

Not sure whether you still have the time to fix these, I still spot five instances of the issue, starting with sentences (search for sentences starting with the following combinations of words):
* estimator_instance over estimator instance
* Introducing or changing base class level interface points 
* adding a function _generate_[variablename](test_name, **kwargs), as described below
* a list of fixture to loop over, to substitute
* test_name, the name of the test the variable is called in
* example fixture generation, via datatypes.get_examples

Let me know if you don't have time, then we'll just merge as is.

**Comment by 0saurabh0** [comment]
I can fix them. 
let me try.

**Comment by 0saurabh0** [comment]
fixed as told.
have a look?? 
let me know

**Comment by lmmentel** [comment]
Thanks @0saurabh0 !

**Comment by fkiraly** [comment]
🎉 thanks a lot @0saurabh0 !! 🎉 
(and thanks for your patience and perseverance)

**Pull request merged**
