### PR TITLE
Fix minor silent issues in TransformedTargetForecaster

### PR DESCRIPTION
**Pull request by aiwalter**
Fix minor silent issues in `TransformedTargetForecaster`
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

### CODE REVIEW

**Comment by aiwalter** [comment]
Sry I should have included this into #967 already. I was just thinking about `pred_int` and I guess we actually have to also apply `inverse_transform` of transformers on them in case of the `TransformedTargetForecaster`, right?

**Review by mloning — DISMISSED** [review]

**Comment by aiwalter** [comment]
`inverse_transform` is now also applied to `pred_int` in `TransformedTargetForecaster`

**Review by mloning — DISMISSED** [review]
I think we need to refactor the interface for prediction intervals (see https://github.com/alan-turing-institute/sktime/issues/984) but happy to include this now as it is

**Review by mloning — APPROVED** [review]
Looks all good to me!

**Comment by mloning** [comment]
Now merged!

**Pull request merged**
