### PR TITLE
Refactor sktime/.../_panels/_examples.py for tsai compatibility

### LINKED ISSUE #1452: [BUG] sktime.datatypes._panel._examples raises pandas.core.common.SettingWithCopyError
**Describe the bug**
Attempting to install [tsai](https://pypi.org/project/tsai/) as an upstream package also installs this package, but the install raises an error that traces to line 67 in "/opt/conda/lib/python3.8/site-packages/sktime/datatypes/_panel/_examples.py"
```
    X.iloc[0][0] = pd.Series([1, 2, 3])
```

**To Reproduce**
Importing any code that executes the code starting at line 67 of /sktime/datatypes/_panel/_examples.py can raise a Pandas error, depending on Pandas version that may be installed

**Expected behavior**
No error should be raised on install or import of sktime as a dependency. 

**Additional context**

**Versions**
System:
    python: 3.9.1 (default, Sep 16 2021, 11:42:30)  [Clang 12.0.5 (clang-1205.0.22.11)]
executable: /.../.pyenv/versions/3.9.1/bin/python
   machine: macOS-11.6-x86_64-i386-64bit

Python dependencies:
          pip: 21.2.4
   setuptools: 49.2.1
      sklearn: 1.0
       sktime: 0.8.0
  statsmodels: 0.12.2
        numpy: 1.20.3
        scipy: 1.7.1
       Cython: None
       pandas: 1.3.3
   matplotlib: 3.4.3
       joblib: 1.0.1
        numba: 0.53.1
     pmdarima: None
      tsfresh: 0.18.0

### PR DESCRIPTION
**Pull request by bobbys-dev**
#### Reference Issues/PRs
Fixes #1452  [#1452](https://github.com/alan-turing-institute/sktime/issues/1452)

#### What does this implement/fix? Explain your changes.
`X.iloc[0][1] = ...` and similar assignments will raise a
SettingWithCopy error in later versions of Pandas.
Refactor the respective lines for compatibility
up to v1.3.3 while maintaining same value assignments to dataframe

#### Does your contribution introduce a new dependency? If yes, which one?
No new dependency

#### What should a reviewer concentrate their feedback on?
Refactor should produce same result and behaviour as previous code intended

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [X] I've added unit tests and made sure they pass locally.

### CODE REVIEW

**Comment by fkiraly** [comment]
Thanks for the fix - would you mind resolving the merge conflict in all-contributors?

**Comment by fkiraly** [comment]
PS: I can't reproduce the bug in https://github.com/alan-turing-institute/sktime/issues/1452, but there's no harm in changing this to sth that seems safer - so would accept once it's mergeable.

**Comment by bobbys-dev** [comment]
@fkiraly Thanks for looking at this PR and issue. The change shouldn't affect the intended behavior of `_examples.py`.

**Comment by fkiraly** [comment]
It's failing code formatting checks - can you please take care of that?
If you check the `code-quality` CI checks, it will tell you that you will need to format the code like this:
```
X["var_0"] = pd.Series(
    [pd.Series([1, 2, 3]), pd.Series([1, 2, 3]), pd.Series([1, 2, 3])]
)
```

(if you are planning to be a frequent contributor, I would recommend to set up linting and/or pre-commits, otherwise you can just copy-paste this formatting)

**Comment by fkiraly** [comment]
Still not quite 😄 
image
It's a (mildly annoying) journey

**Comment by fkiraly** [comment]
generic "learning nugget" is using python linting in professional dev IDE - feel free to join our collaborative coding sessions if you want a demo

**Comment by fkiraly** [comment]
there's still one left (trailing whitespace I think) - not going to print this out again, the challenge is finding it

Hint: first step is clicking here
image

**Comment by bobbys-dev** [comment]
Thanks for being patient. I must not be understanding when the quality checks are ran in Github. I saw a pass and thought it was good to go but I guess the check wasn't complete yet(?). Anyway, I ran the precommit hook as mentioned and should be clean now.

**Comment by fkiraly** [comment]
>Thanks for being patient. I must not be understanding when the quality checks are ran in Github.

Since you're not a frequent contributor, some of them they only run when a core developer kicks them off - you probably only saw the part of the test suite that passed already.

>Anyway, I ran the precommit hook as mentioned and should be clean now.

Yes, congratulations! 🎉 
Thanks for being patient to you too 😄

**Review by fkiraly — APPROVED** [review]
All good now.

**Pull request merged**
