### PR TITLE
Update CI and maintenance tools

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
#196 

#### What does this implement/fix? Explain your changes.
- [x] pre-commit config 
- [x] additional code quality checks from `check-manifest`, `flake8-bugbear`, `flake8-print`
- [x] code formatting using Black
- [x] updated CONTRIBUTING.md to explain how to use pre-commit
- [x] minor clean up from new checks: added missing init files, remove redundant feature-importance-graph file (detected by check-manifest)
- [x] enforces pre-commit checks on the CI servers for changed files only (not all files currently pass), replaces flake8 linting checks on azure dev ops
- [x] adds Codecov with badge in README for unit test coverage reporting
- [x] add informational coverage threshold for new PRs

#### Comments
Leaving existing linting checks on azure dev ops untouched for now.

### CODE REVIEW

**Comment by mloning** [comment]
Hi @big-o I've finally added black with pre-commit, let me know what you think.

**Comment by big-o** [comment]
Looks great! I don't know too much about flake8, but if black is a strict subset of it then maybe you'd be able to remove the flake8 checks?

**Comment by mloning** [comment]
They seem to check slightly different things, so I'll leave them in for now.

**Comment by mloning** [comment]
Self-reviewed. Looks all good to me. @fkiraly or @big-o let me know if you have time to review.

**Pull request merged**
