### PR TITLE
Fixed the wrong KNNClassification with DTW as a distance

### PR DESCRIPTION
**Pull request by Abelarm**
Fixing issue #413 

introducing the dependence to the tslearn, fixed the test for the KNeighborsTimeSeriesClassifier that checks in the case the parameter is a callable and the param name is a metric if it is the correct function

Changed the dtw function from `sktime.distances.elastic_cython` to `from tslearn.metrics import cdist_dtw as dtw_distance`
Fixed the test for the KNeighborsTimeSeriesClassifier as well.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by mloning** [comment]
Can we add tslearn as a soft dependency using this helper function [here](https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/check_imports.py) to check if it has been installed?

**Comment by Abelarm** [comment]
ok I have added the check of "tslearn" with the helper function, but now I don't know where to put the actual version of tslearn to be installed? Before it was in the `MIN_REQUIREMENTS` of `setup.py` but now I have moved inside the `EXTRAS_REQUIRE` but still seems that is not installed.

**Comment by mloning** [comment]
Please take a look at the contributing guide's [section on dependencies](https://github.com/alan-turing-institute/sktime/blob/master/CONTRIBUTING.md#dependencies)

**Comment by Abelarm** [comment]
Maybe the fix was not that fast as I expected...

**Comment by Abelarm** [comment]
I have to change different things, gonna close this PR :-1:

**Pull request closed without merging**
