### PR TITLE
[ENH] Proba metric grid search integration

### PR DESCRIPTION
**Pull request by eenticott-shell**
#### Reference Issues/PRs
Addresses #2233. Branches from #2232.

#### What does this implement/fix? Explain your changes.
Initial plan for grid search implementation.

#### Does your contribution introduce a new dependency? If yes, which one?
No

### CODE REVIEW

**Comment by fkiraly** [comment]
Hm, looks like it's crashing due to an ambiguity that `alpha` can be a list or a float, @eenticott-shell.

In the `BaseForecaster` this is ensured via the function `check_alpha` from `validation.forecasting` which ensures that the `alphas` passed to the inner functions are always a list.
(in case you are using it, would appreciate an addition to the docstring of `check_alpha` which seems to be missing a return - it's always a list of float)

**Comment by eenticott-shell** [comment]
Draft as I need to lint and finish implementing the changes.

**Comment by eenticott-shell** [comment]
Changed the wrong PR to draft by mistake.

**Comment by fkiraly** [comment]
Is this ready for review, or were you still working on it?

**Review by fkiraly — APPROVED** [review]
Merging so we can work on this as a dependency.

In the near future, we should:

* move the notebook to tests and/or the forecasting tutorial
* update the docstrings for evaluation & grid search accordingly

Let's discuss how we split this in the planning session.

**Pull request merged**
