### PR TITLE
[ENH] Added test for OptionalPassthrough

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
#3272

### CODE REVIEW

**Comment by fkiraly** [comment]
* I think we should also cover `fit`, with an estimator where `fit` is not empty. I would recommend `BoxCoxTransformer` as a second transformer
* the `try`/`assert` construction seems brittle - I would instead compare to a direct application of the estimator (e.g., `ExponentTransformer`) without wrapping in `OptionalPassthrough`

**Comment by fkiraly** [comment]
I meant, in addition, rather than, instead. I.e., mark.parametrize over estimator which can be exponential or boxcox?

**Comment by fkiraly** [comment]
(worst case, just copy-paste your old test in, and I´m also happy with that, mark.parametrize would be more elegant)

**Comment by aiwalter** [comment]
I anyway call `fit_transform` ,so where is the difference if fit is empty?

**Comment by fkiraly** [comment]
>I anyway call `fit_transform` ,so where is the difference if fit is empty?

If the wrapped `fit` is empty, the tag will be copied to `OptionalPassthrough`, so we do not test the delegation in `_fit`. Conversely, if the wrapped `fit` is not empty, we delegate, and do not test the skipping logic (both branches could hide bugs).

**Review by fkiraly — APPROVED** [review]
I think this is good enough as a basis for refactor, because it tests the more important of the branches (`fit` delegation), so I merge - would still appreciate covering the different cases here (separate PR)

**Pull request merged**
