### PR TITLE
[ENH] `FeatureUnion` refactor - moved to `transformations`, tags, dunder method

### PR DESCRIPTION
**Pull request by fkiraly**
This PR contains a refactor of `FeatureUnion`:
* move to `transformations.compose`, deprecate `series_as_feature` occurrence
* common refactor with `TransformerPipeliene`,  joint and duplicate methods moved to `_HeterogeneousEnsembleEstimator`
* tag handling
* `+` dunder method for `FeatureUnion`

Depends on PR #1810 which is included.

### CODE REVIEW

**Comment by lmmentel** [comment]
Nice work! Are you running the test that was originally failing for `FutureUnion` ?

**Comment by fkiraly** [comment]
> Nice work! Are you running the test that was originally failing for FutureUnion ?

Of course :-)

**Review by TonyBagnall — APPROVED** [review]
personally I would like to deprecate the whole module series_as_features, and this is a step to that. 

Maybe rename anytagis? Had trouble parsing that name, was thinking of haggis or tardis. maybe has_tag? but I leave it

**Comment by fkiraly** [comment]
> personally I would like to deprecate the whole module series_as_features, and this is a step to that.

Completely agreed, @TonyBagnall! It's a bit solitary and the "concern" it addresses is not entirely clear.
It does have some useful stuff, the other content being the splitters, which we should find a new home for first, though.

**Pull request merged**
