### PR TITLE
Implementation of signature based methods. 

### PR DESCRIPTION
**Pull request by jambo6**
An sktime implementation of the signature method for time series classification.

This is a modification from the previous PR as `signatory` has been replaced with `esig` that does not require torch and should be able to be included as a soft dependency. 

#### Does your contribution introduce a new dependency? If yes, which one?
Yes: esig

#### PR checklist
- [Yes] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [No] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [No] I've added unit tests and made sure they pass locally.
I will build some tests once I've got confirmation that everything builds on the various systems, as currently, this is a cause of much distress. 

##### For new estimators
- [No] I've added the estimator to the online documentation. 
- [No] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.
(I currently have a problem running linting on my jupyter documentation file, so it is left out for the moment. I do have one though)

### CODE REVIEW

**Comment by jambo6** [comment]
Tests are failing because `sktime/transformers/panel/signature_based` cannot be found. All these files were uploaded in the commit, what am I missing here?

**Comment by mloning** [comment]
@jambo6 `__init__` is missing?

**Comment by jambo6** [comment]
Ah, thanks.

I'm getting some linting test fails on the 'alan-turing-institute.sktime' runs, however it is on files that are not mine, for example `sktime/classification/dictionary_based`. I haven't edited any of these and have only an hour ago forked this from master so I'm not sure what is going on there. 

Also, the manylinux builds are just sitting on expected, I am not sure why.

**Comment by mloning** [comment]
@jambo6 alright, yes will look into it. They are stuck because they don't start when linting fails.

**Comment by mloning** [comment]
Once all tests pass, would you mind adding some unit tests too?

**Comment by jambo6** [comment]
Yes absolutely. I also have a jupyter example notebook to add, however I had some linting fails so will fix that too.

**Comment by mloning** [comment]
@jambo6 linting issues should be fixed now.

**Comment by mloning** [comment]
You need a `# noqa` with the soft dependency check before the imports - otherwise it'll complain that imports are not at the top of the file ...

**Comment by jambo6** [comment]
I've added noqa to the relevant places. However its failing on some other dependency checks of esig in the signature modules.

I've tried a few combinations of adding things to `SOFT_DEPENDENCIES` in `check_soft_dependencies.py`

```
SOFT_DEPENDENCIES = {
    "sktime.benchmarking.evaluation": ["matplotlib"],
    "sktime.transformers.panel.tsfresh": ["tsfresh"],
    "sktime.forecasting.arima": ["pmdarima"],
    "sktime.forecasting.all": ["pmdarima"],
    "sktime.classification.all": ["tsfresh"],
    "sktime.regression.all": ["tsfresh"],
    "sktime.classification.signature_based": ["esig"],
    "sktime.transformers.panel.signature_based": ["esig"],
}
```

However, it still finds a way to fail. Am I supposed to add anything to here? If so, what? I tried using the '.all' to no avail.

**Comment by mloning** [comment]
Hi @jambo6, you only have to list the modules that will import the soft dependencies. You don't have an `.all` module so that won't import anything. 

For the signature-based transformers module, I've moved everything to the top level (i.e. the `__init__`), please check if it contains all of the functions you want to expose publicly. 

One of the linux build still seems to fail because esig cannot be built. 

I should be able to take a closer look at the code over the next few days hopefully!

**Comment by jambo6** [comment]
Thanks very much for those edits. There was nothing about adding to the `SOFT_DEPENDENCIES` variable in the `CONTRIBUTING.md` file. Might be worth adding.

Im trying to work out the manylinux64x2010 issue with the esig developers at the moment. 

The code should now be finished if you are wanting to review it. The only things I need to add are the unittests and example notebook.

**Comment by mloning** [comment]
Alright great - we're getting closer! 

Yes, I agree about the soft dependencies - we need to add them to `CONTRIBUTING.md`.

I'll try to review the code over the next couple of days!

**Comment by mloning** [comment]
The easiest would be for them to produce a wheel. 

Alternatively we can skip the tests for that OS. We'd have to make some change to the unit tests (purest has a decorator for skipping tests already) and add some OS-dependent user warnings to the soft dependency check.

**Comment by jambo6** [comment]
Hi Markus, just to update on this:

I have opened an issue with esig for the manylinux2010 build, they have identified the issue, however, I am yet to hear back about whether this will be fixed in an update soon. 

If it is easy to add a rule to skip the manylinux2010 build, can we do that? If they fix the issue with esig I will notify you so it can (hopefully) be removed.

**Comment by mloning** [comment]
Sure, see if you can add a rule to skip manylinux2010 for signature-based functionality, let me know if you get stuck!

**Comment by jambo6** [comment]
Since it fails when trying to build esig, I would need to skip esig in the `pip install -r requirements.txt` call. This seems to be referenced in the azure-pipelines.yml file, however I do not know how I would implement a skip method here. Any ideas?

**Comment by mloning** [comment]
This seems like the same issue we've had with the other signature package ... not sure how to best do that without adding a lot of module-specific code to the CI scripts. What's their time frame for building the manylinux wheel?

**Comment by jambo6** [comment]
Haha, it is a different issue, the other one required an installation outside of requirements, this one wont install...

Ok, I will wait for them to update me on a fix for manylinux2010. They have not replied yet.

**Comment by mloning** [comment]
Yes okay sounds good - packaging the older manylinux wheel should hopefully not be too much trouble given that they already distribute the latest one

**Comment by jambo6** [comment]
Ok fingers crossed I have this sorted now. 

How am I supposed to handle black for the example notebook? I've tried running black_nbconvert (amongst other things) but it continues to fail, even manually doing stuff is not working as it wants a newline at the end of the file which I cannot force.

**Comment by jambo6** [comment]
Ok ignore the above, I have got the notebook to work with black. The way I did it was a bit hacky though, is there a proper way to do it?

**Comment by jambo6** [comment]
Rebase has destroyed me, I dont know why it doesn't play nice or how to fix it. Closing and reopening.

**Pull request closed without merging**
