### PR TITLE
Update .all-contributorsrc

### PR DESCRIPTION
**Pull request by Tomiiwa**
Added myself as a contributor

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
This refers to https://github.com/alan-turing-institute/sktime/pull/2285, is that correct?

Imo, that would be `"doc"`, but not `"design"` (= sktime architecture) and `"ideas"` (ideas on how to improve sktime or its operations).

**Comment by Tomiiwa** [comment]
yes, no problem then




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/23/22,
02:13:19 PM

**Review by Tomiiwa — COMMENTED** [review]
removed design and ideas emoji

**Review by fkiraly — APPROVED** [review]
alright!

Let's work on those other badges too :-)

**Pull request merged**
