### PR TITLE
[ENH] Fix incorrect `update_predict` arg default and docstring on `cv` arg

### PR DESCRIPTION
**Pull request by aiwalter**
#### What does this implement/fix? Explain your changes.
Fix update_predict default `cv` param. `None` was raising an exception, so it should not default to it.

### CODE REVIEW

**Comment by fkiraly** [comment]
would it perhaps be better to have a default of "time stamps are fed to the updating individually"?

**Comment by aiwalter** [comment]
> would it perhaps be better to have a default of "time stamps are fed to the updating individually"?

Where?

**Comment by fkiraly** [comment]
in `update_predict`

**Comment by aiwalter** [comment]
dont get what you mean 🤔

**Comment by fkiraly** [comment]
as a default for `cv` - if not passed, then all the time stamps should be individually added in sequence?

**Review by fkiraly — APPROVED** [review]
This is correct, according to `check_cv`.

I.e., not an interface change, that requires deprecation, but correction of the docstring.

**Pull request merged**
