### PR TITLE
Added tuning tutorial to forecasting example notebook

### PR DESCRIPTION
**Pull request by aiwalter**
Linked issue: #988

### CODE REVIEW

**Comment by fkiraly** [comment]
you need to resolve merge conflicts, @aiwalter

**Comment by aiwalter** [comment]
@fkiraly  yes, basically I dont know how to do this with jupyter notebook. I will rewrite/copy my stuff. Could you pls dont write sth in your notebook in the meanwhile? Otherwise there would be again a conflict..

**Comment by aiwalter** [comment]
@fkiraly could you pls review? Its only a short example I added, but would like to merge already before I get another merge conflict :)

**Comment by fkiraly** [comment]
closed in favour of #1047

**Pull request closed without merging**
