### PR TITLE
Make OptionalPassthrough to support multivariate input

### PR DESCRIPTION
**Pull request by aiwalter**
#### What does this implement/fix? Explain your changes.
`OptionalPassthrough` transformer was only accepting `pd.Series`. This was fixed to also accept `pd.DataFrame`
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

### CODE REVIEW

**Review by mloning — APPROVED** [review]
Looks all good to me.

**Review by fkiraly — APPROVED** [review]
looks good to me

**Comment by mloning** [comment]
@aiwalter you can merge this when it's ready to get this in before the next release.

**Comment by aiwalter** [comment]
I think I dont have rights to merge

**Comment by mloning** [comment]
Ah it didn't let you because it wasn't updated with main - now it's merged! 🎉

**Pull request merged**
