### PR TITLE
Docstring improvements for bats, tbats, arima, croston

### PR DESCRIPTION
**Pull request by Lovkush-A**
#### Reference Issues/PRs
See #1245 

#### What does this implement/fix? Explain your changes.
Updated docstrings in bats, tbats and arima and croston
Fixed a typo in boss docstring
Fixed referencing link in cboss docstring

#### Does your contribution introduce a new dependency? If yes, which one?
no

#### What should a reviewer concentrate their feedback on?
do the docstrings look good in the documentation
do all the links work

### CODE REVIEW

**Review by aiwalter — DISMISSED** [review]

**Comment by aiwalter** [comment]
seems some things regarding Reference are not formatted correctly:
https://sktime--1309.org.readthedocs.build/en/1309/api_reference/auto_generated/sktime.forecasting.arima.ARIMA.html#rdf5743a6daff-1

**Comment by Lovkush-A** [comment]
@RNKuhns @aiwalter 

I think the issue is we added `# noqa: E501` to dodgy the line-too-long error from flake8. Ryan, do you know how to have long URLS in our docstirngs? Maybe I have my precommit setup incorrectly...

**Comment by RNKuhns** [comment]
Looks like the doc-quality error is an easy fix: "See Also" section needs the capitalization. 

Additional feedback: 

**BATS/TBATS**

-  The parameter "sp" is not properly formatted (seems like it was probably like that to begin with). It needs to list type and default value (if applicable), but goes right into the description (I'd also move the note about what that parameter is called elsewhere to the end of the description section as most sktime users probably won't need to know that.)
- Goal for estimators is to include summary of algorithm. There is currently a brief summary (defines the components of the algorithm that make up the BATS and TBATS names), but a longer extended summary that has a bit more explanation would be good.
- Am I correct in remembering from the R implementations that these might be good for multiple seasonality? If so that is something that would be good to mention in the docstring (helps users decide why they might pick the algorithms)

**Croston**

- Need summary of Croston's algorithm in the extended summary.

**Arima**

-  Method parameter description and Sarimax kwargs parameter description are likely not rendering as intended. Probably a spacing issue related to the lists (maybe need spaces prior to and after the list?)

**Auto-Arima**
- Method parameter description also not rendering as intended. Probably need same formatting changes *Arima* model.

**Review by RNKuhns — DISMISSED** [review]
Looks like the doc-quality error is an easy fix: "See Also" section needs the capitalization. 

Additional feedback: 

**BATS/TBATS**

- [x]  The parameter "sp" is not properly formatted (seems like it was probably like that to begin with). It needs to list type and default value (if applicable), but goes right into the description (I'd also move the note about what that parameter is called elsewhere to the end of the description section as most sktime users probably won't need to know that.)
- [x] Goal for estimators is to include summary of algorithm. There is currently a brief summary (defines the components of the algorithm that make up the BATS and TBATS names), but a longer extended summary that has a bit more explanation would be good.
- [x] Am I correct in remembering from the R implementations that these might be good for multiple seasonality? If so that is something that would be good to mention in the docstring (helps users decide why they might pick the algorithms)

**Croston**

- [x] Need summary of Croston's algorithm in the extended summary.

**Arima**

- [x] Method parameter description not rendering correctly
- [x] Sarimax kwargs parameter description are likely not rendering as intended. 

Both are probably a spacing or related formatting issue (maybe need spaces prior to and after the list?)

**Auto-Arima**
- [x] Method parameter description also not rendering as intended. Probably need same formatting changes *Arima* model.

**Comment by Lovkush-A** [comment]
@RNKuhns @aiwalter

> I think the issue is we added `# noqa: E501` to dodge the line-too-long error from flake8.

I think I found a solution. You put the `# noqa: E501` at the end of the docstring, on the same line as the final set of quotes. See my latest commit for arima. Found via this stackoverflow page: https://github.com/PyCQA/pydocstyle/issues/234#issuecomment-828884021

**Comment by Lovkush-A** [comment]
@aiwalter @RNKuhns. I have made changes as suggested by Ryan. While changing BATS and TBATS, I made some minor tweaks (e.g. reordering imports so they agree with each other).

Martin: for BATS, can the sp be non-integer? From the reading I did about it, BATS can only handle integer periods but TBATS can handle both integer and float.

**Review by mloning — COMMENTED** [review]
This seems to be almost ready to go, the only thing that needs changing is @aiwalter's comment above? Would love to get this in for the next release

**Review by mloning — APPROVED** [review]
The way the references are displayed seems to be the default behaviour so I'm happy with this going in

**Comment by mloning** [comment]
Now merged @Lovkush-A - thanks! 🎉

**Pull request merged**
