### PR TITLE
[MNT] Added pre-commit hook to sort imports

### PR DESCRIPTION
**Pull request by aiwalter**

### CODE REVIEW

**Comment by aiwalter** [comment]
maybe random error:

```2021-09-29T15:09:19.1158260Z utils/tests/test_data_processing.py .................................... [ 97%]
2021-09-29T15:09:21.5414040Z ....................................................................     [ 98%]
2021-09-29T15:09:27.0632110Z utils/tests/test_plotting.py ........................................... [ 99%]
2021-09-29T15:09:27.0632710Z                                                                          [ 99%]
2021-09-29T15:09:27.1026920Z utils/tests/test_utils_time_series.py .................                  [ 99%]
2021-09-29T15:09:27.1327300Z utils/validation/tests/test_check_window_length.py ................      [ 99%]
2021-09-29T15:09:27.1400780Z utils/validation/tests/test_forecasting.py ...                           [ 99%]
2021-09-29T15:09:27.1779530Z utils/validation/tests/test_panel.py ........                            [ 99%]
2021-09-29T15:09:34.1168770Z Coverage.py warning: Data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.51958.450213' doesn't seem to be a coverage data file: 'NoneType' object is not iterable
2021-09-29T15:09:34.1170700Z utils/validation/tests/test_write_dataframe_to_ts.py ...                 [100%]
2021-09-29T15:09:34.1172660Z Coverage.py warning: Data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.50993.345825' doesn't seem to be a coverage data file: 'NoneType' object is not iterable
2021-09-29T15:09:34.1174920Z Coverage.py warning: Couldn't use data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.51960.129794': database disk image is malformed
2021-09-29T15:09:34.1177760Z Coverage.py warning: Data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.53310.413797' doesn't seem to be a coverage data file: Couldn't use data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.53310.413797': no such table: coverage_schema
2021-09-29T15:09:34.1180480Z Coverage.py warning: Couldn't use data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.53293.887712': database disk image is malformed
2021-09-29T15:09:34.1183310Z Coverage.py warning: Data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.53294.231579' doesn't seem to be a coverage data file: Couldn't use data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.53294.231579': no such table: coverage_schema
2021-09-29T15:09:34.1186530Z Coverage.py warning: Data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.51961.228923' doesn't seem to be a coverage data file: 'NoneType' object is not iterable
2021-09-29T15:09:34.1188850Z Coverage.py warning: Couldn't use data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.53295.808415': database disk image is malformed
2021-09-29T15:09:34.1191670Z Coverage.py warning: Data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.51959.217970' doesn't seem to be a coverage data file: Couldn't use data file '/Users/runner/work/sktime/sktime/testdir/.coverage.Mac-1632925456549.local.51959.217970': no such table: coverage_schema
2021-09-29T15:09:34.1193170Z 
2021-09-29T15:09:34.1194030Z =================================== FAILURES ===================================
2021-09-29T15:09:34.1194880Z ________________ [doctest] sktime.forecasting.fbprophet.Prophet ________________
2021-09-29T15:09:34.1195740Z 089     >>> from sktime.datasets import load_airline
2021-09-29T15:09:34.1196490Z 090     >>> from sktime.forecasting.fbprophet import Prophet
2021-09-29T15:09:34.1197340Z 091     >>> # Prophet requires to have data with a pandas.DatetimeIndex
2021-09-29T15:09:34.1198450Z 092     >>> y = load_airline().to_timestamp(freq='M')
2021-09-29T15:09:34.1198970Z 093     >>> forecaster = Prophet(
2021-09-29T15:09:34.1199870Z 094     ...     seasonality_mode='multiplicative',
2021-09-29T15:09:34.1200710Z 095     ...     n_changepoints=int(len(y) / 12),
2021-09-29T15:09:34.1201700Z 096     ...     add_country_holidays={'country_name': 'Germany'},
2021-09-29T15:09:34.1202270Z 097     ...     yearly_seasonality=True)
2021-09-29T15:09:34.1202750Z 098     >>> forecaster.fit(y)
2021-09-29T15:09:34.1204230Z UNEXPECTED EXCEPTION: ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()',)
2021-09-29T15:09:34.1205070Z Traceback (most recent call last):
2021-09-29T15:09:34.1207940Z   File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/fbprophet/make_holidays.py", line 33, in get_holiday_names
2021-09-29T15:09:34.1209010Z     holiday_names = getattr(hdays_part2, country)(years=years).values()
2021-09-29T15:09:34.1210250Z AttributeError: module 'fbprophet.hdays' has no attribute 'Germany'
2021-09-29T15:09:34.1211090Z During handling of the above exception, another exception occurred:
2021-09-29T15:09:34.1211750Z Traceback (most recent call last):
2021-09-29T15:09:34.1212610Z   File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/doctest.py", line 1330, in __run
2021-09-29T15:09:34.1214040Z     compileflags, 1), test.globs)
2021-09-29T15:09:34.1215130Z   File "<doctest sktime.forecasting.fbprophet.Prophet[4]>", line 1, in <module>
2021-09-29T15:09:34.1216910Z   File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sktime/forecasting/base/_base.py", line 179, in fit
2021-09-29T15:09:34.1217790Z     self._fit(y=y_inner, X=X_inner, fh=fh)
2021-09-29T15:09:34.1219240Z   File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sktime/forecasting/base/adapters/_fbprophet.py", line 61, in _fit
2021-09-29T15:09:34.1220470Z     self._forecaster.add_country_holidays(**self.add_country_holidays)
2021-09-29T15:09:34.1222030Z   File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/fbprophet/forecaster.py", line 724, in add_country_holidays
2021-09-29T15:09:34.1222960Z     for name in get_holiday_names(country_name):
2021-09-29T15:09:34.1224350Z   File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/fbprophet/make_holidays.py", line 36, in get_holiday_names
2021-09-29T15:09:34.1225360Z     holiday_names = getattr(hdays_part1, country)(years=years).values()
2021-09-29T15:09:34.1226800Z   File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/holidays/countries/germany.py", line 81, in __init__
2021-09-29T15:09:34.1228360Z     HolidayBase.__init__(self, **kwargs)
2021-09-29T15:09:34.1229830Z   File "/Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/holidays/holiday_base.py", line 177, in __init__
2021-09-29T15:09:34.1230840Z     self.years = set(years) if years else set()
2021-09-29T15:09:34.1231580Z ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2021-09-29T15:09:34.1233240Z /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sktime/forecasting/fbprophet.py:98: UnexpectedException
2021-09-29T15:09:34.1234250Z =============================== warnings summary ===============================
2021-09-29T15:09:34.1235390Z forecasting/fbprophet.py::sktime.forecasting.fbprophet.Prophet
2021-09-29T15:09:34.1237470Z   /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/Cython/Build/Inline.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
2021-09-29T15:09:34.1238810Z     import imp
2021-09-29T15:09:34.1239060Z 
2021-09-29T15:09:34.1239560Z forecasting/tests/test_all_forecasters.py: 45 warnings
2021-09-29T15:09:34.1240300Z forecasting/tests/test_sktime_forecasters.py: 5 warnings
2021-09-29T15:09:34.1240950Z tests/test_all_estimators.py: 2 warnings
2021-09-29T15:09:34.1242760Z   /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/statsmodels/tsa/holtwinters/model.py:429: FutureWarning: After 0.13 initialization must be handled at model creation
2021-09-29T15:09:34.1243830Z     FutureWarning,
2021-09-29T15:09:34.1244110Z 
2021-09-29T15:09:34.1244600Z forecasting/tests/test_all_forecasters.py: 12 warnings
2021-09-29T15:09:34.1246610Z   /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/statsmodels/tsa/base/tsa_model.py:383: DeprecationWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
2021-09-29T15:09:34.1248370Z     ' exception.', DeprecationWarning)
2021-09-29T15:09:34.1248760Z 
2021-09-29T15:09:34.1249210Z forecasting/tests/test_naive.py: 16 warnings
2021-09-29T15:09:34.1250600Z   /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sktime/forecasting/naive.py:153: RuntimeWarning: Mean of empty slice
2021-09-29T15:09:34.1251540Z     y_pred = np.nanmean(last_window, axis=0)
2021-09-29T15:09:34.1251870Z 
2021-09-29T15:09:34.1252390Z series_as_features/tests/test_all_panel_estimators.py: 3 warnings
2021-09-29T15:09:34.1253040Z tests/test_all_estimators.py: 17 warnings
2021-09-29T15:09:34.1255080Z   /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sktime/base/_base.py:275: DeprecationWarning: __init__ has been deprecated. Please use `Catch22Classifier` from `sktime.classification.feature_based` instead.
2021-09-29T15:09:34.1256700Z     return cls(**params)
2021-09-29T15:09:34.1256970Z 
2021-09-29T15:09:34.1257490Z series_as_features/tests/test_all_panel_estimators.py: 3 warnings
2021-09-29T15:09:34.1258150Z tests/test_all_estimators.py: 15 warnings
2021-09-29T15:09:34.1260110Z   /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sktime/base/_base.py:275: DeprecationWarning: __init__ has been deprecated. Please use `SignatureClassifier` from `sktime.classification.feature_based` instead.
2021-09-29T15:09:34.1261470Z     return cls(**params)
2021-09-29T15:09:34.1261740Z 
2021-09-29T15:09:34.1262400Z tests/test_all_estimators.py::test_estimator[Catch22ForestClassifier]
2021-09-29T15:09:34.1263330Z tests/test_all_estimators.py::test_estimator[Catch22ForestClassifier]
2021-09-29T15:09:34.1264260Z tests/test_all_estimators.py::test_estimator[Catch22ForestClassifier]
2021-09-29T15:09:34.1266780Z   /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sklearn/base.py:77: DeprecationWarning: __init__ has been deprecated. Please use `Catch22Classifier` from `sktime.classification.feature_based` instead.
2021-09-29T15:09:34.1268790Z     new_object = klass(**new_object_params)
2021-09-29T15:09:34.1269180Z 
2021-09-29T15:09:34.1269790Z tests/test_all_estimators.py::test_estimator[SignatureClassifier0]
2021-09-29T15:09:34.1270830Z tests/test_all_estimators.py::test_estimator[SignatureClassifier0]
2021-09-29T15:09:34.1271700Z tests/test_all_estimators.py::test_estimator[SignatureClassifier0]
2021-09-29T15:09:34.1273950Z   /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/sklearn/base.py:77: DeprecationWarning: __init__ has been deprecated. Please use `SignatureClassifier` from `sktime.classification.feature_based` instead.
2021-09-29T15:09:34.1275380Z     new_object = klass(**new_object_params)
2021-09-29T15:09:34.1275700Z 
2021-09-29T15:09:34.1276350Z transformations/tests/test_all_transformers.py::test_all_transformers[HampelFilter]
2021-09-29T15:09:34.1278010Z   /Users/runner/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1114: RuntimeWarning: All-NaN slice encountered
2021-09-29T15:09:34.1278990Z     overwrite_input=overwrite_input)
2021-09-29T15:09:34.1279330Z 
2021-09-29T15:09:34.1280250Z -- Docs: https://docs.pytest.org/en/stable/warnings.html
2021-09-29T15:09:34.1280760Z 
2021-09-29T15:09:34.1281590Z ---------- coverage: platform darwin, python 3.6.15-final-0 ----------
2021-09-29T15:09:34.1282250Z Coverage XML written to file coverage.xml
2021-09-29T15:09:34.1282610Z 
2021-09-29T15:09:34.1282980Z ============================= slowest 10 durations =============================
2021-09-29T15:09:34.1283670Z 141.73s call     tests/test_all_estimators.py::test_estimator[ShapeletTransform]
2021-09-29T15:09:34.1284490Z 93.11s call     tests/test_all_estimators.py::test_estimator[HIVECOTEV1]
2021-09-29T15:09:34.1285750Z 89.35s call     classification/feature_based/_tsfresh_classifier.py::sktime.classification.feature_based._tsfresh_classifier.TSFreshClassifier
2021-09-29T15:09:34.1287080Z 77.48s call     classification/hybrid/tests/test_hivecote_v1.py::test_hivecote_v1_on_power_demand
2021-09-29T15:09:34.1288140Z 58.97s call     tests/test_all_estimators.py::test_estimator[TSFreshRelevantFeatureExtractor]
2021-09-29T15:09:34.1289190Z 46.51s call     tests/test_all_estimators.py::test_estimator[TimeSeriesKMedoids]
2021-09-29T15:09:34.1290400Z 45.08s call     classification/dictionary_based/_cboss.py::sktime.classification.dictionary_based._cboss.ContractableBOSS
2021-09-29T15:09:34.1291580Z 39.12s call     tests/test_all_estimators.py::test_estimator[TimeSeriesKMeans]
2021-09-29T15:09:34.1292870Z 32.72s call     classification/feature_based/_catch22_classifier.py::sktime.classification.feature_based._catch22_classifier.Catch22Classifier
2021-09-29T15:09:34.1294280Z 32.16s call     tests/test_all_estimators.py::test_estimator[DrCIF]
2021-09-29T15:09:34.1294890Z =========================== short test summary info ============================
2021-09-29T15:09:34.1295740Z FAILED forecasting/fbprophet.py::sktime.forecasting.fbprophet.Prophet
2021-09-29T15:09:34.1296650Z ===== 1 failed, 6040 passed, 2 skipped, 126 warnings in 2107.06s (0:35:07) =====
2021-09-29T15:09:36.4870820Z Coverage.py warning: --include is ignored because --source is set (include-ignored)
2021-09-29T15:09:36.5236930Z ##[error]Process completed with exit code 1.
2021-09-29T15:09:36.5380960Z Post job cleanup.
2021-09-29T15:09:36.6795610Z [command]/usr/local/bin/git version
2021-09-29T15:09:36.6865840Z git version 2.33.0
2021-09-29T15:09:36.6913390Z [command]/usr/local/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-09-29T15:09:36.6993190Z [command]/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-09-29T15:09:36.7853020Z [command]/usr/local/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-09-29T15:09:36.7926220Z http.https://github.com/.extraheader
2021-09-29T15:09:36.7945450Z [command]/usr/local/bin/git config --local --unset-all http.https://github.com/.extraheader
2021-09-29T15:09:36.8026050Z [command]/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-09-29T15:09:36.8968950Z Cleaning up orphan processes
```

**Review by TonyBagnall — DISMISSED** [review]

**Comment by fkiraly** [comment]
are we sure we want this, @aiwalter?

Somtimes, where we have a lot of imports, they are ordered semantically, e.g., objects of similar kind (e.g., base classes), with comments around the imports.

This would always enforce alphabetical ordering, which would conflict with the semantic ordering that makes the import statements more easy to read in places.

**Comment by aiwalter** [comment]
I have often seen completely unsorted imports, so any sorting is better than no sorting in my opinion :)

**Review by mloning — COMMENTED** [review]
Hi @aiwalter, oh I thought we've already had this, I must have forgotten to include it, but could we use `isort` instead? Seems to be the common choice and we're already using it for the notebooks, see https://pycqa.github.io/isort/docs/configuration/pre-commit.html 

I'm in favour of this, generally makes the imports more readable.

**Review by mloning — DISMISSED** [review]

**Comment by RNKuhns** [comment]
@aiwalter and everyone, I'm generally for this. I think it makes things more readable and it automatically groups built-in Python modules, 3rd party modules and local (sktime in our case) modules. 

But I think we also need to update our `setup.cfg` file to add `isort` there and make sure that when `isort`  wraps imports onto multiple lines, it does so in the way that `black` reformats things. Otherwise you end up in a perpetual loop, where `isort` changes what black does and `black` changes what `isort` does!

**Comment by RNKuhns** [comment]
@aiwalter here's the link to `isort's` info on [black compatability](https://pycqa.github.io/isort/docs/configuration/black_compatibility.html).

I've put that into setup.cfg in the past rather than having a seperate isort specific config file.

**Comment by aiwalter** [comment]
thx @mloning  and @RNKuhns  for input, I updated my PR and tested this with `ets.py`. So sorting works well and no infinite hook loop :)

**Review by RNKuhns — APPROVED** [review]
@aiwalter these changes look good to me. Thanks for changing the hook order!

**Review by fkiraly — APPROVED** [review]
Yes, the argument makes sense to me - better some sorting than no sorting, most files are very unordered.

**Comment by aiwalter** [comment]
Its only an issue for existing PRs, when they push new files it runs only on them but on the pipeline it runs on all modified files. 

Solution: adding locally an empty line in every modified file to locally trigger the sorting already. On any new PR there is no issue.

**Pull request merged**
