### PR TITLE
Replace Appveyor CI for Windows builds with GitHub actions

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
Partly fixes https://github.com/alan-turing-institute/sktime/issues/1032

#### What does this implement/fix? Explain your changes.
* Adds GitHub Action CI scripts for Windows building and testing
* Removes appveyor CI

### CODE REVIEW

**Comment by TonyBagnall** [comment]
does changing from appveyor require a check from appveyor? Will it allow it do you think? :)

**Comment by mloning** [comment]
From my side, this is ready to be reviewed. 

The `appveyor` checks are expected to fail, since I removed them here. The `build (macos-latest)` also won't run because I changed and renamed the workflows to now include both macOS and Windows. 

Given that I'm away for the next couple of days, it may be wise to wait before we merge this until I'm back? I think I'd also prefer to publish another release relying on the old tried and tested workflow before merging the new one in this PR.

**Comment by fkiraly** [comment]
@mloning, you are now back from holiday - it would be good to finish this, and there are some conflicts?

**Review by fkiraly — CHANGES_REQUESTED** [review]
Sth is breaking in the windows CI checks, what is that?

**Comment by mloning** [comment]
Not sure why it's now failing, the Windows runs worked before. 

Note to self: still need to update `upload-to-pypi` script once CI runs work again.

**Comment by mloning** [comment]
More issues, I'm working on it.

**Comment by fkiraly** [comment]
@mloning, appveyor is breaking, let's move away from it.
Are you still working on this?

**Comment by mloning** [comment]
Superseded by #1620

**Pull request closed without merging**
