### PR TITLE
Auto-generate a classifier Capabilities summary #997

### PR DESCRIPTION
**Pull request by BINAYKUMAR943**
#### What does this implement/fix? Explain your changes.
This PR automatically generates a summary of the capabilities of the different classifiers. Some classifiers such as ProximityStump, ProximityTree etc. doesn't have any capabilities defined in their class. The code is currently putting N/A for them, but it will be included in the table once it gets added.

#### Does your contribution introduce a new dependency? If yes, which one?

No
#### What should a reviewer concentrate their feedback on?

Please review the part which is automatically generating the capabilities of the classifier. If it seems fine then we can generate a list like this for all the estimators. Code is just putting N/A in the table to the capabilities for the classifiers that do not have any capabilities defined. 

#### Any other comments?
Please review and approve it. @TonyBagnall @ABostrom

##### For all contributions
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi, there are I'm afraid strict formatting rules for submissions which you code failed the test for. Read here https://github.com/alan-turing-institute/sktime/blob/main/CONTRIBUTING.md

**Comment by TonyBagnall** [comment]
click on "details" next to the code quality and it will tell you why it failed. If you are on a command line you can use the pre-commit tool to check if it passes beforehand

**Comment by TonyBagnall** [comment]
if you are on a command line you can check beforehand with pre-commit, although I cannot get this working with github desktop
image

**Comment by BINAYKUMAR943** [comment]
> if you are on a command line you can check beforehand with pre-commit, although I cannot get this working with github desktop
> image

I have made some changes to the code and followed the suggested steps.

**Comment by BINAYKUMAR943** [comment]
> click on "details" next to the code quality and it will tell you why it failed. If you are on a command line you can use the pre-commit tool to check if it passes beforehand
Thank you a ton for the suggestion. I have made some changes and checked using the pre-commit tool in my locals. It is passing now.

**Review by TonyBagnall — APPROVED** [review]

**Review by TonyBagnall — APPROVED** [review]
I'll put this in as its in contrib, we can refactor it for tags later

**Comment by BINAYKUMAR943** [comment]
> I'll put this in as its in contrib, we can refactor it for tags later

Sure, Thanks!

**Pull request merged**
