### PR TITLE
Fix bootstrap in TimeSeriesForestClassifier

### LINKED ISSUE #160: Error when running TimeSeriesForestClassifier() function
**Describe the bug**
Encounter an error when running the code in the example. Specifically, TimeSeriesForestClassifier() function.
PicklingError: Can't pickle <function Pipeline.predict_proba at 0x7fab65da6158>: it's not the same object as sklearn.pipeline.Pipeline.predict_proba

**To Reproduce**
tsf = TimeSeriesForestClassifier(base_estimator=base_estimator, 
                                 n_estimators=100,
                                 criterion='entropy',
                                 bootstrap=True, 
                                 oob_score=True, 
                                 random_state=1)
tsf.fit(X_train, y_train)
tsf.score(X_test, y_test)

**Expected behavior**
Get a score.

**Additional context**

**Versions**
Linux-3.10.0-693.17.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
Python 3.6.3 |Intel Corporation| (default, Feb 12 2018, 06:37:09) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
NumPy 1.17.2
SciPy 1.3.1
sktime 0.3.0

### PR DESCRIPTION
**Pull request by simone-pignotti**
Fixes #160
Update of the `TimeSeriesForestClassifier` class in `sktime/classifiers/compose/ensemble.py` to match the current bootstrap parameters of `sklearn`. The `max_samples` parameter (the number of samples to draw from X to train each base estimator) was missing in `sktime`.
Tested with the [example](https://alan-turing-institute.github.io/sktime/examples/univariate_time_series_classification.html#Fully-modular-time-series-forest-classifier-(TSF)) from the docs.

### CODE REVIEW

**Comment by simone-pignotti** [comment]
Requires `scikit-learn>=0.22`

**Comment by simone-pignotti** [comment]
Version 0.22.0 of `scikit-learn` not available in the `anaconda` channel yet (it is on `conda-forge`).

**Comment by mloning** [comment]
Great! Thanks for the PR! 

What you could try to fix the CI is to update the [install file](https://github.com/alan-turing-institute/sktime/blob/master/build_tools/travis/install.sh) by replacing this line
```bash
conda create -n testenv --yes $TO_INSTALL
```
with this line
```bash
conda create -n testenv -c conda-forge --yes $TO_INSTALL
```
Perhaps that does the trick. Otherwise I can look into this some time later! 

Really appreciate your PR!

**Comment by mloning** [comment]
We would also have to update appveyor.

**Comment by simone-pignotti** [comment]
No problem! appveyor was already fixed, travis works too now. Let me know if there's something else I can do.

**Comment by mloning** [comment]
Great work! Thanks again! Please get in touch if you're interested in contributing more generally!

**Comment by simone-pignotti** [comment]
Thanks to you and the other contributors for this great library! Unfortunately I don't think I will have time (nor a broad enough knowledge of time-series ML) to contribute on a regular basis, but will definitely try to keep fixing stuff here and there.

**Pull request merged**
