### PR TITLE
[ENH] Faster classifier example parameters

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Alters classifier example parameters so they don't take as much time (#2377).

### CODE REVIEW

**Comment by fkiraly** [comment]
@MatthewMiddlehurst, these choices are failing?

**Comment by MatthewMiddlehurst** [comment]
Remaining tests are stalled/failing only due to the overload of testing going on currently.

For some of these, we are reaching the limit of how much time usage we can reduce by tweaking parameters. I have a hunch a bunch of time is being added from having to compile the numba functions some use, i.e. catch22 related classifiers and I think distances now.

**Comment by fkiraly** [comment]
Thanks! So now it´s mainly Prophet...

**Review by fkiraly — APPROVED** [review]
Looks good, thanks!

Btw, in `ClassifierPipeline`, would it be nicer to write
`pipeline = PCATransformer() * TimeSeriesForestClassifier(n_estimators=5)`
?

**Comment by MatthewMiddlehurst** [comment]
I personally prefer how it is currently, but won't object to you changing it before merging if you think it would look better.

**Comment by fkiraly** [comment]
added it as alternative example

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
