### PR TITLE
[MNT] loosen strict upper bound on `scipy` to 1.9.0

### PR DESCRIPTION
**Pull request by fkiraly**
This PR loosens the strict upper bound on the `scipy` dependency to `scipy<1.9.0`.

This requires https://github.com/alan-turing-institute/sktime/pull/2468 which should be the last issue preventing the bump.

### CODE REVIEW

**Comment by lmmentel** [comment]
It seems it has some of the same changes as #2468 ?

**Comment by lmmentel** [comment]
Whenever we tinker with deps we also need to bump make the corresponding changes in the conda recipe https://github.com/conda-forge/sktime-feedstock. Would be great to have some automation around this :grin:

**Comment by fkiraly** [comment]
> It seems it has some of the same changes as https://github.com/alan-turing-institute/sktime/pull/2468 ?

As I said, it relies on the other PR which fixes the bugs/problems that prevented us from loosening the bounds in the first place. Otherwise this would simply break `main`.

**Comment by fkiraly** [comment]
seems to work, @lmmentel

**Comment by fkiraly** [comment]
> Would be great to have some automation around this

Should we open an issue?

**Comment by fkiraly** [comment]
@lmmentel, are you happy or do you have any requests?

**Review by lmmentel — APPROVED** [review]

**Review by aiwalter — APPROVED** [review]

**Pull request merged**
