### PR TITLE
[MNT] cleaning up CI workflow

### PR DESCRIPTION
**Pull request by lmmentel**
This PR simplifies the CI by consolidating the test workflow since there are no longer any platform dependent differences between mac and linux, i.e. merging mac/linux via a matrix.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Looks great!

Quick question before we merge: have you checked whether we can also subsume windows under this, now that `pip install` also works on windows?

@RNKuhns has managed to do it, here!
https://github.com/sktime/BaseObject/blob/main/.github/workflows/test.yml

**Comment by lmmentel** [comment]
> Quick question before we merge: have you checked whether we can also subsume windows under this, now that `pip install` also works on windows?
> 
> @RNKuhns has managed to do it, here! https://github.com/sktime/BaseObject/blob/main/.github/workflows/test.yml

That would  increase the scope, but we can improve it further in a following PR.

**Review by fkiraly — APPROVED** [review]
>That would increase the scope, but we can improve it further in a following PR.

Makes sense.

**Comment by fkiraly** [comment]
stupid questions:

* can you merge this, since the test names have changed?
* I supposed once we merge, we need to change the list of required tests in the admin interface for the same reason?

**Comment by lmmentel** [comment]
> 
>     * can you merge this, since the test names have changed?
> 
Nope, I cannot merge the button is not active,

>     * I supposed once we merge, we need to change the list of required tests in the admin interface for the same reason?

Probably, but I cannot be sure since I don't have access.

**Comment by fkiraly** [comment]
>Probably, but I cannot be sure since I don't have access.

You'd need admin rights which only CC members have, I'll take care of that.

**Pull request merged**
