### PR TITLE
[MNT] Fail CI on missing init files

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
#1695 

#### What does this implement/fix? Explain your changes.
Adds check to fail unit testing if init files are missing in modules

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Looks good, although the error message would be more helpful if you tell the developer *which* init file is missing *where*.

**Comment by mloning** [comment]
Yes just added this now, let's see if this actually fails before we merge #1695

**Comment by mloning** [comment]
Ok, 4ad9060 now fails with the expected error message:

Screenshot 2021-12-05 at 11 25 00

So after merging #1695 and syncing with main, this should be good to go.

**Comment by fkiraly** [comment]
#1695 is now merged, the init files are in.
After update from main, this should no longer fail.

**Review by fkiraly — APPROVED** [review]
It indeed does no longer fail, so ready for merge.

**Pull request merged**
