### PR TITLE
[BUG] remove non-standard `score` function in `BaseGridSearch`

### PR DESCRIPTION
**Pull request by fkiraly**
This PR removes the non-standard `score` function in `BaseGridSearch` which overrides the default `score` from `BaseForecaster`, and seems to cause interface non-compliance with respect to the specification of `score`, as described in https://github.com/alan-turing-institute/sktime/issues/2751.

Before we merge, we should understand why this was there in the first place, as discussed in #2751.

### CODE REVIEW

**Review by aiwalter — DISMISSED** [review]

**Comment by aiwalter** [comment]
@fkiraly no I think this was "legacy" code

**Comment by aiwalter** [comment]
wait I think now it can only score with default `mean_absolute_percentage_error`?

**Comment by fkiraly** [comment]
I think that's what `score` is always supposed to do? For `sklearn` compatibility, it has to default to one particular metric always afaik, in the case of forecasters the MAPE

**Comment by aiwalter** [comment]
ah right, there is 2 score functionalities

**Comment by aiwalter** [comment]
I dont have a strong opinion on this PR then

**Comment by fkiraly** [comment]
seems to introduce interface non-conformance, since `score` is always assumed to be MAPE elsewhere, so would be in favour because of making the interface conformant.

**Review by aiwalter — DISMISSED** [review]
ok then I approve it :)

**Pull request merged**
