### PR TITLE
Fix counting for Github's automatic language discovery

### LINKED ISSUE #809: [BUG] problematic language statistics shown in the homepage
Hi, I have noticed that `.ts` files in the folder `datasets` are tracked by Github Linguist, which is not the case in the past.

As a result, the language statistics shown in the homepage are somehow mis-leading. Maybe we should add `jquery.js -linguist-vendored` as a new line in `.gitattributes`, according to this [markdown file](https://github.com/github/linguist/blob/master/docs/overrides.md#vendored-code).

### PR DESCRIPTION
**Pull request by xuyxu**
#### Reference Issues/PRs

resolves #809

#### What does this implement/fix? Explain your changes.

* Update config in `.gitattributes` for Github Linguist to conduct language discovery more appropriately

### CODE REVIEW

**Comment by xuyxu** [comment]
cc @mloning

**Comment by mloning** [comment]
Thanks @xuyxu

**Comment by mloning** [comment]
Looking again at the documentation: do we need to add this last line too?

```
docs/* linguist-documentation
docs/formatter.rb -linguist-documentation
```

**Comment by mloning** [comment]
Actually seems like docs is excluded automatically - so perhaps just adding your originally suggested fix should do the work.

**Comment by xuyxu** [comment]
> Actually seems like docs is excluded automatically - so perhaps just adding your originally suggested fix should do the work.

You are right, `.rst` files are not tracked now. So shall we remove the first line?

**Comment by mloning** [comment]
Yes let's just add the `jquery.js -linguist-vendored` - the entire `docs` folder is excluded actually.

**Comment by xuyxu** [comment]
Done. I am not sure if this problem arises from the missing line on `jquery.js`. Lingust has released the version 7.14 two days ago, and it looks like many repos also suffer from this problem after that release.

**Review by mloning — APPROVED** [review]

**Comment by mloning** [comment]
@xuyxu I merged it now, let's see if this fixes the issue

**Comment by xuyxu** [comment]
Well, it looks like the problem still exists :-(

I will open an issue in Github linguist to see if they could help us ;-)

**Pull request merged**
