### PR TITLE
Update documentation backend and reduce warnings in doc creation (#1199)

### LINKED ISSUE #1181: [BUG] Mismatch between stub files and autosummary toctrees
**Describe the bug**
While investigating why https://github.com/alan-turing-institute/sktime/pull/1158 doesn't produce a proper gallery without executing the notebooks first (which, as per https://github.com/spatialaudio/nbsphinx/issues/586, should be possible), it was mentioned that reducing the number of warnings would simplify finding the root cause for the problem. Therefore, I executed `sphinx-build` with `-W` ("turn warnings into errors") and started with the first one:

```
$ python -m sphinx -v -W -T -E -b html -d _build/doctrees -D language=en source/ _build/html
...
    self.builder.build_update()                                                                                                                                                                                    (27/27 results) [2068/9792]
  File "/home/juanlu/Projects/RTD/tmp/sktime/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))                                                                                                     
  File "/home/juanlu/Projects/RTD/tmp/sktime/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())                                                                                
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__                                                                                                                                                                              
    self.gen.throw(type, value, traceback)                                                                                                                                                                                                    
  File "/home/juanlu/Projects/RTD/tmp/sktime/.venv/lib/python3.7/site-packages/sphinx/util/logging.py", line 213, in pending_warnings
    memhandler.flushTo(logger)                                                                                                                                                                                                                
  File "/home/juanlu/Projects/RTD/tmp/sktime/.venv/lib/python3.7/site-packages/sphinx/util/logging.py", line 178, in flushTo                                                                                                           
    logger.handle(record)                                                                                                                                                                                                                     
  File "/usr/lib/python3.7/logging/__init__.py", line 1524, in handle                                                                                                                                                                         
    self.callHandlers(record)                                                                                                                                                                                                                 
  File "/usr/lib/python3.7/logging/__init__.py", line 1586, in callHandlers                                                                                                                                                                   
    hdlr.handle(record)                                                                                                                                                                                                                       
  File "/usr/lib/python3.7/logging/__init__.py", line 890, in handle                                                                                                                                                                          
    rv = self.filter(record)                                                                                                                                                                                                                  
  File "/usr/lib/python3.7/logging/__init__.py", line 751, in filter                                                                                                                                                                          
    result = f.filter(record)                                                                                          
  File "/home/juanlu/Projects/RTD/tmp/sktime/.venv/lib/python3.7/site-packages/sphinx/util/logging.py", line 421, in filter
    raise exc                                              
sphinx.errors.SphinxWarning: /home/juanlu/Projects/RTD/tmp/sktime/docs/source/source/api_reference/classification.rst.rst:16:autosummary: stub file not found 'sktime.classification.compose.ColumnEnsembleClassifier'. Check your autosummary
_generate setting. 
```

After some investigation, I realized that `sktime.classification.compose.ColumnEnsembleClassifier` stub is located in `api_reference/modules/auto_generated/`, however `api_reference/classification.rst` points to `modules/auto_generated/`:

https://github.com/alan-turing-institute/sktime/blob/d149b2379aa213f24cc260d1b6a35bea15d829db/docs/source/api_reference/classification.rst#L17

It turns out that stub files are being generated in two directories: `api_reference/modules/auto_generated/` and `modules/auto_generated`, which might be the source of confusion. For this particular warning to go away, I made this one-line change:

```diff
diff --git a/docs/source/api_reference/classification.rst b/docs/source/api_reference/classification.rst
index dfa882cb..b4e552d6 100644
--- a/docs/source/api_reference/classification.rst
+++ b/docs/source/api_reference/classification.rst
@@ -14,7 +14,7 @@ Composition
 .. currentmodule:: sktime.classification.compose
 
 .. autosummary::
-    :toctree: modules/auto_generated/
+    :toctree: api_reference/modules/auto_generated/
     :template: class.rst
 
     ColumnEnsembleClassifier
```

However, there are a lot of these, so someone would have to go and amend those manually. In addition, it would be useful to clarify why these two directories hold stub files, and if this is the normal thing to do. I am not an expert in `sphinx.ext.autosummary` so I can't give much more guidance yet.

I think this is a good first step towards reducing the number of warnings in the documentation, although there is still a long road ahead.

### LINKED ISSUE #1230: [DOC] autosummary warning: stub file not found
#### Describe the issue linked to the documentation
We see many warnings from auto summary as below:
> /home/docs/checkouts/readthedocs.org/user_builds/sktime/checkouts/1205/docs/source/api_reference/classification.rst.rst:16: WARNING: autosummary: stub file not found 'sktime.classification.compose.ColumnEnsembleClassifier'. Check your autosummary_generate setting.

#### Suggest a potential alternative/fix
I'm not sure where they come from. The solution described [here](https://groups.google.com/g/sphinx-users/c/-il-CYbGwGA/m/_MoO3jxPAQAJ) does not seem to work.

### PR DESCRIPTION
**Pull request by mloning**
#### Reference issues/PR
Fixes #1181 
Fixes #1230 
Partly addresses #1152 

#### What does this implement/fix? Explain your changes.
* replaces `readthedocs-theme` with `pydata-sphinx-theme`
* restructures content in line with new theme
* adds new getting started page
* fixes autodoc display of summaries of classes and functions
* fixes sphinx build and warnings
* fixes docstrings and numpydoc warnings
* adds tutorial notebook thumbnail gallery
* adds links to Twitter, Discord and GitHub
* fixes wrong auto-generation directory in sphinx build
* updates version of sphinx and related packages
* integrates `myst-parser` replacing `m2r2`
* update `.gitignore` to exclude auto-generated documentation files
* adds glossary
*  removes full module path from page titles in API reference
* removes module names from table of content in API reference using more readable names (e.g. instead of "sktime.forecasting" we now simply use "Forecasting")
* adds page for adding estimators using extension templates
* adds page for enhancement proposals

#### Does your contribution introduce a new dependency? If yes, which one?
For generating docs only: 
* `pydata-sphinx-theme` (replaces `readthedocs` theme)
* `myst-parser` (replaces `m2r2`)
* `sphinx-gallery` 

#### What should a reviewer concentrate their feedback on?
Rendered website from ReadTheDocs CI/CD (click details below in CI/CD checks)

### CODE REVIEW

**Comment by satya-pattnaik** [comment]
Example for PyOD Annotator

```
from sktime.annotation.adapters import PyODAnnotator
from pyod.models.iforest import IForest
from sktime.datasets import load_airline
y = load_airline()
pyod_model = IForest()
pyod_sktime_annotator = PyODAnnotator(pyod_model)
pyod_sktime_annotator.fit(y)
annotated_series = pyod_sktime_annotator.predict(y)
```

Should we also have data set for outlier detection added, as it doesn't make much sense to use it on ```normal``` time series. The taxi data from this [benchmark repo](https://github.com/numenta/NAB) will be good

**Comment by RNKuhns** [comment]
> Should we also have data set for outlier detection added, as it doesn't make much sense to use it on normal time series. The taxi data from this benchmark repo will be good

@satya-pattnaik I agree that probably makes sense. Either including one of the specific datasets or a function to request any of them. That's probably beyond the scope of the documentation PR. Once completed, we'd update the Quickstart code example to use a more realistic dataset.

**Review by mloning — COMMENTED** [review]
Self-reviewed, looks good enough to go in now.

This is ready to be merged from my side. The doc-quality tests fail because of some of the docstrings but I think we can ignore that for now. 

The changes are needed for the doc-sprint next week.

**Review by MatthewMiddlehurst — APPROVED** [review]
Website looks a lot better. Like how detailed the auto generated API pages are now.

I only looked at the changes for the files I usually work with as there is quite a lot going on, but most seem to be docs changes to make it compatible with the new website format.

Fine with this going in if its required for the doc sprint, any kinks can be worked out during that. See also #1294.

**Comment by RNKuhns** [comment]
@mloning I concur that things look good besides any minor things we can take care of during the docsprint. As soon as 1294 finishes its checks, should be able to merge it into docs-dev and fix the doc-quality error.

**Review by fkiraly — CHANGES_REQUESTED** [review]
This changes 158 files, many of them not documentation related but core python files like base classes etc. I don't think anyone can seriously review this without a STEP or equivalent detailed description in this PR and am against merging this until this is remedied.

More precisely. I don't think we should merge this until there is some guide to what is being changed in which files. I think people should also be given sufficient time to look through this rather than rushing it through on a week-end.

@mloning, if someone else makes a PR like this, you would pull the plug and stop it for two weeks, and possibly try to murder them.

Now I'm aware we have the docsprint next week, so I'm willing to compromise: would you kindly be able to list which files are changed for which reason, optimally no later than Sunday morning?

**Comment by mloning** [comment]
Hi @fkiraly, for context, sorry if that wasn't clear, @RNKuhns and I worked on this together, we've reviewed our changes multiple times throughout the process. 

The changes in the Python files are all docstring changes. There shouldn't be any code changes, except for a few cases of Black reformatting. We tried to debug the sphinx build which was inundated by error messages, that's where most changes come from.

Can we go ahead and merge this?

**Comment by fkiraly** [comment]
ok, if the changes to the py files are all docstring fixes, fine with me - I trust you that you know what you are doing.

**Review by fkiraly — APPROVED** [review]
see above - py file changes are all docstring fixes

**Review by MatthewMiddlehurst — APPROVED** [review]

**Comment by fkiraly** [comment]
let's just get this over with? we ought to merge now-ish, then we still have 0.5-1 day to check whetehr everything works as intended and potentially revert.

**Comment by astrojuanlu** [comment]
Great job 👏

**Comment by aiwalter** [comment]
Really appreciate this PR, especially new website! thx @RNKuhns and @mloning

**Pull request merged**
