### PR TITLE
Evaluate (example and fix)

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs

#657 #622 

#### What does this implement/fix? Explain your changes.

Added example in notebook. Fix minor `tqdm` issue.

### CODE REVIEW

**Comment by mloning** [comment]
Thanks @aiwalter - the `n_split` fix is related to https://github.com/alan-turing-institute/sktime/issues/632 - probably best to fix this in the CV class.

**Comment by aiwalter** [comment]
from my side, this can be merged

**Comment by mloning** [comment]
How do we handle the `tqdm` dependency now?

**Comment by aiwalter** [comment]
I have removed it, no?

**Comment by aiwalter** [comment]
Sry seems I didnt push 🙄

**Comment by aiwalter** [comment]
should be fine now :) sry for confusion

**Review by mloning — APPROVED** [review]
Looks all good now! Thanks @aiwalter, will merge tomorrow

**Pull request merged**
