### PR TITLE
[ENH] Extract cached `ForecastingHorizon` methods to functions and avoid B019 error

### LINKED ISSUE #2338: [ENH] @lru_cache in ForecastingHorizon is an error for `flake8-bugbear`
**Is your feature request related to a problem? Please describe.**

Starting from version 22.3.20 of `flake8-bugbear` (https://github.com/PyCQA/flake8-bugbear/releases/tag/22.3.20) `@lru_cache` decorator in `sktime.forecasting.base._fh.ForecastingHorizon.to_relative` and `sktime.forecasting.base._fh.ForecastingHorizon.to_absolute` raises a pre-commit error. Adding `# noqa: B019` silences the warning, but I do not think this is a very sustainable solution.

**Describe the solution you'd like**

Is `@lru_cache` strictly necessary? Is the speed gain so dramatic that it overweights the dangers suggested by flake8? I do not have much experience with caching, so I have no good solution to propose.

### PR DESCRIPTION
**Pull request by khrapovs**
#### Reference Issues/PRs

closes #2338 

#### What does this implement/fix? Explain your changes.

Extract `ForecastingHorizon.to_relative` and `ForecastingHorizon.to_absolute` to `_to_relative` and `_to_absolute`, respectively, to allow caching without B019 error.

#### Does your contribution introduce a new dependency? If yes, which one?

No

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [X] I've added unit tests and made sure they pass locally.
- [X] The PR title starts with either [ENH], [DOC] or [BUG] indicating wether the PR topic is related to enhancement, documentation or bug

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Looks good, thanks!

Non-blocking comments:
* might be worth to add to the comments preceding the new, losse functions, a refrence to the B019, or someone might get the idea to put them back
* you remember the `pandas` bug? I think we should maybe change the comments there from "replace when fixed" to "replace when we upgrade our lower pandas bound to a version where this is fixed"? Or we´ll have the bug back on the lower end of our supported versions...

**Comment by khrapovs** [comment]
@fkiraly Addressed both of your suggestions.

**Comment by fkiraly** [comment]
> @fkiraly Addressed both of your suggestions.

Thanks!

May I ask for reformulation of this:

> This function is a direct replacement of the `ForecastingHorizon.to_relative` method to avoid B019 error from flake8-bugbear.

The problem with this is that it's obsccure.
You need to imagine someone who has not been part of our conversation.
Hence they will not get the reference "replacement" which is referring to the earlier state, since they will see only the current state (in the future).

Would suggest to change to 

"This function needs to be outside `ForecastingHorizon` since the `lru_cache` decorator has known, problematic interactions with object methods, see B019 error of `flake8-bugbear`"

**Comment by khrapovs** [comment]
@fkiraly I change the wording as you proposed

**Pull request merged**
