### PR TITLE
[ENH] flexible `update` behaviour of forecasting tuners

### LINKED ISSUE #3051: [ENH] flexible `update` behaviour of forecasting tuners
Suggestion inferred from #3046.

There should be an `update_best_params: bool` parameter in the forecasting tuners, and a custom `_update` function.

The parameter `update_best_params` should determine whether the grid search is repeated in `update`, or whether only parameters of the wrapped estimator are updated.

The location to add this would be `BaseGridSearch._update`.

Update: what could even be nicer is an `update_param_grid` which allows to specify a tuning grid separate from the one used in fit. Only the parameters specified in there are re-tuned, on update.

### PR DESCRIPTION
**Pull request by fkiraly**
Fixes #3051, also see #3046.

Adds an `update_behaviour` parameter to grid tuners which allows the user to select which of tuning parameters and inner parameters are updated in `update` of the grid search wrapper. Also:

* cleans up docstrings which were missing parameters
* adds the new parameter to the tests

### CODE REVIEW

**Comment by fkiraly** [comment]
Tests are passing, issue is with codecov #3057

**Comment by fkiraly** [comment]
Hmm, come to think of it: would it be even better, if the user could specify an `update_param_grid` different from the `param_grid` used in `fit`?

**Comment by fkiraly** [comment]
well, the above is just the special case where `update_param_grid` is completely empty...

**Comment by h-t-w** [comment]
> well, the above is just the special case where `update_param_grid` is completely empty...

So your saying, implementation wise it almost makes no difference, one would just need to make the `update_param_grid` public available as parameter in the `update` method? In this case: why not.

**Comment by fkiraly** [comment]
>implementation wise it almost makes no difference

It would, implementing the more general version takes more time - I have, in fact, implemented only the simpler one in #3057.

**Pull request merged**
