### PR TITLE
Support Latest numba

### PR DESCRIPTION
**Pull request by freddyaboulton**
##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
hmmm, that wasn't it, was it?
Looks like a nice puzzle to me...
No idea how to solve it.

Perhaps you want to make your PR a draft until it's ready?

**Comment by freddyaboulton** [comment]
@fkiraly Apologies! I thought I opened this on my own fork 🙈

**Comment by fkiraly** [comment]
no worries - feel free to have it here, that's perfectly fine and easier for in-progress feedback, but just mark it as a draft (you can do this when you open, or on the top right in the navigation bar). Otherwise, the "signalling" on the "please review" is misleading.

**Comment by fkiraly** [comment]
( just reopened and converted to draft)

**Comment by mloning** [comment]
The failing manylinux2010 build should be handled by #1379, not sure how to fix the failing windows build.

**Pull request closed without merging**
