### PR TITLE
Dataset generators

### PR DESCRIPTION
**Pull request by karthikn72**
#### Reference Issues/PRs

Adds shapelet data simulators as discussed with @TonyBagnall in issue #353. Also uses PR #384 as a starting point. 

#### What does this implement/fix? Explain your changes.

This introduces a Shapelet generator using TSML's implementation.

#### What should a reviewer concentrate their feedback on?

I have tested the generator using some values, but as I am not exactly sure of the kind of values I am supposed to be getting, I would appreciate some feedback on whether the code does what it should. As far as I am aware, since I used the TSML model, both these implementations should hopefully work the same way.

#### Any other comments?

To avoid repitition, I continued on the work done on PR #384. This is my first public contribution, so I would appreciate some feedback on the code quality. Furthermore, it would be helpful for me to get the theory behind the TSML simulators, so that I can figure out how to modularise what I currently have to help with the other classification generators.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

### CODE REVIEW

**Review by mloning — COMMENTED** [review]
Hi @karthikn72 - thanks for the PR. 

We need to think about a common interface for the generators. Making sure that all generators have a `sample(...)` method seems like a good idea:
```python
generator = MyGenerator(...)
data = generator.sample()
```

We should also make sure that users can control the number of instances, variables and time points (length of the series) that are generated (e.g. having `n_instances`, `n_variables` and `n_timepoints` input arguments). 

For supervised learning problems, there is also the question how to generate the target/label based on the feature data. 

Any other ideas @TonyBagnall @fkiraly?

**Comment by fkiraly** [comment]
Yes, @mloning, agreed with a common interface!
Might be worthwhile to open a STEP after we have this PR sorted, @karthikn72!

I think the following should be different classes:
* different sampling distributions
* different sampling algorithms

The following should be different templates:
* different tasks or types of data set

The following should be hyper-parameters:
* parameters of the sampling distribution
* parameters of the sampling algorithm
* random seed (important)

The following should be parameters of *sample*:
* number of samples and other "size/dimension" properties of the dataset, e.g., `n_variables`, `n_instances`, and so on
* any parameters related to distributed/parallelized runs or contracting

**Comment by karthikn72** [comment]
Hey, thanks for the feedback! A STEP for this sounds like something interesting I can take on as a GSoC project this year, if that is fine. If so, maybe I could alter the current shapelet generator, and start working on the STEP proposal. Does that sound fine? :)

**Comment by mloning** [comment]
@karthikn72 yes sounds like a good idea!

**Comment by sjmiller8182** [comment]
I don't think I have any addition input beyond what @fkiraly and @mloning have mentioned about consistency between the generators. I do think the generators should inherit from an abstract class to guide the interface design. Granted the base class `Generator` I wrote is rather limited in scope. A base class would be a good place to document @fkiraly comments about generators in general:

>I think the following should be different concrete classes:
>
>* different sampling distributions
>* different sampling algorithms
>The following should be different template classes:
>
>* different tasks or types of data set
>The following should be hyper-parameters of each concrete class:
>
>* parameters of the sampling distribution
>* parameters of the sampling algorithm
>* random seed (important)
> The following should be parameters of sample:
>
>* number of samples and other "size/dimension" properties of the dataset, e.g., n_variables, n_instances, and so on
>* any parameters related to distributed/parallelized runs or contracting

**Comment by karthikn72** [comment]
>     * any parameters related to distributed/parallelized runs or contracting
Hi just to clarify, could someone please elaborate on this point a little? I am aware of how distributed/parallel computing works in general, but not exactly in this context

**Comment by mloning** [comment]
@karthikn72 for example the number of jobs `n_jobs` to use (a common argument in estimators).

**Comment by TonyBagnall** [comment]
hi @karthikn72 , I'm doing a bit of PR tidying up. Is this still current or can I close it? Happy for you to reopen it later.

**Comment by karthikn72** [comment]
> hi @karthikn72 , I'm doing a bit of PR tidying up. Is this still current or can I close it? Happy for you to reopen it later. 

Hi, sorry for not getting back to this earlier as I was a bit busy. Pleas do close it for now, and I'll surely reopen it later when I get time. Thanks.

**Comment by TonyBagnall** [comment]
no worries, completely understand, look forward to your future contribution

**Pull request closed without merging**
