### PR TITLE
[ENH] Implement reconcilers for hierarchical predictions - transformers

### PR DESCRIPTION
**Pull request by ciaran-g**
#### Reference Issues/PRs

This PR adds a reconciler transformer, which takes hierarchical predictions and processes them so they sum appropriately. Three methods are implemented here out of the list in issue #2157
 - bottom up 
 - ols
 - wls_var

#### What does this implement/fix? Explain your changes.

Hierarchical reconciler which depends only on the structure of the hierarchy. The three methods are detailed [here](https://otexts.com/fpp3/hierarchical.html) and the code is constructed similar to the methodology as noted in these [slides](https://github.com/robjhyndman/reconciliation_review_talk/blob/main/10years_reconciliation.pdf). The only difference between the three methods is the construction of the "G" matrix.

#### Does your contribution introduce a new dependency? If yes, which one?

No

### CODE REVIEW

**Comment by ciaran-g** [comment]
just pushed a few checks on the index and method @fkiraly

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks for this, good start!

My main comment is that this needs to work for an arbitrary number of hierarchy levels. Currently I think it works only for precisely three.
It should work for two, four, and even one (in that case the series is returned unchanged).

For that, you also should set the tag
`"X_inner_mtype": ["pd.DataFrame", "pd-multiindex", "pd_multiindex_hier"]`
that way you can assume you are being passed a `pd.DataFrame` with one, two, three, or more levels.

**Comment by fkiraly** [comment]
PS: I took the liberty to update your branch from `main` and fix your tags (except `X_inner_mtype`)

**Comment by ciaran-g** [comment]
Closing for now - it should now work with hierarchy levels greater than or equal to two tho 👍

**Comment by fkiraly** [comment]
? why are you closing?
This has not been merged yet afaik?

**Comment by fkiraly** [comment]
We should try to get this merged, or am I misunderstanding sth?

**Comment by ciaran-g** [comment]
lol no, that's my bad! I was just closing until the we sorted the problem with the tests

**Comment by fkiraly** [comment]
currently it's linting - and we should leave it open.
We can merge the type check updates into it and then the tests should run.

**Pull request merged**
