### PR TITLE
[ENH] Add AutoARIMA from StatsForecast 

### PR DESCRIPTION
**Pull request by FedericoGarza**
#### Reference Issues/PRs

#2181 

#### What does this implement/fix? Explain your changes.

I've added `AutoARIMA` from `StatsForecast`.

#### Does your contribution introduce a new dependency? If yes, which one?

Yes, [`StatsForecast`](https://github.com/Nixtla/statsforecast). I've included it as a soft dependency.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Looks good to me, excellent!
Not much iteration needed on this PR :smile:

Non-blocking comment, I wonder how much of the boilerplate can be avoided, or how much is duplicated between `pmdarima` and `statsforecast`.

**Comment by aiwalter** [comment]
Hm now we have 2 classes with same name. I think that is not ideal solution, have never seen a package that has sth like this

**Comment by FedericoGarza** [comment]
Hi @aiwalter ! I could change the name if necessary :)

**Comment by aiwalter** [comment]
@FedericoGarza did you look into the exisitng `AutoARIMA` and whether we could have both in this class with 2 different backends?

**Comment by aiwalter** [comment]
@fkiraly @lmmentel I think we should not release before this here is resolved

**Comment by fkiraly** [comment]
ok, let´s move the release by 1 day then. I feel this needs discussion at the CC

**Comment by fkiraly** [comment]
(sorry for merging, @aiwalter, I assumed tacit approval)

**Comment by lmmentel** [comment]
Wouldn't a simple solution be to add a prefix to the class name e..g `StatsForecastAutoARIMA`?

**Comment by aiwalter** [comment]
yes that is one solution, there was a more general discussion on Slack about this topic. In my opinion it should not go in as it is now at least

**Comment by FedericoGarza** [comment]
Hey @aiwalter @fkiraly @lmmentel! I've created a PR renaming the class as suggested  (#2272).  Let me know what you think😉

**Pull request merged**
