### PR TITLE
AutoARIMA access fitted order and seasonal order under get_fitted_params

### PR DESCRIPTION
**Pull request by AngelPone**
#### Reference Issues/PRs

Finish #962 

#### What does this implement/fix? Explain your changes.

`get_fitted_params()` of `AutoARIMA()` can access `order` and `seasonal order` of the fitted ARIMA model

#### Does your contribution introduce a new dependency? If yes, which one?

no

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Quick and painless, thanks!

**Review by fkiraly — CHANGES_REQUESTED** [review]
actually, not ready for approval - the linter is unhappy.

In this specific case:
Please use double-quotes, not quotes, for strings.

Generally:
I recommend you have local linters running that tells you this already in your developer IDE. Happy to show how this works in one of the community collaboration sessions if you are interested.

**Comment by fkiraly** [comment]
linter still unhappy - hope you don't mind me fixing, @AngelPone

**Comment by AngelPone** [comment]
Thanks @fkiraly  I'm still not familiar about this, but I'm trying!

**Comment by fkiraly** [comment]
> I'm still not familiar about this, but I'm trying!

No worries, happy to help - it's not 100% straightforward, setting up local linter and pre-commits.
We do the occasional screenshare walkthrough at the community collab meetings, if someone is interested.
We're also hoping to improve our developer documentation here (see all the "documentation" labeled issues).

**Review by fkiraly — APPROVED** [review]
tests look good now, will merge once they pass.

**Pull request merged**
