### PR TITLE
Add content to documentation guide for use in docsprint

### PR DESCRIPTION
**Pull request by RNKuhns**
#### Reference Issues/PRs

#1245

#### What does this implement/fix? Explain your changes.

This includes content in the developer guide's documentation section (and a tweak to the reviewer guide) to clarify our docstring expectations ahead of the docsprint.

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### What should a reviewer concentrate their feedback on?

Is there anything you don't agree with in the documentation guide? 
Should we expect reviewers to ensure documentation meets our standards (I think we need to in order to ensure quality of sktime documentation post docsprint)

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by RNKuhns** [comment]
@fkiraly and @mloning I know this is kind of last minute ahead of the docsprint, but can you take a look at my suggested documentation guide (sub-part of developer guide) and suggested tweak to reviewer guide's documentation section. 

I'm open to suggestions on either place, but we should try to implement this ahead of the start of the docsprint if possible (so we give anyone working to fix docstrings clear guidance on what we expect). 

If we are particularly ambitious we could add the update of a estimator docstring to this PR (I'd suggest a forecaster that doesn't have too many hyperparameters). That way we could tell people to look at that as an example.

**Comment by fkiraly** [comment]
looks good, would you mind merging material from this issue?
https://github.com/alan-turing-institute/sktime/issues/1148

**Comment by fkiraly** [comment]
one change we made was "components" for class docstrings

**Review by mloning — APPROVED** [review]
Looks good @RNKuhns - we can also iterate over this based on the questions/feedback from the docsprint.

**Pull request merged**
