### PR TITLE
Add expanding window splitter

### PR DESCRIPTION
**Pull request by koralturkk**
#### Reference Issues/PRs

Feature #552 

#### What does this implement/fix? Explain your changes.
It adds a functionality crossvalidate models with an expanding window. 

#### Does your contribution introduce a new dependency? If yes, which one?
No, it does not.

#### What should a reviewer concentrate their feedback on?

Still in debugging

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by mloning — COMMENTED** [review]
Thanks @koralturkk - looks all good to me, very clean code! 

Could we add a simple unit test to make sure it's behaving as expected?

**Comment by koralturkk** [comment]
@mloning Yes, I was thinking of doing that, I still need to check the existing unit tests which are being used on other splitters. I will be updating the PR when the unit tests are also implemented.

**Comment by mloning** [comment]
Great - thanks @koralturkk!

**Comment by koralturkk** [comment]
Hi @mloning, I have added a notebook example and unit tests, I would appreciate if you take a look and let me know if you want to add more.

**Review by mloning — APPROVED** [review]
Thanks @koralturkk - looks all good to me! 

I started playing around with the notebook and made some minor changes, mostly formatting and style. 

Will leave this PR open a bit longer and merge later today or in the next few days!

**Comment by mloning** [comment]
Thanks again @koralturkk - now merging!

**Pull request merged**
