### PR TITLE
Classifiers capabilities tags Issue #996

### LINKED ISSUE #996: Summary of the Capabilities of time series classifiers
summary of the type of data input the main sktime classifiers can deal with. If you are interested in extending the capabilities of any of these classifiers, get in touch and we will offer some guidance. 

image

### PR DESCRIPTION
**Pull request by bilal-196**
#### Reference Issues/PRs

Fixes #996 .

#### What does this implement/fix? Explain your changes.

This PR generates a summary of the capabilities of different classifiers. The main list of classifiers included showing their capabilities tags. 
For clarity, some utility classifiers, such as ColumnEnsembleClassifier, ComposableTimeSeriesForestClassifier, IndividualBOSS, IndividualTDE, ProximityStump, ProximityTree, are not included as they miss such tags.

#### What should a reviewer concentrate their feedback on?

This PR generates csv file with the summary of the capabilities of classifiers. Kindly note below,

1. Below command is not used as it throughs an error with the compatibility of fbprophet.
           from sktime.utils import all_estimators
2. Some utility classifiers miss the capabilities tags which I am focusing to implement in next PR.

#### Any other comments?

I would really be grateful if you could spare some time to review and approve it. @mloning @TonyBagnall @ABostrom 

##### For all contributions
- [Y ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [Y ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
@bilal-196, thanks for your contribution!

Although, we are currently refactoring the tags/capabilities system, as the last posts in the issue #996 show.

If you would like to work on this topic, consider contributing to #1146, e.g., moving the capabilities to `_tags` first, as described in there.

**Comment by fkiraly** [comment]
@bilal-196, thanks for your contribution!

Although, we are currently refactoring the tags/capabilities system, as the last posts in the issue #996 show.

If you would like to work on this topic, consider contributing to #1146, e.g., moving the capabilities to `_tags` first, as described in there.

**Comment by fkiraly** [comment]
were you at the scipy sprint, @bilal-196? Not sure I remember you, but maybe your alias was different?

**Comment by bilal-196** [comment]
@fkiraly Thanks for the update. I am going to update one classifier as per #1146 and will raise a new PR. Thanks to reviewing that.

**Pull request closed without merging**
