### PR TITLE
Remove license info from docstrings

### LINKED ISSUE #1433: [DOC] Remove license info from module docstrings
#### Describe the issue linked to the documentation

There has been cases popping up where module docstrings are including our licensing information. 

Licensing should not be in docstrings (See [numpydoc module docstrings](https://numpydoc.readthedocs.io/en/latest/format.html#documenting-modules). It should be in a comment line. 

#### Suggest a potential alternative/fix

Solution is manually going through and finding the cases where we have included licensing information in the module docstrings and moving it to a comment line above the docstring.

The result should look something like this:

``` python
#!/usr/bin/env python3 -u
# -*- coding: utf-8 -*-
# copyright: sktime developers, BSD-3-Clause License (see LICENSE file)
"""Some docstring (single or multiple line) here."""
```

### PR DESCRIPTION
**Pull request by ronnie-llamado**
#### Reference Issues/PRs

Fixes #1433.

#### What does this implement/fix? Explain your changes.

Moved any copyrights inside a docstring to a comment above.

#### Does your contribution introduce a new dependency? If yes, which one?
N/A

#### What should a reviewer concentrate their feedback on?
N/A

#### Any other comments?
N/A

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by mloning — APPROVED** [review]
Thanks @ronnie-llamado - looks all good to me!

**Comment by mloning** [comment]
The doc-quality tests are failing due to: D100: Missing docstring in public module. We need to add a string to the top of all (public) Python files, a one-sentence description of what's included in the file. Would you mind adding that?

**Comment by ronnie-llamado** [comment]
I've added the missing module docstrings to the files in this commit. 

Side note: It might be worth opening another issue for doc-quality errors and/or config. Running `pydocstyle` on the code base with the current config yields 898 errors.

**Review by RNKuhns — APPROVED** [review]
@ronnie-llamado this looks good to me. Thanks for hopping on it so quickly.

**Comment by RNKuhns** [comment]
> I've added the missing module docstrings to the files in this commit.
> 
> Side note: It might be worth opening another issue for doc-quality errors and/or config. Running `pydocstyle` on the code base with the current config yields 898 errors.

@ronnie-llamado is that something you'd be willing to help with? I'd suggest we attack the errors on a module by module basis.

**Review by mloning — APPROVED** [review]
Thanks @ronnie-llamado

**Pull request merged**
