### PR TITLE
updated-core-developers-doc

### LINKED ISSUE #1837: [DOC] update core developers
The core developer list `docs/source/about/team` should be updated:

* Ryan Kuhns @RNKuhns has left and is inactive
* Patrick Schäfer @patrickzib has joined core developers

Core developers should also be ordered alphabetically by first name, then last name.

### PR DESCRIPTION
**Pull request by sumit-158**
close #1837

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks, @sumit-158!

I think there are still a few outliers regarding alphabetical order: Aaron should be before Anthony (a before n), Franz before Freddy (a before e)

**Comment by fkiraly** [comment]
hm, and Guzal should be after George?

**Review by fkiraly — APPROVED** [review]
Thanks :-)

Feel free to add yourself as a contributor if you like. Small contribution, but a useful contribution!

**Comment by fkiraly** [comment]
Apologies, it's not done yet - the tests are failing, probably because there's a trailing whitespace. Click on "details" next to the failing test, "code-quality" to see which line it's about.

**Comment by sumit-158** [comment]
> Apologies, it's not done yet - the tests are failing, probably because there's a trailing whitespace. Click on "details" next to the failing test, "code-quality" to see which line it's about.

@fkiraly  I am unable to find any tailing whitespace?

**Comment by sumit-158** [comment]
> Thanks :-)
> 
> Feel free to add yourself as a contributor if you like. Small contribution, but a useful contribution!

How can I add myself as a contributor!

**Comment by fkiraly** [comment]
> How can I add myself as a contributor!

the `.all-contributorsrc` file, in root. Your contribution would be `"doc"`.

**Pull request merged**
