### PR TITLE
Correct the `examples/catch22.ipynb` call to `transform_single_feature`

### LINKED ISSUE #1783: [BUG] catch22.ipynb notebooks throws  'Catch22' object has no attribute '_transform_single_feature'
**Describe the bug**

When running the `examples/catch22.ipynb` with `jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=600 examples/catch22.ipynb` the following error pops up:

```
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
transformed_feature_uv = c22_uv._transform_single_feature(IPD_X_train, "CO_f1ecac")
print(transformed_feature_uv)
------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_2209/4126608039.py in <module>
----> 1 transformed_feature_uv = c22_uv._transform_single_feature(IPD_X_train, "CO_f1ecac")
      2 print(transformed_feature_uv)

AttributeError: 'Catch22' object has no attribute '_transform_single_feature'
AttributeError: 'Catch22' object has no attribute '_transform_single_feature'
```

**To Reproduce**

This is taken form CI, which means ubuntu-20.04 and python 3.7.

**Expected behavior**

Notebook executes without errors.

**Additional context**

**Versions**
<details>

</details>

### PR DESCRIPTION
**Pull request by lmmentel**
#### Reference Issues/PRs

fixes #1783 

#### What does this implement/fix? Explain your changes.

Correct the method name call that was causing an error.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by lmmentel** [comment]
@MatthewMiddlehurst would you mind giving it a look?

**Review by MatthewMiddlehurst — APPROVED** [review]
Do we not have the test-examples action to pick up stuff like this?

**Comment by lmmentel** [comment]
> Do we not have the test-examples action to pick up stuff like this?

Yes, but for some reason this fails for me on #1620. I would suspect that it should also fail on main but I didn't investigate if it does. Long story short `Catch22` class does not have a `_transform_single_feature` method as in the original notebook but a `transform_single_feature` (please notice the leading underscore) which is what I try to fix here.

**Comment by lmmentel** [comment]
@fkiraly this should be easy to merge :slightly_smiling_face:

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
