### PR TITLE
[MNT] Bump numpy version to >=1.21.0, <1.22

### LINKED ISSUE #1787: StatsModels and Numpy to have a >= version instead of == version
Would it be possible to use StatsModels >= 0.12.1 and Numpy >= 1.19.3 instead of StatsModels == 0.12.1 and Numpy == 1.19.3?

Currently the file main/setup.py uses the same version for StatsModels  and Numpy  in min and max requirements

### LINKED ISSUE #1794: [ENH] Upgrading to numpy 1.20
sktime requires numpy <1.20. This severely limits its use in larger more modern projects. Moving to numpy 1.20 would help allow sktime to be used in more projects without causing dependency issues.

### PR DESCRIPTION
**Pull request by lmmentel**
#### Reference Issues/PRs

- Fixes #1794 (& duplicate #1914)
- Fixes #1787 

#### What does this implement/fix? Explain your changes.

Bumping numpy to >=1.21.0,<1.22 

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by lmmentel** [comment]
Looks like nothing break after bumping numpy :slightly_smiling_face: :rocket:

**Review by TonyBagnall — APPROVED** [review]

**Review by fkiraly — APPROVED** [review]
Great!

Quick Q, why does nothing break? Because we discontinued support for `python 3.6` (which in turn influences the upper `pandas` bound)?

**Comment by lmmentel** [comment]
> Quick Q, why does nothing break? Because we discontinued support for `python 3.6` (which in turn influences the upper `pandas` bound)?

This is not an easy question to answer, but recent changes in #1620  made it easy to introduce this change also dropping 3.6 made release some of the constraints on package versions.

**Comment by fkiraly** [comment]
So, here's another question, @lmmentel: why a lower bound of 01.21.0? This does not include the old version, and may break things for users.
Would it be problematic to have this at 1.19.3 (the old version)?

**Comment by lmmentel** [comment]
I bumped it since I got a dependabot alert about my other package that there are vulnerabilities in numpy the recommended action is to bump it at least to 1.21, I can decrease the lower bound if you are afraid of users not being able to use sktime. BTW this will only affect people installing sktime 0.10.0 onward so I don't think it's an issue.

**Comment by fkiraly** [comment]
> I bumped it since I got a dependabot alert about my other package

This violates the "Thou shalt have no other packages before sktime" clause in the sktime code of conduct ... or am I confusing this with another literature source? :-)

**Comment by ilkersigirci** [comment]
Is there any specific reason not to include numpy version 1.22 ?

**Comment by fkiraly** [comment]
@ilkersigirci, since this is a general Q, answering it here: https://github.com/alan-turing-institute/sktime/discussions/2037

**Pull request merged**
