### PR TITLE
Tsc refactoring/arsenal

### PR DESCRIPTION
**Pull request by victordremov**
#### Reference Issues/PRs

TSC refactor issue: https://github.com/alan-turing-institute/sktime/issues/1146

#### What does this implement/fix? Explain your changes.

Refactor `Arsenal` classifier:
- rename `fit`, `predict` and `predict_proba` to their private versions `_fit` etc
- remove input checks and `is_fitted` property setting in private methods
- remove redundant imports
- rename `capabilities` to `_tags`
- change full names to github IDs in __author__

#### Does your contribution introduce a new dependency? If yes, which one?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
Changes made in #1305 also.

**Comment by dremovv** [comment]
> Changes made in #1305 also.

Yes, I have seen #1305 right after I made this PR. I do not think it is a good idea to refactor and make meaningfull changes at the same time, so this PR will wait until #1305 is merged and then I will solve merge conflicts.

**Comment by MatthewMiddlehurst** [comment]
#1305 is now merged. I'm unsure if any more changes need to be made to it however.

At some point soon I can go over all the open classification PR and files and see which ones still need to be updated.

**Comment by victordremov** [comment]
The code is already refactored in #1305 according to new extension template.
Checked out no additional work needs to be done, close the PR.

**Comment by fkiraly** [comment]
oh - sorry, perhaps it would be a good idea to coordinate next time...

I'll add a checklist of classifiers to #1146.

**Comment by fkiraly** [comment]
Really sorry for this... feel free to pick another one, and let me know if you are aware of other refactors going on.

**Pull request closed without merging**
