### PR TITLE
[ENH] Retry url request after HTTPError

### PR DESCRIPTION
**Pull request by khrapovs**
#### Reference Issues/PRs

Follow up on Slack conversation: "Looks like test_load_solar is causing CICD to fail. Does anyone experience something similar?" (2022-08-11 in Contributors channel). More precisely, here is the `HTTPError` causing the failure: https://github.com/alan-turing-institute/sktime/runs/7774941244?check_suite_focus=true#step:10:1676

#### What does this implement/fix? Explain your changes.

Use [backoff](https://pypi.org/project/backoff/) library to retry data load from url in `sktime.datasets._single_problem_loaders.load_solar`.

#### Does your contribution introduce a new dependency? If yes, which one?

[backoff](https://pypi.org/project/backoff/)

#### What should a reviewer concentrate their feedback on?

Does this failure happens so often that it is worth introducing a new dependency?

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [X] I've added unit tests and made sure they pass locally.
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Good idea!

But, we can't introduce `backoff` as a core dependency, since it's used only in the tests.
It should be moved to the `dev` dependency set.

**Comment by fkiraly** [comment]
assuming you are on holiday or otherwise off, @khrapovs, so I´m just moving this to the other dependency set myself (to avoid the load errors)

**Comment by khrapovs** [comment]
I wanted to come back to it on Monday, but you are welcome to take it over if you think it becomes a pressing issue.

**Comment by fkiraly** [comment]
> I wanted to come back to it on Monday, but you are welcome to take it over if you think it becomes a pressing issue.

ok, sorry - feel free to revert my changes.

I was trying to isolate `backoff` as a soft dependency, as moving it to the soft dependency set was breaking things here and there.

**Comment by fkiraly** [comment]
merging since the error is popping up frequently on PR

**Pull request merged**
