### PR TITLE
Fix Imputer. Added Imputer tests

### LINKED ISSUE #1643: [BUG] evaluate fails with Imputer
**Describe the bug**
Calling `evaluate` with a pipeline and imputer fails.  

**To Reproduce**
```python
import pandas as pd
import numpy as np
from sktime.transformations.series.impute import Imputer
from sktime.forecasting.compose import ForecastingPipeline
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.model_evaluation import evaluate
from sktime.forecasting.model_selection import SlidingWindowSplitter

y = pd.Series(np.random.normal(size=100))
X = pd.DataFrame(np.random.normal(size=(100, 2)))
X.iloc[3, 1] = np.nan

cv = SlidingWindowSplitter(fh=[1, 2, 3])

forecaster = ForecastingPipeline([
    ("impute", Imputer()),
    ("forecast", NaiveForecaster())
])

evaluate(forecaster, cv=cv, y=y, X=X)
```

**Expected behavior**
No error. 

**Versions**
<details>
System:
    python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:37:09)  [Clang 10.0.1 ]
executable: /Users/mloning/.conda/envs/sktime-dev/bin/python
   machine: Darwin-19.6.0-x86_64-i386-64bit

Python dependencies:
          pip: 21.2.4
   setuptools: 49.6.0.post20210108
      sklearn: 0.24.2
       sktime: 0.8.1
  statsmodels: 0.12.1
        numpy: 1.19.3
        scipy: 1.6.0
       Cython: 0.29.21
       pandas: 1.2.3
   matplotlib: 3.3.4
       joblib: 1.0.1
        numba: 0.53.1
     pmdarima: 1.8.2
      tsfresh: 0.17.0
</details>

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
Closes #1643

### CODE REVIEW

**Review by mloning — APPROVED** [review]
Looks good, let's merge after v0.9.0 has been released

**Comment by aiwalter** [comment]
Why after? Does it not make sense to have bug fixes in this release?

**Comment by fkiraly** [comment]
>Why after? Does it not make sense to have bug fixes in this release?

Exactly my point! They were on the 0.9.0 milestone, ready to merge.
A few days of delay will result in sticking to the milestone plan and improved reliability, quality.
Let's not rush the release, @mloning.

**Comment by mloning** [comment]
Hi @aiwalter, yes the release was ready to go, that's why I wanted to hold back on this.

**Pull request merged**
