### PR TITLE
[DOC] Added list of interns to website

### PR DESCRIPTION
**Pull request by aiwalter**
#### What does this implement/fix? Explain your changes.
Added list of Interns to website.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Nice!

I think though we should also include mentees?

Further, you are missing Taiwo from Outreachy.

**Comment by aiwalter** [comment]
Taiwo didnt answer if she is fine with it, mentors we would have to ask them first. So feel free to do so and make a PR

**Comment by fkiraly** [comment]
we could just make PRs and ask for confirmation?

The information is not secret, they have already put it there as issues on the `mentoring` repo.

**Comment by aiwalter** [comment]
Lets merge this already

**Comment by fkiraly** [comment]
I think from multiple perspectives, it would be better to include all the mentees, not just paid interns.

Perspectives from which I see benefits: inclusivity towards the individuals; branding and visibility of `sktime` mentoring; completeness of information.

**Comment by aiwalter** [comment]
But this is the sponsoring section

**Comment by fkiraly** [comment]
> But this is the sponsoring section

Ah, I see. Then, we should include Taiwo at least.
I would also add a link to the issue tracker of the `mentoring` repo, which has details about the internships.

**Comment by aiwalter** [comment]
@thayeylolu pls confirm

**Comment by aiwalter** [comment]
@fkiraly lets merge this then

**Comment by fkiraly** [comment]
merge it?

**Pull request merged**
