### PR TITLE
[ENH] Pass frequency explicitly to `sktime.utils.datetime._shift` function

### LINKED ISSUE #1750: [ENH] address FutureWarning: Timestamp.freq is deprecated and will be removed in a future version
It would be great if someone could address the repeated
`FutureWarning: Timestamp.freq is deprecated and will be removed in a future version`
that is caused by various places all over the codebase.

The most prominent source seems to be `utils/datetime`

### PR DESCRIPTION
**Pull request by khrapovs**
#### Reference Issues/PRs

Partially addresses #1750 

#### What does this implement/fix? Explain your changes.

On master function `_shift` extracts the frequency information from `pd.Timestamp` object which in future will cot contain it. Hence, here I explicitly pass frequency from the outside. This frequency is used to calculate offset for `pd.Timestamp` input, Frequency is inferred from `self._y` and stored in `self._freq` attribute of `sktime.forecasting.base._base.BaseForecaster` after `fit` is invoked.

#### Does your contribution introduce a new dependency? If yes, which one?

No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [X] I've added unit tests and made sure they pass locally.
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by khrapovs** [comment]
This PR has an overlap with https://github.com/alan-turing-institute/sktime/pull/2834 which should be merged first.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks, nice work dealing with `_shift`!

Change requests:
* `self._freq` is never read in the `BaseForecaster`, so it should not be written in `BaseForecaster`
* from a user perspective, `_shift` should not require a `freq` argument. Why are we passing it? Can we not infer it internally?

**Comment by fkiraly** [comment]
>from a user perspective, `_shift` should not require a `freq` argument. Why are we passing it? Can we not infer it internally?

Ok, I understand that we cannot do this for `pd.Timestamp` anymore.

May I request instead that `_shift` is extended so it can also deal with suitable `pandas.Index` elements? I.e., defaults to `pandas.Index.shift` if an index is passed?

This is building functionality towards indices that might be useful to have later.

**Comment by fkiraly** [comment]
Tried the alternative approach here, to deal with `_shift`:
https://github.com/alan-turing-institute/sktime/pull/2909

`freq` is not explicitly passed, but passed as part of the `index` object `_cutoff`.
Might be a less invasive kind of surgery...

**Comment by khrapovs** [comment]
> `freq` is not explicitly passed, but passed as part of the `index` object `_cutoff`. Might be a less invasive kind of surgery...

`_shift` is an internal function only used in a few places. Please, let's not waste time on preserving its signature by overcomplicated treatment of `cutoff`.

**Comment by fkiraly** [comment]
>Please, let's not waste time on preserving its signature

It's not `_shift` I'm worried about but `BaseForecaster`.

**Comment by khrapovs** [comment]
Was solved by #2932

**Pull request closed without merging**
