### PR TITLE
Add example notebooks for resizing transformer

### PR DESCRIPTION
**Pull request by DmitriyValetov**
Added a notebook to examples. ("TSinterpolation_tutorial.ipynb")

### CODE REVIEW

**Comment by mloning** [comment]
Thanks for the fix! Please remove the `sktime/tests/test_interpolate.py` file, I moved it to `sktime/transformers/series_as_features/tests`

**Comment by mloning** [comment]
I like the notebook! Could you add a bit more text on how the interpolation works below the headings?

**Comment by DmitriyValetov** [comment]
Are comments good?

**Comment by mloning** [comment]
@DmitriyValetov I've made some minor changes to the comments, they look good! 

But I ran into an error when using the `random_cut` function, could you check that again? 

Once that's sorted out, I'm happy to merge!

**Comment by mloning** [comment]
Looks good to go, will merge later! Thanks! 🚀

**Pull request merged**
