### PR TITLE
Adding table of content in the forecasting tutorial

### PR DESCRIPTION
**Pull request by bilal-196**
#### Reference Issues #986 

This PR fixes issue #986 

#### What does this implement/fix? Explain your changes.

A table of content has been included in the forecasting tutorial.

#### Does your contribution introduce a new dependency? If yes, which one?

No, it does not introduce any further dependency.

#### What should a reviewer concentrate their feedback on?

Kindly look at the table of content, its structure and position. If ok, I will add a similar table to other tutorials as well. 
@fkiraly 
##### For all contributions
- [Y] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [Y] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Brilliant, thanks!

Now it may be just me on Windows: I've tried clicking on the ToC links in vscode, and also in the GitHub interface, and it didn't take me to the respective section header.

Would you mind double checking whether they are correct?

As said, it could be just a problem with my set-up, but let's double check.

**Comment by bilal-196** [comment]
@fkiraly, I have checked each of the links at least 3 times and all are working fine i.e. each link on clicking leads to the designated position. Please suggest if anything else is needed from my side.

Apart from it, are you happy with overall structure, I mean should I follow the same format for other tutorials?

**Comment by bilal-196** [comment]
Hi, @mloning , would be great if you could have a look at this PR.

**Comment by fkiraly** [comment]
>Apart from it, are you happy with overall structure, I mean should I follow the same format for other tutorials?

Yes, although some of them may be refactored in the near future.

Another thing you could investigate in relation to the forecasting notebook is why the section headers are not properly displayed in the tutorial here:
https://www.sktime.org/en/latest/examples/01_forecasting.html
in the navitagion panel on the left.

Which section headers are displayed in the navigation panel on the left seems totally random to me.

Maybe you have a good idea?

**Comment by fkiraly** [comment]
>@fkiraly, I have checked each of the links at least 3 times and all are working fine i.e. each link on clicking leads to the designated position. Please suggest if anything else is needed from my side.

It's really strange, they do not work for me, I also checked 3 times. Is it maybe a browser issue?

Would be good if someone else could review this, too - to distinguish whether it's just a thing with my browser/setup or whatevre, or whether it's only @bilal-196 for whom it works locally.

**Comment by fkiraly** [comment]
@mloning, @RNKuhns, @aiwalter, could one of you please look at this PR and let us know whether the links are working fine for you?

**Review by fkiraly — APPROVED** [review]
Ok, I can confirm now that it works in jupyter notebook.

It does not work in visual studio code, that's probably an issue with the plugin which was recently updated. So, fine to go!

**Pull request merged**
