### PR TITLE
Resolved warnings in notebook examples

### PR DESCRIPTION
**Pull request by alwinw**
#### Reference Issues/PRs

Reopening #407 as new separate pull request

#### What does this implement/fix? Explain your changes.

Reran notebooks to clean up `.ipynb` outputs (example of previous warnings below):

image

image

Also cleaned up some of the python code in the notebook, e.g. removed trailing `;`.

#### Does your contribution introduce a new dependency? If yes, which one?

N/A

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by mloning** [comment]
Ha, I like the `;` to suppress the output from plotting functions 😄

**Comment by mloning** [comment]
Let me know when you think this is good to go!

**Comment by alwinw** [comment]
Whoops sorry about that @mloning! I've added the `;` back in now - can't say I noticed a difference in the output after I removed them. Let me know if you spot anything else

**Comment by mloning** [comment]
Maybe it depends on the matplotlib settings (e.g. `%matplotlib inline`), not sure. I'll merge this now, thanks for cleaning this up!

**Pull request merged**
