### PR TITLE
Feature/information criteria get_fitted_params

### LINKED ISSUE #931: Exposing AIC, BIC and HQIC from sktime models via get_fitted_params
After fitting a time series model (i.e. ARIMA, AutoETS...etc), there is no way to retrieve individual fitting scores (i.e. AIC, BIC, HQIC..etc) for evaluation.

The following key does not exists
model.get_fitted_params()['aic']
model.get_fitted_params()['bic']
model.get_fitted_params()['hqic']

### PR DESCRIPTION
**Pull request by ltsaprounis**
#### Reference Issues/PRs

Fixes #931

#### What does this implement/fix? Explain your changes.

Adding the available information criteria (AIC, AICc, BIC, HQIC) for various forecasting algorithms.
TBATS and BATS did not have a get_fitted_params method so I added it in the adapter there. Maybe we'll want to add additional parameters returned there. 

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?

Is get_fitted_params the right place to return those? maybe a similar function e.g. get_fit_results is more appropriate.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Nice! Looks good from my side. Must have been fiddly to find where the parameters are...

**Comment by fkiraly** [comment]
Regarding this question:

> Is get_fitted_params the right place to return those? maybe a similar function e.g. get_fit_results is more appropriate.

A very valid point - do we want to separate fitted parameters from things like summaries or inspection?

The MLJ package, where I've co-designed the interfaces, does separate this, and I think it's a good idea - see
https://alan-turing-institute.github.io/MLJ.jl/stable/machines/#Inspecting-machines

During the dev days later this month, we'll probably refactor the interfaces, and this may be one thing we add - feel free to join.
I've also opened an issue #944 so we don't forget.

**Comment by fkiraly** [comment]
@mloning, have you had a look at this?
This affects the relatively new `get_fitted_params` interface, would like to have a 2nd opinion.

**Comment by mloning** [comment]
I agree @fkiraly, fitted parameters are different from summary statistics of the model, so suggest to create a separate interface for them.

**Comment by ltsaprounis** [comment]
Thanks @mloning and @fkiraly. I think this is the right call, it felt wrong to put AIC etc. in the same place as the fitted model parameters. Do you think I should keep going with this PR and implement the function to get summary statistics here? or is it more appropriate to do it in a separate PR (maybe linked to #944 ).

**Comment by mloning** [comment]
I suggest to work on the interface first in a separate PR, before we start adding it to concrete implementations.

**Comment by fkiraly** [comment]
hm, @mloning, I would suggest we merge this and then perhaps later move it to the other interface - or this nice contribution may be buried under refactors and commits on top?

Rationale being, moving it from `get_fitted_params` to `get_report_params` or similar is almost trivial once we have the interface point, while finding the PR again, updating it, and remembering to do this later may not be easy.

**Review by mloning — APPROVED** [review]

**Comment by fkiraly** [comment]
2 approvals, so can be merged now.

**Comment by fkiraly** [comment]
@ltsaprounis, I think @mloning and I have aligned that we'll merge this and then later re-factor along #971.

Would you like to merge?
Minor suggestion, please add the names of the classes you've changed in the squashed commit message.

**Comment by fkiraly** [comment]
merged due to dependencies and 2 approvals

**Comment by ltsaprounis** [comment]
Sorry @fkiraly I was on holidays for the past few days and nowhere near my laptop. Just realised Github has an "out of office" option...

Looks good to me, thanks for merging!

**Pull request merged**
