### PR TITLE
Fix ForecastingPipeline import

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
#967 

#### What does this implement/fix? Explain your changes.
* Fixes import error from merging into main without first updating from main

### CODE REVIEW

**Review by aiwalter — APPROVED** [review]

**Comment by aiwalter** [comment]
I am wondering what happened? Are some CI/CD only running on `main`?

**Comment by mloning** [comment]
No I merged without updating the branch from `main` and some other changes happened on `main` in the meantime, my fault, didn't want to wait again for the CI to finish.

**Comment by fkiraly** [comment]
I think Iknow precisely what happened - yesterday, I merged #1068 which removed the `_has_tag` import from `_pipeline`.

@aiwalter forgot to merge `main` into his branch before merging into `main`, so didn't notice that the removed import broke his change which was using `_has_tag`.

Right?

**Comment by fkiraly** [comment]
PS: my preferred fix would be #1119, but don't mind either way to get this done quickly.

**Comment by aiwalter** [comment]
I thought merging into `main` is blocked if branch is outdated?

**Comment by fkiraly** [comment]
Also, I think we should print this thread out and hang it on the wall for posterity, @mloning admitting that the tests take very long, and indirectly showing that that very fact introduces risk to the codebase 😄

**Comment by fkiraly** [comment]
@mloning, are you watching this? Tests look ok, but don't want to merge in case we again do a double merge accidentally.

**Comment by fkiraly** [comment]
ok, going to merge this now. Still waiting for appveyor, but everything else is fine and it can't break more than it already is.

**Comment by mloning** [comment]
oh I've always said that the tests are slow but seems like nobody wants to work on them 👀

**Comment by fkiraly** [comment]
I want to work on tests but I would really like to refactor them with scitype dispatch for which I'd really like the tag system and the aliasing in #980 ...

Because that would allow you to dispatch on tags (behaviour), scitypes, as well as different inputs easily, instead of having to hardcode all the cases.

**Comment by mloning** [comment]
@fkiraly yes that makes sense - setting up the CI is also not my favourite work, it's very fiddly always but I'd love to move away from appveyor

**Pull request merged**
