### PR TITLE
[ENH] classifier single class handling

### PR DESCRIPTION
**Pull request by fkiraly**
Handles "single class seen in `fit`" scenario that can lead to infinite loops according to unreported bug discussed in PR #3110.

Alternative solution which simply returns "that class" predicted every time, instead of erroring out. Includes tests.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
While this will ensure all classifiers return a single class from predict, it won't stop them potentially crashing in fit. Easy solution for now is to just add another class_dictionary check in fit and stop building if it is length 1.

**Comment by fkiraly** [comment]
>While this will ensure all classifiers return a single class from predict, it won't stop them potentially crashing in fit. Easy solution for now is to just add another class_dictionary check in fit and stop building if it is length 1.

I did indeed consider that, but then I thought, this would make the "fitted" interface polymorphic. I.e., you would not have fitted parameters etc.
Would it crash the problematic estimators if we do not skip `fit`?

**Comment by MatthewMiddlehurst** [comment]
Not going to block for any of the above, just a concern.

**Comment by fkiraly** [comment]
> If we don't do it in the base class, we would probably require a test for all classifiers making sure it does interact as intended.

Yes, you are right.
We either need to handle it in the base class and test the base class, or ensure the individual implementations guarantee it, by test.

I'll add a test that checks `fit` only.

**Comment by fkiraly** [comment]
> Prehaps the fit check would be the place to raise a warning that only a single class has been seen and certain parameters have not been fit?

Yes, you are also right here, this is a good place to raise a warning (rather than the exception).

**Comment by fkiraly** [comment]
added test & warning now

**Comment by fkiraly** [comment]
Hm, I actually went with your earlier suggestion of just skipping `fit`. I think there were too many estimators that broke with just one class.

**Review by MatthewMiddlehurst — DISMISSED** [review]
Probably don't need the test_all_classifiers test any more if it is handled in fit, but if there is a reason I'm missing to keep it, sure.

**Comment by fkiraly** [comment]
> Probably don't need the test_all_classifiers test any more if it is handled in fit, but if there is a reason I'm missing to keep it, sure.

It seems very quick (no fitting actually happens), so I feel it makes sense to keep it for regression testing in case we change the logic, but no strong reason.

**Pull request merged**
