### PR TITLE
[ENH] replace deprecated np.int, np.float

### PR DESCRIPTION
**Pull request by fkiraly**
Take that, deprecation warnings.

This PR does what they were begging us to do since months - replacing deprecated `np.int` by `int` and `np.float` by `float`.

The deprecation message assures it's safe to do so ... let's see.

### CODE REVIEW

**Comment by fkiraly** [comment]
... not going to fix all the missing docstrings in 100 files here.
I hope it's fine to review it this way

**Comment by TonyBagnall** [comment]
> ... not going to fix all the missing docstrings in 100 files here. I hope it's fine to review it this way

Why not fix the doc strings? Someone has to

**Comment by TonyBagnall** [comment]
> > Why not fix the doc strings? Someone has to
> 
> There are ca 60 problems in the files that are being touched. Some I can fix, others are for code that I haven't written and would have to spend time to understand.
> 
> Tell you what: I'll fill in the docstrings if you run isort over the imports (or move it around manually).

Not my pr, I have enough on the go, but I do it update docstrings as I find them (currently in benchmarking)

**Comment by fkiraly** [comment]
This PR is *already* fixing an annoying issue and you are asking me to fix another annoying issue... can I fix the other annoying issue another time, please?

**Comment by fkiraly** [comment]
Ok, fine. I'll look at the docstrings.

**Comment by fkiraly** [comment]
Here you go.

**Comment by fkiraly** [comment]
@TonyBagnall, I did what you asked, can you please give it a review now? :-)

**Comment by TonyBagnall** [comment]
Great but of leg work :)

**Review by TonyBagnall — APPROVED** [review]

**Review by MatthewMiddlehurst — APPROVED** [review]

**Pull request merged**
