### PR TITLE
[MNT] Extend python support to 3.10

### LINKED ISSUE #2079: [ENH] Support Python 3.10
**Is your feature request related to a problem? Please describe.**
sktime cannot be installed in python 3.10 because the [pyproject.toml](https://github.com/alan-turing-institute/sktime/blob/main/pyproject.toml#L44) file lists python<3.10 as a dependency.

**Describe the solution you'd like**
We should let users install sktime in python 3.10. 

Related issue: https://github.com/alkaline-ml/pmdarima/issues/481

### PR DESCRIPTION
**Pull request by lmmentel**
#### Reference Issues/PRs

- Fixes #2079

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
Nice!
Fingers crossed...

**Comment by fkiraly** [comment]
@lmmentel, it seems the syntax you are using is not working as intended, as in "install only if python < 3.10"?

The CI installs still seem to try installing stan etc

**Comment by lmmentel** [comment]
> @lmmentel, it seems the syntax you are using is not working as intended, as in "install only if python < 3.10"?
> 
> The CI installs still seem to try installing stan etc

Which platform? Any logs you can share?

**Comment by fkiraly** [comment]
windows 3.10 logs

**Comment by lmmentel** [comment]
> windows 3.10 logs

windows CI uses conda so that's why pystan is installed (see https://github.com/alan-turing-institute/sktime/blob/d6d2e129edad2233bd4df7511147c3c769cbbad9/.github/workflows/test.yml#L74)

**Comment by fkiraly** [comment]
closed in favour of #2661 which is the only current practical approach to deal with the test failures due to version incompatibility of soft dependencies

**Pull request closed without merging**
