### PR TITLE
[ENH] Introduce classifier_type tag

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Adds a new tag for classifier type and adds it to most classifiers (#1390). Classifiers missing the tag either don't have a type (early classification, composable) or are not refactored/lack tags (ShapeDTW and TSF).

~~Removes the capability:missing_values tag, replaces any usage with handles-missing-data. As noted by the comment currently there, capability:missing_values is essentially a duplicate of the latter. The inconsistent usage of _ and - is a bit jarring, but that's an issue for another time, I guess.~~

There were a few commented out tags, I assume for annotation. Is there any reason these should not be removed or uncommented?

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
> Removes the capability:missing_values tag, replaces any usage with handles-missing-data. As noted by the comment currently there, capability:missing_values is essentially a duplicate of the latter. The inconsistent usage of _ and - is a bit jarring, but that's an issue for another time, I guess.

If we´re already doing this, do we want to change this in a separate PR; and everything to `handles_missing_data`?

Also, I think this needs deprecation, since it is a tag that users will likely have referred to in their code. I´ve tried to write a deprecation utility here https://github.com/alan-turing-institute/sktime/pull/1962 (not entirely complete, feel free to take it over)

**Comment by MatthewMiddlehurst** [comment]
If removing this is a larger job, then we can leave it to a separate PR. 

Deprecation seems a little overkill, no classifier actually uses the tag, only the base class, dummy classes for testing and templates. Keeping it in just leaves time for the issue to grow larger IMO.

**Comment by fkiraly** [comment]
> Deprecation seems a little overkill, no classifier actually uses the tag, only the base class, dummy classes for testing and templates. Keeping it in just leaves time for the issue to grow larger IMO.

Deprecation is not just about internal and developer use, imo, but also - and especially - about direct use by users and dependent packages. The tag might be common in use, since it´s about missing data.

**Comment by MatthewMiddlehurst** [comment]
We'll leave removing it for another PR then.

**Comment by fkiraly** [comment]
>We'll leave removing it for another PR then.

Ok - would you be so kind and move it to another PR?
So I can work on the deprecation utility and then move it in once that's merged.
I suggest a move to a name with only underscores, but we may like to keep the "capability" grouping.

**Comment by patrickzib** [comment]
Looks fine to me. 

One suggestion: what about adding a tag that defines, if the classifier returns a probability of a decision function?

**Review by patrickzib — APPROVED** [review]
I am fine with the change. See my comment about decision_function() vs predict_proba()

**Review by TonyBagnall — APPROVED** [review]
all looks fine to me

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
