### PR TITLE
Catch22 Refactor & Multithreading

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
The catch22 package has been updated to fix the operating system issue, so im moving the related classifiers and transformers out of contrib. https://github.com/chlubba/catch22/releases/tag/v0.2.0

Fixes and the addition of multithreading for interval and dictionary based classifiers I have previously contributed. Notebooks for these have been updated to include multivariate examples for classifiers which now have that capability.

### CODE REVIEW

**Review by mloning — COMMENTED** [review]
Thanks @MatthewMiddlehurst - looks all good! 

Can we update the online docs too, here in `sktime/docs/source/api_reference/` for `classification.rst` and `transformations.rst`?

**Comment by TonyBagnall** [comment]
this is quite a big PR, lots of new functionality. I think we wait until the last one has settled down before bringing this into master, but its very good to know it passes the tests 👍

**Review by mloning — APPROVED** [review]
The `0.5.2` release went through, so happy to merge this whenever you're ready.

**Review by TonyBagnall — APPROVED** [review]
actually think this can go in, we have another coming soon

**Pull request merged**
