### PR TITLE
[ENH] Adding FunctionTransformer

### PR DESCRIPTION
**Pull request by boukepostma**
#### What does this implement/fix? Explain your changes.
Adds an sktime-compatible adjustment of sklearn's FunctionTransformer. This class allows the user to easily create custom transformers that are different from the ones already included in sktime (e.g. SqrtTransformer, ExponentTransformer).

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
* Docstring: this is a slightly adjusted version of the docstring in sklearn's FunctionTransformer. Should I give credits to or cite the original authors and if so, how? 
* `def _check_inverse_transform()`: this works but there may be more reliable ways to check whether `func` and `inverse_func` are the inverse. Note: comparing with `==` does not work due to numeric errors.

#### Any other comments?
Looking forward to receiving your feedback!

##### For all contributions
- [X] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
Huh, we didn't already have this?
@aiwalter, @mloning, did we not already have this somewhere (under a different name)?

**Comment by fkiraly** [comment]
:Not sure which error you are referring to wrt docstrings. Should I remove some spaces after the 0. in the array?

Go here to see CI test failures for the various builds:

image

**Comment by aiwalter** [comment]
@boukepostma would you mind to add `FunctionTransformer` also to docs? You can search for other transformers in the `.rst` files how to do it.

**Comment by fkiraly** [comment]
@RNKuhns, I think this very much makes sense as part of the public API, a general-purpose transformer creator.

**Pull request merged**
