### PR TITLE
Add example to docstring for each classifier

### LINKED ISSUE #932: [DOC] Add example to docstring
#### Describe the issue linked to the documentation
add an usage Example to the docstring for each classifier

    Example
    -------
    >>> from etc

the best idea would be to do one, run it past us, then duplicate for others.

### PR DESCRIPTION
**Pull request by tabhishek432**
#### Reference Issues/PRs
 Fixes #932 

#### What does this implement/fix? Explain your changes.
 This adds example to docstring for each classifier

#### Does your contribution introduce a new dependency? If yes, which one?

 Nope

#### What should a reviewer concentrate their feedback on?

 I have written example for most of the classifiers but some are left due to some error for which I have created another issue #946 

#### Any other comments?
 Nope

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by tabhishek432** [comment]
Hi @mloning Sir, can you please review this PR. And please also tell me that why this PR failed 4 checks.

**Comment by tabhishek432** [comment]
I also request @ABostrom, @MatthewMiddlehurst, and @jasonlines (as you are the CODEOWNERS) to please review this PR.

**Comment by MatthewMiddlehurst** [comment]
Hi,

Looks like the PR is failing the code quality checks. You can check what it doesnt like by clicking details next to the failing tests (in this case [https://github.com/alan-turing-institute/sktime/pull/949/checks?check_run_id=2813405716](https://github.com/alan-turing-institute/sktime/pull/949/checks?check_run_id=2813405716)).

It seems like it doesn't like the white space before your examples, are you sure its just a new line with no extras?

**Comment by tabhishek432** [comment]
Hello @mloning Sir, I am not getting why my PR is failing these checks could you please tell me the required changes?

**Comment by mloning** [comment]
Hi @tabhishek432 - it's because we have to approve the workflows first, this is something GitHub introduced recently for first time contributors.

**Comment by mloning** [comment]
Hi @tabhishek432 it looks like the code quality checks are failing, please make sure you run pre-commit as described in the contributing guide.

**Comment by tabhishek432** [comment]
@mloning Sir, I didn't make the contributions on my local machine, I simply ran example code on my sktime, and if it worked then, I added it to docstring. I did all of the work on the GitHub website. So, now can I run pre-commit? Also when I run ```pre-commit run --all-files``` in the branch in which I made changes, it gives some kind of other error because of my local machine not working python 2.x version. Is there any other way than pre-commit to know why code quality checks are failing? Also, can I use ``` # noqa``` in the lines so that they pass all checks?

**Comment by aiwalter** [comment]
@tabhishek432 I had a look at the tests and it seems you have to add the outputs in the docstring as well. 
Given this for example:
```python
    >>> clf = BOSSEnsemble(threshold=0.92, max_ensemble_size=100, n_jobs=1, random_state=42)
    >>> clf.fit(X_train, y_train)
    >>> clf.score(X_test, y_test)
```
you would have to make sth like this:
```python
    >>> clf = BOSSEnsemble(threshold=0.92, max_ensemble_size=100, n_jobs=1, random_state=42)
    >>> clf.fit(X_train, y_train)
    BOSSEnsemble(...)
    >>> clf.score(X_test, y_test)
    0.9832
```
or whatever the score output is. You can see this when you have a look at a forecaster, where I did this stuff: https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/arima.py

In case there is randomization in the model so that the score can be slightly different, you have either to set seed or write `score = clf.score(X_test, y_test)` so that there is no output on the console.

**Comment by mloning** [comment]
@tabhishek432 You can look at the logs from the CI to figure out what went wrong, but I suggest to set up a conda environment with pre-commit as discussed in the contributing guide.

**Comment by afzal442** [comment]
hey @tabhishek432, plz have a look here https://github.com/alan-turing-institute/sktime/blob/main/CONTRIBUTING.md#code-quality-checks, make sure you have installed `precommit` before you push the commit. Thanks.

**Comment by TonyBagnall** [comment]
hi @tabhishek432 we are having a tidy of PRs. Are you still working on this, or shall I close it? Fine if you want to keep to open until you have the time to do this, but there is a conflict above. Let us know your plans

**Comment by tabhishek432** [comment]
Hello @TonyBagnall sir, I haven't used pre-commit before pushing these branches, I think that I have to install pre-commit and then try to merge this pull request. So I think you can close this as I have to run pre-commit before making new PR I think.

**Comment by TonyBagnall** [comment]
thanks @tabhishek432, hope you have a go again soon

**Comment by mloning** [comment]
@tabhishek432 you can still use his PR, see here: https://gist.github.com/mloning/6f4b8d412743968af6b2da8b4eaaf2bf

**Pull request closed without merging**
