### PR TITLE
[MNT] Removed hcrystalball from all_extras

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
#2677 

#### What does this implement/fix? Explain your changes.
removed leftover `hcrystalball `stuff

### CODE REVIEW

**Comment by fkiraly** [comment]
oh, we forgot it in there? Sorry.
Generally, release managers go through all comments that mention the major release version number, so there was probably no comment to this effect in `pyproject.toml`

**Review by fkiraly — APPROVED** [review]
👍

**Comment by lmmentel** [comment]
@aiwalter could you also remove this dep from conda recipe?

**Comment by aiwalter** [comment]
@lmmentel how to do that? I searched repo for this name and didnt find another match

**Comment by fkiraly** [comment]
>@fkiraly it was my mistake to not do that in previous PR

Well, it's a community project, so responsibility for mistakes is shared 😄 

>@lmmentel how to do that? I searched repo for this name and didnt find another match

It's a different repo: https://github.com/conda-forge/sktime-feedstock

**Comment by lmmentel** [comment]
I should've mentioned conda is build from a separate repo, here is the file with the recipe https://github.com/conda-forge/sktime-feedstock/blob/3a9022db43b586c4b675093609747bdb7a2fb322/recipe/meta.yaml#L77

**Pull request merged**
