### PR TITLE
Deprecate code tagged in 0.9: MrSEQL, data.io, risf and shapelet

### PR DESCRIPTION
**Pull request by TonyBagnall**
Three deprecations and one refactor for v0.10 release

1. MrSEQL removed
2. functions in utils/data.io moved to datasets/_data.io, data.io removed
3. classification/interval_based/_risf.py removed
4. transformation/panel/shapelet.py moved to contrib

built on top of https://github.com/alan-turing-institute/sktime/pull/1885 because #1885 removed dependencies in notebooks for deprecated code

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks, looks good!

I suppose, by mistake, this PR also contains the refactor of the classification notebook?
Kindly remove that from this PR.

**Comment by TonyBagnall** [comment]
> Thanks, looks good!
> 
> I suppose, by mistake, this PR also contains the refactor of the classification notebook? Kindly remove that from this PR.

it was not a mistake, it was intentional. this sequentially follows the notebook PR which removed references to deprecated classifiers, so was easier like this, otherwise it would conflict

**Comment by fkiraly** [comment]
> it was not a mistake, it was intentional. this sequentially follows the notebook PR which removed references to deprecated classifiers, so was easier like this, otherwise it would conflict

ahhhh, I see.

Can you then please say explicitly in the preamble that this depends on the other PR, which should be merged first? And that the changes to the notebook should be reviewed there?

**Comment by TonyBagnall** [comment]
> > it was not a mistake, it was intentional. this sequentially follows the notebook PR which removed references to deprecated classifiers, so was easier like this, otherwise it would conflict
> 
> ahhhh, I see.
> 
> Can you then please say explicitly in the preamble that this depends on the other PR, which should be merged first? And that the changes to the notebook should be reviewed there?

other one is already merged

**Comment by TonyBagnall** [comment]
> > it was not a mistake, it was intentional. this sequentially follows the notebook PR which removed references to deprecated classifiers, so was easier like this, otherwise it would conflict
> 
> ahhhh, I see.
> 
> Can you then please say explicitly in the preamble that this depends on the other PR, which should be merged first? And that the changes to the notebook should be reviewed there?

the other PR is already in main, I have added a note in the preamble

**Review by fkiraly — APPROVED** [review]
Looks good to me, so happy with this being merged once the tests pass.

**Review by MatthewMiddlehurst — APPROVED** [review]
No issues with the content here.

Not related to this PR really, but alongside some concerns pointed out elsewhere with classification/all/\_\_init\_\_.py, is ESTIMATOR_OVERVIEW.md something we want to continue maintaining?

Both seem rather out of date currently.

**Comment by fkiraly** [comment]
>Not related to this PR really, but alongside some concerns pointed out elsewhere with classification/all/__init__.py, is ESTIMATOR_OVERVIEW.md something we want to continue maintaining?

I noticed the same but did not want to bother Tony with this.
I was going to write issues, already finished the one about `all`: https://github.com/alan-turing-institute/sktime/issues/1928

Re the overview, the current evergreen (and auto-updated) version is here:
https://www.sktime.org/en/stable/estimator_overview.html

I'd like to deprecate the old corpse of `ESTIMATOR_OVERVIEW.md` and add stuff like tags.

**Pull request merged**
