### PR TITLE
[ENH] Classification Benchmarking with kotsu

### PR DESCRIPTION
**Pull request by TNTran92**
Implement classification benchmarking based on kotsu framework.

#### Reference Issues/PRs

Solution to #3319 
Related PR #3218 and PR #2977

#### What does this implement/fix? Explain your changes.

 Added a kotsu-based factory for doing classification benchmarking
#### What should a reviewer concentrate their feedback on?

Unit test is still in progress

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by DBCerigo** [comment]
Great work :) 

A few thoughts if you want them: `git commit --amend --no-edit` is a really handy command, and is `git rebase main -i` and then use the `fixup` option to squash commits into each other for cleaning up your commit history. Once #2977 is merged you could rebase this branch onto main too.

**Comment by TNTran92** [comment]
> 

Thanks for feedback. Let me try that

**Comment by TNTran92** [comment]
Unit test is done. This PR is ready for review

**Comment by TNTran92** [comment]
Closed and moved to #3318

**Pull request closed without merging**
