### PR TITLE
Windows installation guide for sktime development with Anaconda and PyCharm

### PR DESCRIPTION
**Pull request by jasonlines**
A walk-through guide for setting up sktime for development with PyCharm and Anaconda. Also includes examples with pytest and pre-commit within PyCharm

#### Reference Issues/PRs
Contributes to part 2 of #1635 

#### What does this implement/fix? Explain your changes.
Documented example of installing sktime on Windows, specifically using PyCharm and Anaconda with extensive screenshots to guide new users. While PyCharm is used as the IDE, instructions are separated out so that just the environment instructions can be followed (i.e. Section 2) without need for PyCharm, if preferred.  

The notebook is in examples/windows_installation.ipynb and the other files that have been added are screenshots that are used within the notebook. 

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

No code introduced has been introduced but I'm not sure if this is the correct place for it - it may be better in the \docs but I'm not sure how best to include the images and have used a notebook as a first pass. Also, please comment on whether the instructions are informative or if you have suggestions for any changes

### CODE REVIEW

**Review by TonyBagnall — APPROVED** [review]
Maybe @chrisholder could add a vscode version?

**Comment by fkiraly-shell** [comment]
Can we please not merge this at current?

We should not duplicate the location of instructions again, it will confuse users even more, no matter how great the new set of instructions is.

There should be just one set of installation instructions, this PR would create the third set of instructions!

The instructions themselves are ok, although I think they are too pycharm centric.

**Review by fkiraly — CHANGES_REQUESTED** [review]
My main comment: any PR to clean up the installation instructions must use the current location, or make a reasonable change that reduces duplication, redundancy or number of locations.

I am against merging a PR that introduces one more location of installation instructions, and would block this until this is resolved.
We need to keep the user in mind, and user confusion that results from having multiple redundant sets of installation instructions.

I am not against the clarification of instructions in itself, thanks a lot for your contributions, @jasonlines!

**Comment by TonyBagnall** [comment]
@fkiraly where do you think they should go? We can adapt to the structure and you or chris could add vscode. We need more detailed windows instructions, since it is currently a bit of a nightmare with fbprophet

**Comment by fkiraly** [comment]
(hope this makes sense - I really appreciate all the work!)

**Comment by TonyBagnall** [comment]
I think there should be a hierarchy of install instructions in different documents, with basic install <- developer install -< windows dev install, one huge document is too unwieldy.  Not sure it should be a notebook though

**Comment by TonyBagnall** [comment]
we could even have  basic install <- developer install <- windows dev install <- pycharm getting started/vscode getting started

**Comment by fkiraly** [comment]
> @fkiraly where do you think they should go?

There are currently two inconsistent locations with installation instructions:
* installation instructions
* "how to contribute" guide

For an explanation of the duplication and links to the locations, see this issue: https://github.com/alan-turing-institute/sktime/issues/1203

The general location of installation instructions is our docs: https://www.sktime.org/en/stable/
If you want to change those, you need to make changes to the docs folder.

I also suggest to have a coordination meeting tomorrow, since after months of no one working on this we have 4 people working on this simultaneously. Will you be there at the community stand-up?

**Comment by fkiraly** [comment]
> I think there should be a hierarchy of install instructions in different documents, with basic install <- developer install -< windows dev install,

Perhaps, but I'd like to see the proposed structure first because there is a good risk of making things worse. For instance, I don't think having a separate "windows" dev install from a dev install is a good idea, or having instructions that are too specific to one developer IDE (such as pycharm).

**Comment by TonyBagnall** [comment]
I don't know about jay, but I really do not feel strongly about what structure the instructions/doc should have. tbh I do not interface well with the docs at all, I'm not set  up to do so. Lets put this on hold then, we can store the instructions locally, it is primarily to reduce the pain for new people in my group. If you decide what you would like we can work around that, I really don't want to spend an hour talking about it and I have a full day tomorrow.

**Comment by TonyBagnall** [comment]
@fkiraly can we put it in contrib?

**Comment by fkiraly** [comment]
well, if you must... anything goes in contrib.

But what would be much more preferable imo is if we integrate this into the "official" installation instructions which 100s of people a day are reading!
If you or @jasonlines don't like to do that, I'm happy to take this on.

**Comment by TonyBagnall** [comment]
> well, if you must... anything goes in contrib.
> 
> But what would be much more preferable imo is if we integrate this into the "official" installation instructions which 100s of people a day are reading! If you or @jasonlines don't like to do that, I'm happy to take this on.

I think that would be great. Lets put this into contrib for now, and when the "proper" version is done we can remove it. I need to capture this not least for my sanity,  when I next have to do a full windows install I dont want to hav to do it again

**Comment by fkiraly** [comment]
sure - "notebooks" folder in contrib then?

I don't think it will take too long to integrate this into the "right place" in the dev instructions, since we're now actively working on it at my day job (it's a key project dependency so it will be done).

**Comment by jasonlines** [comment]
Hi @fkiraly 

> (hope this makes sense - I really appreciate all the work!)

Yep, absolutely - no problem and I tend to agree with all of the above. 

This level of detail in my notebook is probably more suited for a blog post than the official docs perhaps, but I think it'll be really helpful for getting newcomers started if they're not familiar with setting up and IDE and environment for a project like this (i.e. I have 8 undergrad dissertation students trying to set this up as we speak!), so I'll put it in contrib like @TonyBagnall suggested so we have a record of it. I'm just happy to be contributing in any capacity again, so I'm happy for you to then take this over @fkiraly and then you (and others) can lift/add/delete/ignore any parts of what I've done for the official docs (I'm happy to keep an eye on the docs as they evolve and give any input if you like, but I'd prefer to get stuck into the distances rework code at the mo)

I'll update the code and put this in contrib now

**Comment by fkiraly-shell** [comment]
blog post sounds excellent, actually!
Let's just make sure the instructions are "official" though and work in user testing, since blog posts usually get a lot of traffic, and especially for installation instructions it's potentially dangerous...

**Comment by TonyBagnall** [comment]
a blog with posts like this would be really good, can we set one up?

**Comment by TonyBagnall** [comment]
@jasonlines can then record himself doing it :)

**Comment by jasonlines** [comment]
ok, simple change completed for now with the notebook moving into contrib (as @TonyBagnall suggested) within a notebooks subdir (as @fkiraly suggested) 👍

**Comment by TonyBagnall** [comment]
into contrib with you, on the understanding we will tidy/remove once the proper docs are updated and/or we find somewhere to put it as a blog post

**Review by TonyBagnall — APPROVED** [review]

**Comment by jasonlines** [comment]
hurrah, thanks for your inputs @fkiraly and @TonyBagnall

**Pull request merged**
