### PR TITLE
Implementation of catch22 transformer, CIF classifier and dictionary based clean-up

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
(See PR #317 for previous catch22 discussion)

Separate cBOSS from BOSS. Small clean-up of BOSS, TDE and related documentation/examples/tests.

Implementation of the catch22 transformer and Canonical Interval Forest classifier.  ~~The Windows OS issue from PR #317 has still not been resolved, as such both will raise an OSError if called in Windows. Tests for both will be skipped on Windows also, though im unsure if more will be needed for the general estimator tests.~~ 
Edit: I think Linux may be the broken one with Windows being more faithful actually. The original was tested on MacOS, with neither of the other OS fully replicating it. Putting all this stuff in contrib for now with disclaimers, very messy.

Documentation for the above and interval based classifiers.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by mloning** [comment]
Hi @MatthewMiddlehurst, re linux see (#456), I'm working on it! 

How did you end up skipping the common estimator checks on Windows for catch22?

**Comment by MatthewMiddlehurst** [comment]
Moved it to contrib, where I assume it doesn’t even get checked. 

I have updated the original PR text, but with differences from multiple OS I think it is a bit too unstable for anywhere but contrib.

**Review by mloning — COMMENTED** [review]
It looks like you forgot about an empty folder for `classification/hybrid` when you moved everything to `contrib` - everything else looks good!

**Review by mloning — APPROVED** [review]

**Review by TonyBagnall — APPROVED** [review]
looks good

**Pull request merged**
