### PR TITLE
[MRG] Resolve TypeError issue

### LINKED ISSUE #608: [BUG] TypeError from KNeighborsTimeSeriesClassifier
**Describe the bug**

```Python

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-25-a54f834dd466> in <module>
      2 
      3 knn = KNeighborsTimeSeriesClassifier(n_neighbors=1, metric="dtw")
----> 4 knn.fit(X_train, y_train)
      5 knn.score(X_test, y_test)
      6 

~\Desktop\sktime\sktime\classification\distance_based\_time_series_neighbors.py in fit(self, X, y)
    250             check_array.__code__ = _check_array_ts.__code__
    251 
--> 252         fx = self._fit(X, self._y)
    253 
    254         if hasattr(check_array, "__wrapped__"):

TypeError: _fit() takes 2 positional arguments but 3 were given
```
**To Reproduce**

```python

from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier

knn = KNeighborsTimeSeriesClassifier(n_neighbors=1, metric="dtw")
knn.fit(X_train, y_train)
knn.score(X_test, y_test)
```

**Expected behavior**

Generate the result: `0.55`

**Additional context**

This problem occurs because that `NeighborsBase._fit()` only accept 1 positional argument (only X).

**Versions**
<details>

System:
    python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
executable: c:\users\hephaest\appdata\local\programs\python\python38\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.3.3
   setuptools: 49.2.1
      sklearn: 0.23.2
       sktime: 0.5.1
  statsmodels: 0.12.1
        numpy: 1.19.3
        scipy: 1.4.1
       Cython: 0.29.21
       pandas: 1.1.2
   matplotlib: 3.3.2
       joblib: 0.17.0
        numba: 0.52.0
     pmdarima: None
      tsfresh: 0.17.0
</details>

### PR DESCRIPTION
**Pull request by Hephaest**
#### Reference Issues/PRs

Fixes #608 

#### What does this implement/fix? Explain your changes.

To fix the TypeError.
This problem occurs because that NeighborsBase._fit() only accept 1 positional argument (only X).

#### Does your contribution introduce a new dependency? If yes, which one?

None

#### What should a reviewer concentrate their feedback on?

Whether or not it can generate the correct result. I have already tested it so no worries.

#### Any other comments?

This is a bug fix, so I guess the following PR checklist's most content is not applicable.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi, this is really odd, because it would not work for me with just the one argument! Is it an sklearn version problem? I think sklearn changed the KNN classifier at some point. @mloning do you have any thoughts?

**Comment by Hephaest** [comment]
> hi, this is really odd, because it would not work for me with just the one argument! Is it an sklearn version problem? I think sklearn changed the KNN classifier at some point. @mloning do you have any thoughts?

Dear prof @TonyBagnall,

I think you may get the point, my scikit-learn version is `0.23.2` and the related code in `sklearn\neighbors\_base.py` shown in the following:
```Python
    def _fit(self, X):
        self._check_algorithm_metric()
        if self.metric_params is None:
            self.effective_metric_params_ = {}
        else:
            self.effective_metric_params_ = self.metric_params.copy()

        effective_p = self.effective_metric_params_.get('p', self.p)
        if self.metric in ['wminkowski', 'minkowski']:
            self.effective_metric_params_['p'] = effective_p
      ........
```

**Comment by TonyBagnall** [comment]
I'm using scikit lear 0.24, and if I run _fit(X) I get this error. They have moced the knn classifier and changed the fit method I think. I'll talk to markus about it and get back to you 

image

**Comment by TonyBagnall** [comment]
we might be able to set the tags so that it doesn't require y

image

**Comment by Hephaest** [comment]
> I'm using scikit learn 0.24, and if I run _fit(X) I get an error from scikit learn. They have moved the knn classifier and changed the fit method I think. I'll talk to markus about it and get back to you

Dear prof @TonyBagnall,

Sure, I will close this PR since it still needs further test, but I will keep the issue so your team won't forget where you should consider back-compatibility.

❤️ from Hephaest

**Pull request closed without merging**
