### PR TITLE
[ENH] add `reset` at the start of all `fit`

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds `reset` at the start of all `fit` methods.

This prevents issues with state handling of composites, such as discussed in https://github.com/alan-turing-institute/sktime/pull/2531, especially:

* incorrectly set dynamic tags when calling `set_params` and then calling `fit`
* incorrectly set state variables such as `fh`, `cutoff` (forecasting) or `classes_`, `n_classes_` (classification), in components of composites, when calling `set_params` and then calling `fit`
* incorrectly set `cutoff` and `fh` in components of composites when calling `update_predict` twice (forecasting)

Also adds tests that would fail on `main` (but should work) and are fixed by the above.

Relies on fixes of bugs unmasked by the above:

* https://github.com/alan-turing-institute/sktime/pull/2563

### CODE REVIEW

**Comment by fkiraly** [comment]
@miraep8, do you still have the failing code that we could add as a test here saved somewhere?
I seem to have lost it.

@ltsaprounis, we should also also add the `BaggingForecaster` `update_predict` example to this PR once #2248 is merged.

**Comment by miraep8** [comment]
I *think* this is what you are referring to: 
```
from sktime.forecasting.theta import ThetaForecaster
from sktime.forecasting.var import VAR
from sktime.forecasting.compose import MultiplexForecaster
from sktime.utils._testing.series import _make_series

f = MultiplexForecaster([ThetaForecaster(), VAR()])
X = _make_series()
f.fit(X)
f.set_params(selected_forecaster="VAR")
X_multivariate = _make_series(n_columns=2)
f.fit(X_multivariate)
```

Or potentially some other version of the same?

**Comment by fkiraly** [comment]
Yes, this is it. Thanks

**Comment by fkiraly** [comment]
the two columns 

```python
X = _make_series()
f.fit(X)
```
are superfluous, I think, to test what we want to test

**Comment by miraep8** [comment]
I agree

**Pull request merged**
