### PR TITLE
Added Exploration Data notebook

### PR DESCRIPTION
**Pull request by satya-pattnaik**
Added a Time Series Exploration Notebook, inspired by [the notebook](https://github.com/mloning/intro-to-ml-with-time-series-DSSGx-2020/blob/master/notebooks/02_exploratory_data_analysis.ipynb) by @mloning

### CODE REVIEW

**Comment by fkiraly** [comment]
so, this is nice, but it seems unrelated to `sktime` (the package) - would you mind explaining the purpose of this notebook?

**Comment by mloning** [comment]
@fkiraly, @satya-pattnaik is one of the mentees in the mentorship program and we thought it might be nice to bring in some basic EDA tools into sktime

**Comment by TonyBagnall** [comment]
hi @satya-pattnaik, I'm doing a bit of PR tidying up. Is this still current or can I close it? Happy for you to reopen it later.

**Comment by satya-pattnaik** [comment]
> can I close it?

Yes, I think you can close it as already mentioned it is a bit out of scope.

**Comment by TonyBagnall** [comment]
thanks

**Pull request closed without merging**
