### PR TITLE
DIAGNOSTIC re CI failures: Release/v0.12.1 state

### PR DESCRIPTION
**Pull request by fkiraly**
This is a diagnostic PR to investigate https://github.com/alan-turing-institute/sktime/issues/3103

Purpose: see whether the tests complete at v0.12.1 state.

If the theory is correct that recent migrations in the GitHub cloud are the culprit, this should fail. Otherwise, it would pass.

### CODE REVIEW

**Comment by lmmentel** [comment]
Sorry,  didn't want to convert this to ready. Can someone every back to draft?

**Comment by fkiraly** [comment]
done

**Comment by fkiraly** [comment]
failure on mac, similar to the one reported in #3103. no similar failures were reported before 0.13.0 release.

**Comment by fkiraly** [comment]
and failing again. Could it be different by time of day??

**Pull request closed without merging**
