### PR TITLE
Distance based classification package refactor

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Refactor along the lines of #1146 for the distance_based package (PF, EE, and ShapeDTW). Adds tests for these classifiers as well.

I have left KNeighborsTimeSeriesClassifier mostly alone. It requires changes beyond what I am willing to look into for this PR. In its current fit it calls a different version of self._fit inherited from sklearn NeighborsBase.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
so is this failure due to a CI bug? I seem to remember seeing this kind of failure before when refactoring. Its saying it cannot see KNeighborsTimeSeriesClassifier, but it is in init 
image

**Comment by TonyBagnall** [comment]
I had hoped that the bug would be resolved by rerunning the tests, but it isnt. I think this is a problem with the testing, not your code.

**Comment by TonyBagnall** [comment]
I am going to try recreate this bug on a branch, its annoying

**Comment by TonyBagnall** [comment]
something going on with the stump. I actually think we should make "ProximityStump" and "ProximityTree" private. I see no reason to use them independently of ProximityTree.

**Comment by TonyBagnall** [comment]
error is 
    value = getattr(self, key)
AttributeError: 'ProximityStump' object has no attribute 'get_exemplars'

**Comment by TonyBagnall** [comment]
and there is even an issue, google object has no attribute 'get_exemplars' gives this, lol  https://github.com/alan-turing-institute/sktime/issues/598

**Review by chrisholder — APPROVED** [review]

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
