### PR TITLE
Refactoring CIF classifier to match the template

### PR DESCRIPTION
**Pull request by kejsitake**
#### Reference Issues/PRs

Partially handles #1146. TSC refactoring for Canonical Interval Forest Classifier (_cif) classifier

#### What does this implement/fix? Explain your changes.

- Turned the public methods into private
- Changed the name of the capabilities dictionary to _tags.
- Removed the checks from the private version
- Checked that all tags already were already in the _tag registry

#### Does your contribution introduce a new dependency? If yes, which one?

No
#### What should a reviewer concentrate their feedback on?

Please look at the changes and let me know if I should make any other edits.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
Changes made in #1269 also. Seems a bit difficult getting PR's merged at the moment though.

**Comment by TonyBagnall** [comment]
hi @kejsitake thanks for the pull request, but I think this has been done in #1269. There are other classifiers that still need to be updated, if you still want to do one/some I'll take a look which need doing and prioritise your PR

**Comment by fkiraly** [comment]
@kejsitake, many apologies for this situation, you made a great contribution here - we should have been better organized :-(

I've now made a checklist of the classifiers, the proposed workflow is to post there before you start working on a refactor.
There are plenty of classifiers to pick up still!

**Comment by kejsitake** [comment]
Thank you for the help! I will pick one/some of the other classifiers!

**Pull request closed without merging**
