### PR TITLE
Add Class for Composite Distance

### PR DESCRIPTION
**Pull request by abheesht17**
#### What does this implement/fix? Explain your changes.

Resolves https://github.com/alan-turing-institute/sktime/issues/1888

#### Does your contribution introduce a new dependency? If yes, which one?
N.A.

#### What should a reviewer concentrate their feedback on?

@fkiraly:
 
I'm a bit confused about how I should organise the code for this. There are two scenarios I can think of:
 
1. I thought we had to do something like this:
Make a class `CompositeDistance`, subclass of `NumbaDistance`. However, since `NumbaDistance` is an abstract class, I will have to implement `_distance_factory(x: np.ndarray, y: np.ndarray, ...)`. The issue with this is that I won't be passing numpy arrays, I will pass a dictionary (for example, `{"x1": np.array([1,2,3]), "x2": np.array([4,5,6]}`). So, I'm not sure if I should inherit from `NumbaDistance`. I can change the definition for `_distance_factory` in `NumbaDistance` to `_distance_factory(x: Union[np.ndarray, Dict[str, np.ndarray]], y: Union[np.ndarray, Dict[str, np.ndarray]])` and proceed, but not sure if I should do this. 
2. This is what I've done:
    Make a class `Composite Distance`, with `__call__`. Example usage:

```
>>> import numpy as np 
>>> from sktime.distances.composite import CompositeDistance
>>> cd = CompositeDistance(metrics=["euclidean", "squared"], weights=[0.4,0.6], variables=[["x1", "x2"], ["x3"]])
>>> d1 = {"x1": np.array([1,2]), "x2": np.array([3,4]), "x3": np.array([5,6])} 
>>> d2 = {"x1": np.array([2,3]), "x2": np.array([4,5]), "x3": np.array([6,7])} 
>>> cd(d1, d2)
2.331370849898476
```

#### Any other comments?
I haven't added doc-strings and unit tests yet. Let me know if what I've done is the correct way, and I'll add doc-strings and UTs.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thank you for your work!

The main issue with your distance is that you did not follow the extension template that I linked in #1888 - for instance, you should be inheriting from one of the base classes.
You should be implementing `_transform` and not override `__call__`.

**Comment by abheesht17** [comment]
> Thank you for your work!
> 
> The main issue with your distance is that you did not follow the extension template that I linked in #1888 - for instance, you should be inheriting from one of the base classes. You should be implementing `_transform` and not override `__call__`.

Ah, I see. I was trying to make it a subclass of the `NumbaDistance` class, but couldn't find a way since `_distance_factory` takes numpy arrays, and not dictionaries. Great, I'll go through the extension template and update the PR. Thanks!

**Comment by fkiraly** [comment]
@abheesht17, are you still working on this?

**Comment by fkiraly** [comment]
closed due to inactivity

**Pull request closed without merging**
