### PR TITLE
pyOD stream anomaly detector adapter

### PR DESCRIPTION
**Pull request by fkiraly**
This is an adaptation of @satya-pattnaik's stream anomaly detector adaptor to the `pyOD` interface, to the base template extension in #1021. This is conditional on #1021.

This is just an interface adaptation of the already existing PR #839 by @satya-pattnaik.

Some minor added features:

* ability to choose annotation format - `sparse` (only outlier time points) vs `dense` (same length output as annotated series)
* ability to choose annotation label - yes/no (calls `pyOD` `predict` interface point) vs outlier score (calls `pyOD` `decision_score` interface point)

### CODE REVIEW

**Comment by fkiraly** [comment]
pinging @satya-pattnaik

**Comment by fkiraly** [comment]
hm, the tests are failing since `pyod` is not a dependency, but we'd need it in testing - how to solve this?

**Review by mloning — COMMENTED** [review]
Let me review this one once #1021 has been merged.

**Comment by fkiraly** [comment]
this is now integrated into #1021 for ease of development and review.

**Pull request closed without merging**
