### PR TITLE
[ENH] `Table` scitype and refactor of `convert` module

### PR DESCRIPTION
**Pull request by fkiraly**
This PR refactors the `datatypes` module and adds a `Table` scitype, details below.

This is in anticipation of two things:
* refactoring and extension of transformer tests
* moving conversions in classifiers to `datatypes`, my contribution to https://github.com/alan-turing-institute/sktime/pull/1594

The changes to the `datatypes` module:
* the `test_convert` tests are refactored - the six loops over fixtures (from, to, fixture, etc) are moved to `pytest_test_generate` where it belongs. This should make the code much easier to read.
* similarly, the individual conversions now appear as individual fixture combinations, which should make debugging much easier
* a `Table` scitype is added. The mtypes are `pandas` `DataFrame`, `numpy1D`, and `numpy2D`. This will be useful for checks and conversions as follows: to check the output of transformers with a `Primitives` output - this must be `DataFrame`; to check the output of classifiers - this must be `numpy1D`; for classifiers to accept the other two mtypes in fitting.
* a metadata field `has_nans` which checks whether the container has any nans
* for the `nested_univ` mtype, nan and equal spaced checks use @TonyBagnall's `_nested_dataframe_has_nans` and `_nested_dataframe_has_unequal` from #1594

### CODE REVIEW

**Comment by fkiraly** [comment]
@chrisholder, @MatthewMiddlehurst, @TonyBagnall, would appreciate your review, as this will be a dependency of the classifier conversions.

@Lovkush-A, you might also be happy over how the `convert` tests have been refactored.

**Comment by fkiraly** [comment]
quick question, @TonyBagnall, @chrisholder, @matthewmiddlehusrt:
in #1594, do you have a method that checks whether `nested_univ` data containers have nans?
If so, kindly point me to it, since I don't want to re-implement this...

**Comment by fkiraly** [comment]
> If so, kindly point me to it, since I don't want to re-implement this...

Found and added.

**Review by TonyBagnall — APPROVED** [review]
Looks ok to me, but @chrisholder is better placed to comment, especially on the NaN checking

**Comment by fkiraly** [comment]
Ultimately, we should whether the `check` functions correctly recover properties of a fixture.

That is, add functionality to the `examples` modules to specify what properties the fixtuers have, and then write a test to check.
Each mtype/property combination should appear (at least) twice, once with the property positive, and once as a negative.

**Comment by fkiraly** [comment]
appveyor timed out, but seems fine. Merging so I can get to work more easily on dependencies.

**Pull request merged**
