### PR TITLE
[DOC] extended & cleaned docs on dependency handling

### PR DESCRIPTION
**Pull request by fkiraly**
This PR moves the "dependencies" section out of "coding standards" (where it does not really seem to fit) and extends it with instructions and explanations of different kinds of dependencies.

Other, minor changes:
* removes the duplicated "deprecation" section from "coding standards" (this is duplicated on the more recent "deprecation" page)
* fixes a link to the continuous integration page, which linked to a random position on the "coding standards" page for some reason

### CODE REVIEW

**Comment by GuzalBulatova** [comment]
Looks all good to me! ReadTheDocs is failing though

**Comment by fkiraly** [comment]
> Looks all good to me! ReadTheDocs is failing though

That's the sporadic failure, imo nothing to do with the content. Will restart to make sure.

**Comment by fkiraly** [comment]
readthedocs runs now, @GuzalBulatova

**Review by GuzalBulatova — APPROVED** [review]
Looks ready to me!

**Pull request merged**
