### PR TITLE
Release v0.9.0

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
https://github.com/alan-turing-institute/sktime/milestone/9

#### What does this implement/fix? Explain your changes.
- [x] update README
- [x] update version
- [x] remove deprecated functionality
- [x] update all contributors
- [ ] update changelog

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
In response to @mloning's slack post that he plans to do this tomorrow morning.

I think this is too rushed! Let's do at least one day of feature freeze, as we have agreed.

There are further a number of fixes to bugs in the milestone
https://github.com/alan-turing-institute/sktime/pulls?q=is%3Aopen+is%3Apr+milestone%3Av0.9.0
which haven't gone in yet. They are done, just need to be quickly looked at and merged.

I am *against* releasing without 1 day feature freeze and without having gone at least through the bugfix PRs.

**Comment by fkiraly** [comment]
FYI @lmmentel - in particular I don't think the 0.9.0 release should not happen without *all* tests passing.

Currently, due to some problem with CI/CD that we don't fully understand, 5 tests fail without the CI/CD noticing (@lmmentel, can you please confirm this?).
In line with "all tests must pass" policy, we need to fix those before 0.9.0.

**Comment by lmmentel** [comment]
> FYI @lmmentel - in particular I don't think the 0.9.0 release should happen without _all_ tests passing.
> 
> Currently, due to some problem with CI/CD that we don't fully understand, 5 tests fail without the CI/CD noticing (@lmmentel, can you please confirm this?). This can be checked by local testing. In line with "all tests must pass" policy, we need to fix those before 0.9.0. Those fixes are part of the unreviewed PR in the milestone.

I rerun the test suite locally using this branch and a fresh venv and all seems good:

```
================================================================== 9075 passed, 546 warnings in 618.44s (0:10:18) ===================================================================
```

**Review by fkiraly — APPROVED** [review]
approving now (as per discussion in slack), priority bugfixes are merged, other items solved or moved to next release.

**Pull request merged**
