### PR TITLE
Add back missing bibtex reference to classifiers

### LINKED ISSUE #447: [DOC] classifiers missing bibtex reference
#### Describe the issue linked to the documentation

The following classifier miss the bibtex reference to the paper for the algorithm:

- ColumnEnsembleClassifier in classification/compose/_column_ensemble.py

- TimeSeriesForestClassifier in classification/compose/_ensemble.py

- TemporalDictionaryEnsemble in classification/dictionary_based/_tde.py

- ProximityTree in classification/distance_based/_proximity_forest.py

- ShapeDTW in classification/distance_based/_shape_dtw.py

-  KNeighborsTimeSeriesClassifier in classification/distance_based/_time_series_neighbors.py 

#### Suggest a potential alternative/fix
add back the bibtex reference

### PR DESCRIPTION
**Pull request by whackteachers**
#### Reference Issues/PRs

Follow up Fixes #447 

#### What does this implement/fix? Explain your changes.

add missing Bibtex reference to the classifiers without any reference
fix some minor syntax issues in the existing Bibtex
fix indent of some existing references
add links to paper under the references
#### Does your contribution introduce a new dependency? If yes, which one?
n.a

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by mloning — COMMENTED** [review]
Hi @whackteachers, thanks for adding the references. 

Could we add them under a References header more or less following the [numpy doc string guide](https://numpydoc.readthedocs.io/en/latest/format.html), something like this:

```python
"""
TimeSeriesForestClassifier

...

References
-----------
<reference>
"""
```

**Comment by whackteachers** [comment]
oh I thought we don't need to as most of the references are like that

**Comment by mloning** [comment]
@whackteachers I see, I think we agreed on the numpy doc string format but understand that this isn't always followed, let me know if you have the time to quickly fix this, otherwise happy to merge without it and we can fix it later.

**Review by TonyBagnall — APPROVED** [review]
looks good Jason, thanks for doing that

**Review by mloning — APPROVED** [review]

**Pull request merged**
