### PR TITLE
Transform classifiers

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Implements some of the classifiers from #1063.

- TSFreshClassifier
- MatrixProfileClassifier

Refactors SignatureClassifier and Catch22ForestClassifier into a new feature_based package alongside the two new pipeline classifiers.

Quite a lot of documentation changes that were required due to the new tests also.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
doc-quality test seems to be failing because it cant check the old location of some refactored files?

**Comment by fkiraly** [comment]
Hm, shouldn't @jambo6 be automatically be added as Pr reviewer when it is about signature methods? Why did that not happen?

**Comment by MatthewMiddlehurst** [comment]
This also happened with #1084 where Patrick was not notified as far as I am aware, I also could not manually add him as a reviewer.

Do people have to be added to the repository to be notified and leave reviews maybe?

**Review by mloning — COMMENTED** [review]
Hi @MatthewMiddlehurst, for the deprecations, we haven't really agreed on the details in terms of how long we keep them in and so on, but for a simple example how to raise a deprecation warning see: https://github.com/alan-turing-institute/sktime/blob/d296230155d871fe66a973cab942e20f63173516/sktime/forecasting/compose/_reduce.py#L764

**Review by TonyBagnall — COMMENTED** [review]
I dont think you should default to random forest for Matrix Profile, since MP is a series to series conversion, I think default to rocket, or 1-NN as I did in the paper.  I might call it pipeline classifiers rather than feature_based? But then you could argue STC goes in there, The best name I have thought of so fat is unsupervised transforms, but its not very informative.

**Comment by MatthewMiddlehurst** [comment]
The deprecated decorator only works for functions, so I just put it on the \_\_init__ for both classes. I'm sure that's the intended usage.

Changed the MatrixProfileClassifier base estimator. The matrix profile I used is in the panel transformation package, through now that i look there is a second matrix profile in series transformations. Not sure what's up with that.

**Review by TonyBagnall — APPROVED** [review]
this is a refactoring to reduce proliferation of subpackages prior to a new release of hive-cote

**Comment by MatthewMiddlehurst** [comment]
The remaining doc-quality test failures are from deprecated or deleted files. This should be fine to go in if there are no changes or objections.

**Pull request merged**
