### PR TITLE
Multivariate regression

### PR DESCRIPTION
**Pull request by SebasKoel**
Draft PR

Started working on adding multivariate regression support
Not finished yet

### CODE REVIEW

**Comment by fkiraly** [comment]
Thanks!

Does this relate to an issue?

If not, would you be able to outline what you are planning? 
We may also want to align on an interface design first, to avoid incompatibility between workstreams.

We have a tentative API design proposal for multivariate:
https://github.com/alan-turing-institute/sktime/wiki/Design-proposal:-forecasting-API-re-work-including-support-for-datetime-indices
(but we haven´t started with implementation yet, since the design still needs hammering out)

**Comment by mloning** [comment]
@fkiraly @SebasKoel got involved with sktime during the PyData sprint and is now in the mentorship programme and mentored by @big-o. 🙂

**Comment by fkiraly** [comment]
Ah, nice to make your acquaintance, and welcome onboard!
:wave:
(not sure whether I saw you on slack)

**Comment by mloning** [comment]
Please merge into `master` (see #360)

**Comment by mloning** [comment]
Closed in favour of #390

**Pull request closed without merging**
