### PR TITLE
[ENH] empirical and conformal probabilistic forecast intervals (Stankeviciute et al, 2021)

### PR DESCRIPTION
**Pull request by fkiraly**
This PR adds a prediction interval wrapper that adds simple empirical and conformal forecast intervals based on Stankeviciute et al, 2021. Also includes more naive empirical/frequentist strategies.

The estimator implements the algorithm as a wrapper which can add the intervals to any forecaster, not just the special case presented there for RNN.

### CODE REVIEW

**Comment by fkiraly** [comment]
FYI @IlyasMoutawwakil, I based this partially on your code.
I wonder whether:

* we could move the joint functionality somewhere, but where?
* whether the window/aggregation computation would not be better located in `_fit`

**Comment by bethrice44** [comment]
I've been using this locally and have made a couple of changes:

1. Moved `_compute_sliding_residuals` to it's own function like in `NaiveVariance`
2. Added early computation of residuals matrix like in `NaiveVariance`
3. Added option to pass a `sample_frac` argument at initialisation to speed up computing the residuals matrix
4. I found an issue where `forecaster.predict_residuals` doesn't always return a series, so assigning it to the residuals matrix can fail here: 

```
residuals_matrix.loc[id] = forecaster.predict_residuals(y_test, X_test)
```

Hot fix was to do 
```
residuals_matrix.loc[id] = forecaster.predict_residuals(y_test, X_test).iloc[:,0]
```
but there is probably a better way.

Shall I push these changes to the branch for review? I am set up for development but am yet to contribute.

**Comment by fkiraly** [comment]
>Shall I push these changes to the branch for review? I am set up for development but am yet to contribute.

Oh, that's really nice!!

I wanted to make the same changes, but this has constantly been "outcompeted" by more important maintenance related tasks and my day job.

Would be really great if you could open a separate PR, branching off this PR!
Target of your PR can be this branch, or `main`, whichever is more convenient for you, just make sure it branches off this one.

**Comment by fkiraly** [comment]
> I wanted to make the same changes,

Well, not 3 or 4. These are genuine additions and new, great ideas. I meant, I wanted to do 1 and 2, and did not have the idea or intent to do 3 or 4.

**Comment by bethrice44** [comment]
I have opened a PR from this branch [here](https://github.com/alan-turing-institute/sktime/pull/2704)

**Comment by fkiraly** [comment]
@bethrice44, as said on there: thanks a lot for the additions!

I have unfortunately messed up my advice to how we merge both, the problem is that CI/CD gets triggered only for PR to `main`, not for PR to other branches. That does not allow us to look at your additions separately, if you PR to my other branch.

I would hence, kindly, ask you to repeat the PR, this time to `main`. The CI/CD will then trigger properly.

**Pull request merged**
