### PR TITLE
[ENH] Change `_set_fh` to a `_check_fh` that returns `self._fh`

### PR DESCRIPTION
**Pull request by fkiraly**
This implements the change suggested in issue #1776:

Main change is changing the `_set_fh(fh)` method to `_check_fh(fh)` which returns `self.fh` (the coerced/validated `ForecastingHorizon`), instead of no return.

Further additions concern docstrings which clarify the functionality of `_check_fh` and the `fh` attribute.

### CODE REVIEW

**Comment by fkiraly** [comment]
FYI @kejsitake.

I added you as a potential reviewer, @SveaMeyer13, since this is arising from changes you originally added (see #1776).

**Review by chrisholder — APPROVED** [review]
Code looks fine someone who knows what this actually does and impact should also review :joy:

**Comment by fkiraly** [comment]
@aiwalter, any opinions?

**Comment by fkiraly** [comment]
In #1776, @kejsitake said

> I agree that this is counterintuitive and _check_fh makes more sense.

so I'll count this as "someone who knows what this actually does and impact" for the purpose of your statement, @chrisholder.
Though I'll give it a few more days so core devs can have a look if they want.

**Comment by fkiraly** [comment]
@chrisholder, I had to update this since `predict_residuals` was added since the PR opened, which had another reference to `_set_fh`

**Review by kejsitake — APPROVED** [review]
This looks good to me, for the following two reasons:
- I tested the existing code and it looks like `set_fh(fh)` modifies `self._fh` without returning the Forecasting Horizon, making it confusing for the user to keep track of which fh to use next(fh passed to the function or self.fh).
- I also think that it is more consistent to have a returning value, given that `check_alpha` has the same behaviour.

Regarding code, I agree with @chrisholder that it looks okay.

**Pull request merged**
