### PR TITLE
[ENH] upgrade codecov uploader and cleanup coverage reporting

### PR DESCRIPTION
**Pull request by tarpas**
#### What does this implement/fix? Explain your changes.

* addresses the deprecation of Codecov Bash Uploader: https://docs.codecov.com/docs/about-the-codecov-bash-uploader#deprecation-notice-and-schedule
* fixes the partial misconfiguration of codecov uploader https://github.com/alan-turing-institute/sktime/runs/5817665318?check_suite_focus=true#step:9:37
* fixes covergepy warnings: https://github.com/alan-turing-institute/sktime/runs/5807142605?check_suite_focus=true#step:7:12
* `make test` by default doesn't measure coverage but allows it via PYTESTOPTIONS variable
* uses `pytest -n auto`, which seems to work reliably. GHA MacOS runners have 3 core CPUs available, so that should speed up these builds

#### What should a reviewer concentrate their feedback on?
Check if code coverage got uploaded as it should. See if there are unwanted differences in the build or tests in general.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [X] The PR title starts with either [ENH], [DOC] or [BUG] indicating wether the PR topic is related to enhancement, documentation or bug

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by tarpas** [comment]
I'm working on adding https://github.com/tarpas/pytest-testmon to sktime. In my tests I had great results with it, congrats for the nice test suite! 
This PR is a pre-requisite. testmon doesn't support --pyargs :/ 
Adding testmon will come in a second PR. I have limited capacity to work on this so I wanted to let you know about my work, so that we don't duplicate effort .
@fkiraly @lmmentel

**Comment by tarpas** [comment]
> Previously we've had issues with pytest picking up source from `./sktime` rather than from the `sktime` package installed at `PYTHONPATH`. That was when we had compiled extensions present but I'm not sure if we don't need to a bit of caution here.
Hi Lukasz, I saw you did the testdir, that's why I notified you. You're right, ./sktime and --pyargs sktime are different. ./sktime picks up around 500 tests more than --pyargs sktime. I admit in CI it makes more sense to test with --pyargs. 
I'm trying to fix this PR so that it uses --pyargs. 
But unfortunately testmon doesn't support --pyargs yet. I was testing with `pytest --testmon ./sktime` and it was doing great. It was selecting very small subset of tests and hitting the same test failures as the original build without testmon. If no new problems arise, do you think you could live with testing ./sktime until testmon supports it? As said the build results were equivalent. @lmmentel @fkiraly 

It would be beneficial for local development experience to actually fix the tests so that ./sktime and --pyargs sktime pick the same tests. 

Also some base import always takes 2 minutes, whenever you need to execute even just one simplest test. I assume it's a bug and could be fixed with not much effort.

**Comment by tarpas** [comment]
@lmmentel @fkiraly @TonyBagnall could you please have a look? The changes are fairly straightforward and seem to work fine.

**Review by lmmentel — APPROVED** [review]
:+1:

**Comment by lmmentel** [comment]
Thanks @tarpas!

**Pull request merged**
