### PR TITLE
[DOC] Update Time series forest regression docstring

### PR DESCRIPTION
**Pull request by thayeylolu**
**User Guide: Regressor**

Task
- [x] I understand the implementation of TimeSeriesForestRegressor Class
- [x] I have explained how time series data are different from cross sectional data
- [x] I have illustrated this difference with an example
- [x] I have created another example that demonstrated how to train _Time Series Forest Regressor (tsf)_ to predict continuous target variable(s) from time series .
- [x] I have done model evaluation

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

### CODE REVIEW

**Comment by thayeylolu** [comment]
https://github.com/alan-turing-institute/sktime/issues/361#issuecomment-814115680

**Comment by mloning** [comment]
@thayeylolu thanks for the PR! There are a lot of changed files in this PR, probably because you applied Black formatting to all files in the repo. Could you see if you can undo that and only include your changed files? The CI checks will only check changed files. 

Let me know if you need help with any of this.

**Comment by thayeylolu** [comment]
@mloning  I have done as your suggested. Thank you

**Review by mloning — DISMISSED** [review]
Hi @thayeylolu it seems like most of the user guide section was already discussed in the docstring. In terms of the content, the docstring seems to be the better place. So I reverted your changes to the user guide and updated the docstring instead. Hope that's ok!

**Review by mloning — APPROVED** [review]

**Pull request merged**
