### PR TITLE
post-fix merge error in #967

### PR DESCRIPTION
**Pull request by fkiraly**
This is a post-fix to #1118 to make this consistent with changes introduced in #1068.

I.e., removes the new instance of `_has_tag` from #967 in favour of `_all_tags`, as done in #1068 with the other instance in the same class.

### CODE REVIEW

**Comment by mloning** [comment]
`_has_tag` is used elsewhere in the library too, that's why I thought it may be best to refactor that everywhere once we agree on the new interface points for the tag system. 

The PR breaks because of the default setting if the tag is missing.

**Comment by fkiraly** [comment]
>The PR breaks because of the default setting if the tag is missing.

Yes, we didn't fix it for transformers...

**Comment by fkiraly** [comment]
so let's just do this later.

**Comment by fkiraly** [comment]
at least I was wise enough to merge your PR and not mine (it wasn't tested).

**Comment by fkiraly** [comment]
no longer needed since replaced by `get_tags` since then.

**Pull request closed without merging**
