### PR TITLE
[BUG] fixing click/black incompatibility in CI

### LINKED ISSUE #2354: [BUG] code-quality CI fails due to incompatibility of click with black
`code-quality` checks in CI are failing due to an incompatibility ot `click` with the newest `black` version.
Error traceback is
```
 Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo6qt55n6c/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/.cache/pre-commit/repo6qt55n6c/py_env-python3/lib/python3.10/site-packages/black/__init__.py", line 1367, in patched_main
    patch_click()
  File "/home/runner/.cache/pre-commit/repo6qt55n6c/py_env-python3/lib/python3.10/site-packages/black/__init__.py", line 1353, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repo6qt55n6c/py_env-python3/lib/python3.10/site-packages/click/__init__.py)
```

A suggested workaround is pinning `click`, see https://github.com/alan-turing-institute/sktime/pull/2353.

This temporary fix is attempted in https://github.com/alan-turing-institute/sktime/pull/2353.
We can close this issue once the pin/fix is removed again.

### PR DESCRIPTION
**Pull request by fkiraly**
`code-quality` checks in CI are failing due to an incompatibility ot `click` with the newest `black` version.
This bumps `black` to 22.3.0 for both code and notebook checks.
It also removes the pin on `click`, in an attempt to fix #2354.

This PR follows the fix suggested in
https://github.com/psf/black/issues/2964

### CODE REVIEW

**Comment by lmmentel** [comment]
Could you bump black to `black==22.3.0`? for details see https://github.com/psf/black/issues/2964

**Comment by fkiraly** [comment]
ok, did that and removed the click pin

**Comment by aiwalter** [comment]
I think code quality is not failing anymore? see e.g. #2349

**Review by lmmentel — APPROVED** [review]
:+1:

**Comment by aiwalter** [comment]
I think  we dont need this PR anymore, no? @lmmentel

**Comment by lmmentel** [comment]
This bumps black to the version that should have a fix so it's good for it to go in.

**Comment by fkiraly** [comment]
>I think we dont need this PR anymore, no? @lmmentel

It's the permanent fix, the earlier fix was only temporary.
Well, until the next version breaks it...

**Pull request merged**
