### PR TITLE
master to main conversion in docs folder closes #644

### LINKED ISSUE #644: Rename master branch to main
I suggest to rename our current `master` branch to the new GitHub standard name `main`.  

More details on why and what has to be done here: https://github.com/alan-turing-institute/the-turing-way/issues/1210

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
#### Reference Issues/PRs
Fixes #644 

#### What does this implement/fix? Explain your changes.

I have changes occurrences of ```master``` into ```main``` in the files in the docs but not changed the CIs inside .github folder but in some files like which has external documentation links and which are not part of sktime I have kept them as it is

#### Does your contribution introduce a new dependency? If yes, which one?

No my contribution is free of any new dependency

#### What should a reviewer concentrate their feedback on?

Please see if anything more needed to be changed , in some .py files like ```setup.py``` there was one occurrence of master in the line 5 but it was a documentation link of external documentation so I have not changed that and like this I haven't changed in some other one or two places so please see if there is any more change needed or not.

#### Any other comments?

No

#### PR checklist

NA

##### For all contributions

- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by mloning — COMMENTED** [review]
Thanks @ayan-biswas0412 - this looks all good to me. Could you also check the `.rst` and `.md` files in the root directory of the repo (README etc)?

**Comment by ayan-biswas0412** [comment]
> Thanks @ayan-biswas0412 - this looks all good to me. Could you also check the `.rst` and `.md` files in the root directory of the repo (README etc)?

should I make the changes and push the commits in this PR ?? in that files also

**Comment by mloning** [comment]
Yes let's do it in this PR too! 

Once all references in the docs are changed and everything still passes, we can change the CI.

**Comment by ayan-biswas0412** [comment]
> Yes let's do it in this PR too!
> 
> Once all references in the docs are changed and everything still passes, we can change the CI.

yah sure I will do that

**Comment by mloning** [comment]
@ayan-biswas0412 there seems to be some issue with linting, could you take a look please?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 there seems to be some issue with linting, could you take a look please?



> @ayan-biswas0412 there seems to be some issue with linting, could you take a look please?

is there any tool to detect this locally ? actually syntax wise this is fine this is a problem of code styling I think

**Comment by ayan-biswas0412** [comment]
@mloning I have solved the lint errors please review

**Comment by ayan-biswas0412** [comment]
@mloning all the checks have been passed now and the master to main conversion is ready for now I think

**Comment by mloning** [comment]
Okay great, thanks @ayan-biswas0412. I'll see if I can rename the branches over the next couple of days!

**Review by mloning — APPROVED** [review]

**Comment by mloning** [comment]
@ayan-biswas0412 thank you again for working on this! I've now renamed the branch and merged this PR!

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 thank you again for working on this! I've now renamed the branch and merged this PR!

Thank you for merging this 🥰

**Comment by mloning** [comment]
I took me a bit longer than expected ...

**Pull request merged**
