### PR TITLE
Refactor mrseql

### PR DESCRIPTION
**Pull request by lnthach**
#### Reference Issues/PRs

See #257 

#### What does this implement/fix? Explain your changes.

Refactor Mr-SEQL to pass all the tests for estimators.
Add multivariate time series support. MrSEQLClassifier can classify multivariate time series now.
Update notebook example.

### CODE REVIEW

**Comment by mloning** [comment]
Hi @lnthach, thanks for the fixes, looks good to me. Let me know when you're all done so that I can merge it 🙂

**Comment by lnthach** [comment]
Thanks @mloning . Sorry for the late response. Yes it's good to go from my side.

**Comment by mloning** [comment]
No worries, thanks for the fixes! 🙂

**Comment by mloning** [comment]
Hi @lnthach, 

I've noticed that the `test_mrseql_on_gunpoint` now takes considerably more time. Any idea why? 

Before your changes, it ran in roughly [30 secs](https://travis-ci.com/github/alan-turing-institute/sktime/jobs/331493783), not it needs [240 secs](https://travis-ci.com/github/alan-turing-institute/sktime/jobs/341673634).

**Comment by lnthach** [comment]
Hi @mloning ,

Many thanks for pointing that out. It appeared that the way I sliced the dataframe wasn't optimal. I have implemented the fix for this issue. Can I make my pull request on dev ?

**Comment by mloning** [comment]
Yes please! Thanks @lnthach

**Pull request merged**
