### PR TITLE
[ENH][BUG] Testing vectorization for forecasters, plus various bugfixes

### PR DESCRIPTION
**Pull request by fkiraly**
This PR contains a simple test for vectorization via `BaseForecaster`.

This PR also contains the following change:
* relaxes the `pd-multiindex` mtype so the multiindex levels do not need to have particular names (from `"instances"` and `"timepoints"`)

A number of bugs were uncovered, these were fixed:
* the `_nested_dataframe_has_nans` utility function did not work for nested data frames where index was not integer starting at zero - fixed replacing `loc` indexing by `iloc`. Relies on PR #2216 where this is separated out.
* a number of bugs around vectorization in `BaseForecaster` - it did not actually work.

FYI @TonyBagnall about the first bug - I think you have seen it before?
FYI @danbartl about the second bug. Vectorization now works as intended, at least for `Panel` input. Will add the `Hierarchical` test once @ltsaprounis's data generator is merged.

### CODE REVIEW

**Comment by ltsaprounis** [comment]
> FYI @danbartl about the second bug. Vectorization now works as intended, at least for `Panel` input. Will add the `Hierarchical` test once @ltsaprounis's data generator is merged.

@fkiraly are you talking about #2093? That's already merged!

**Comment by fkiraly** [comment]
ah, thanks for pointing this out, @ltsaprounis, I´ll add a test using that

**Comment by fkiraly** [comment]
>ah, thanks for pointing this out, @ltsaprounis, I´ll add a test using that

Done, thanks for the useful utility!

**Comment by fkiraly** [comment]
@ltsaprounis, windows tests are failing with some problem related to `freq` of the multiindex.
https://github.com/alan-turing-institute/sktime/issues/2194
Really strange - do you have an idea? Could this be related to `_make_hierarchical`?

**Comment by TonyBagnall** [comment]
there is a lot of commented out code left in

**Comment by fkiraly** [comment]
Contains some urgent bugfixes to the hierarchical forecasting functionality.
As discussed in core dev channel, mergency-merging to avoid blockage of the workstream.
Topic & note was scheduled for Fr dev meeting.

Kindly unmerge if not happy with this.

**Pull request merged**
