### PR TITLE
[DOC] reformatted the documentation structure

### PR DESCRIPTION
**Pull request by amrith-shell**
#### Reference Issues/PRs

This is related to issue #1635 , also related #1448 

#### What does this implement/fix? Explain your changes.

This pull request addresses the reformatting of the documentation structure to follow the following hierarchical structure  
documentation design

#### Does your contribution introduce a new dependency? If yes, which one?
No new dependency introduced.

#### What should a reviewer concentrate their feedback on?
- [ ] Review the documentation structure
- [ ] Ensure that text has not been deleted

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by mloning — COMMENTED** [review]
Hi @amrith-shell and thanks for the work on this! 

I had a first look, here are some comments:
* I think we still want Installation to be under Documentation
* There is also a short installation section in Get Started, perhaps add a link there to the main Installation page
*  The How to contribute page shows an empty drop-down menu
* There's a typo in "continious" integration file name
* I'd change the order of pages in the Developer Guide, the goal here is to take people from zero to the first PR
* The Installation page under the Developer Guide needs to link to the developer installation instruction rather than the top of the page 
* Deprecation should be a separate page in the Developer Guide (there's a page already for this)
* I think we can combine the Continuous Integration and Coding Standards page

Let me know if they're not clear, I'm happy to help with any of this!

**Comment by amrith-shell** [comment]
"I'd change the order of pages in the Developer Guide, the goal here is to take people from zero to the first PR" - what ordering would you suggest?

**Comment by fkiraly** [comment]
Thanks! Would you be able to write a few lines how @mloning´s comments were addressed?

**Comment by amrith-shell** [comment]
> 
> * I think we still want Installation to be under Documentation - **This has been addressed**
> * There is also a short installation section in Get Started, perhaps add a link there to the main Installation page - **This has been addressed**
> * The How to contribute page shows an empty drop-down menu - **This has been addressed**
> * There's a typo in "continious" integration file name - **This has been addressed**
> * I'd change the order of pages in the Developer Guide, the goal here is to take people from zero to the first PR - **This follows the above diagram**
> * The Installation page under the Developer Guide needs to link to the developer installation instruction rather than the top of the page - **This has been addressed**
> * Deprecation should be a separate page in the Developer Guide (there's a page already for this) - **Not sure where else to put. I thought based on the above diagram it made sense to go under coding standards** 
> * I think we can combine the Continuous Integration and Coding Standards page - **I tried this but it looked a bit messy for me, so I left it as 2 separate sections (as in the above diagram). But, happy to change if  others think its better as one.**

**Comment by fkiraly** [comment]
ok, thanks!

>> I think we can combine the Continuous Integration and Coding Standards page 
> I tried this but it looked a bit messy for me, so I left it as 2 separate sections (as in the above diagram). But, happy to change if others think its better as one.

Yes, I agree, in hindsight, that 2 separate sections are better here.

**Review by fkiraly — APPROVED** [review]
Excellent, looks good!

Major improvement to the documentation!
There's still a few bits and pieces that could be reordered or added, but that's better done in separate PRs.

**Pull request merged**
