### PR TITLE
[MNT] CI/CD failure diagnostics: prophet removal

### PR DESCRIPTION
**Pull request by fkiraly**
Diagnostic PR to address #2584.

This PR removes facebook `prophet` and `pystan` as dependencies, and all the extra steps in the windows CI that this had necessitated.

### CODE REVIEW

**Review by TonyBagnall — DISMISSED** [review]
I'm just approving this because I would like it to happen :)

**Comment by fkiraly** [comment]
we can´t just remove it without dprecation or alternative ... this was purely diagnostic

**Comment by fkiraly** [comment]
was diagnostic. No longer needed

**Comment by fkiraly** [comment]
problem resolved https://github.com/alan-turing-institute/sktime/issues/2748 ... for now ...

putting this PR to rest until we need it next

**Pull request closed without merging**
