### PR TITLE
Replace time.time with time.perf_counter

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
Fixes https://github.com/alan-turing-institute/sktime/issues/1194

#### What does this implement/fix? Explain your changes.
* replaces `time.time` with `time.perf_counter`

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
@RNKuhns, @mloning, can you kindly explain why this fixes #1194?
I don't see the link to the bug, and looking at your discussion in #1194 isn't very concrete there.

**Comment by mloning** [comment]
See https://github.com/alan-turing-institute/sktime/issues/1194#issuecomment-986061801

**Comment by fkiraly** [comment]
No changes, just the explanation why this fixes the bug.
Typical sequence is reproduce, understand, fix. I need to check that I've understood the fix.

**Comment by mloning** [comment]
Sure, I've added a short explanation on the issue. A "comment" review would have been better in this case I guess.

**Review by fkiraly — APPROVED** [review]
Got it, explanation makes sense.

**Comment by fkiraly** [comment]
> A "comment" review would have been better in this case I guess.

Well, a "bugfix" is changes to the code and sufficient evidence that it's fixed, and I've asked for the latter.

**Pull request merged**
