### PR TITLE
[FIX] Add missing init files

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
Related to #1661, #1699

#### What does this implement/fix? Explain your changes.
* add missing init files identified via: `find sktime -type d '!' -exec test -e "{}/__init__.py" ";" -not -path "**/__pycache__" -not -path "**/datasets/data*" -print`

### CODE REVIEW

**Review by chrisholder — DISMISSED** [review]

**Comment by mloning** [comment]
This is failing as expected because these tests weren't picked up previously.

**Comment by mloning** [comment]
Should be good to go now since #1661 has been merged

**Comment by fkiraly** [comment]
> `find sktime -type d '!' -exec test -e "{}/__init__.py" ";" -not -path "**/__pycache__" -not -path "**/datasets/data*" -print`

Excellent! Could we also add this as a CI check? I.e., that there are no missing init files? A check based on this line should work?
FYI @lmmentel

**Review by fkiraly — APPROVED** [review]
Looks good - should merge once tests pass.

**Comment by mloning** [comment]
Can we wait before we merge to see if #1699 fails without the init files?

**Comment by fkiraly** [comment]
of course

**Comment by fkiraly** [comment]
merged, since #1699 failed as expected.

**Pull request merged**
