### PR TITLE
[ENH] Rename PluginParamsForecaster

### PR DESCRIPTION
**Pull request by aiwalter**

### CODE REVIEW

**Comment by aiwalter** [comment]
I think actually that forecaster should live in forecasting module, but for now as it is experimental it can stay where it is probably

**Comment by fkiraly** [comment]
ah, come on :-)

I think it is one of many pipeline adapters for the parameter plugin functionality, so it should stay where it is.

I also like the name.

**Comment by fkiraly** [comment]
suggestion: let's not rename this or change location until it works for multiple estimator types

**Comment by aiwalter** [comment]
My name is fine for multiple estimator types

**Pull request closed without merging**
