### PR TITLE
Resolved warnings in ipynb examples

### PR DESCRIPTION
**Pull request by alwinw**
#### What does this implement/fix? Explain your changes.

When running the example ipynb in a clean environment, `ModuleNotFoundError` are raised for pmdarima (sktime/forecasting/arima.py#269) and tsfresh (sktime/transformers/series_as_features/summarize/_tsfresh.py).

Reran and cleaned up .ipynb outputs (example of previous warnings below):

image

image

#### Any other comments?

Really liking this package! Hoping to contribute more than fixing typos and updating docs in the future.

### CODE REVIEW

**Comment by mloning** [comment]
Hi @alwinw, thanks for your work on this. We treat tsfresh and pmdarima as a soft dependency to keep our core dependencies to a minimum. That's why we haven't included it in `setup.py`. But perhaps we should add a `!pip install tsfresh` and ``!pip install pmdarima` line to the notebook?

And thanks for cleaning the notebook output!

**Comment by alwinw** [comment]
Hi @mloning, thanks for explaining that to me. Interesting approach since a user can `pip install sktime` and hit a `ModuleNotFoundError` when trying to run selected functions which could become annoying. I'll remove it as a core dependency and add it into the notebook. 

Just changed my PR into a WIP one until I've fixed that up and have it passing the CI pipeline (I'll install precommit locally as well so my commit history isn't full of flake8 or black fixes!)

**Comment by mloning** [comment]
Since there are a number of other packages we'd like to support without blowing up our list of hard dependencies, we opted for that middle way. But happy to hear about alternatives! 

One suggestion we've received in the past is to add import checks and raise a more helpful error message when soft dependencies are missing (see #325).

**Comment by mloning** [comment]
Closed in favour of #410

**Pull request closed without merging**
