### PR TITLE
tsfeatures adapter

### LINKED ISSUE #905: tsfeatures in sktime
tsfeatures is a popular R package that gives a lot of important time series features and really helps with EDA and modelling.
There are various implementations of this in R and python: 
- [original R tsfeatures](https://cran.r-project.org/web/packages/tsfeatures/vignettes/tsfeatures.html)
- [python tsfeatures](https://github.com/FedericoGarza/tsfeatures)
- [featsts - R tidyverts alternative](https://cran.r-project.org/web/packages/feasts/index.html)

Although the current python package does the job well, having this functionality within sktime would be a very nice feature and would really help with the sktime forecasting workflow.

### PR DESCRIPTION
**Pull request by ltsaprounis**
#### Reference Issues/PRs

Fixes #905 

#### What does this implement/fix? Explain your changes.

Implementing a tsfeatures adapter for sktime. 
Will be a panel-to-tabular transformer, similar to tsfresh and catch22
#### Does your contribution introduce a new dependency? If yes, which one?
Adding [tsfeatures](https://github.com/FedericoGarza/tsfeatures) as a soft depeendency

#### What should a reviewer concentrate their feedback on?
Nothing yet, will update this section in the near future

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by ltsaprounis** [comment]
@mloning / @fkiraly - Some dependency issues with [tsfeatures](https://github.com/FedericoGarza/tsfeatures) here. 
Looks like the requirements in tsfeatures are too strict: 
```
arch==4.14
git+https://github.com/raphaelvallat/entropy@v0.1.1
pandas==1.0.5
scikit-learn==0.23.1
statsmodels==0.11.1
supersmoother==0.4
```
(Also [entropy](https://github.com/raphaelvallat/entropy) is depreciated)

I've raised this as an issue in tsfeatures but it might take a while till it's resolved. Another option is to create the individual features as series-to-primitives transformers as suggested by @fkiraly in https://github.com/alan-turing-institute/sktime/issues/905#issuecomment-853684571 and then create a panel-to-dataframe from those. 

A complete checklist for the individual series to primitives transformers (copied from [Combination of Forecast Methods by Feature-based Learning](https://htmlpreview.github.io/?https://github.com/robjhyndman/M4metalearning/blob/master/docs/M4_methodology.html#features)) would be:
- [ ] x_acf
- [ ] x_acf10
- [ ] diff1_acf1
- [ ] diff1_acf10
- [ ] diff2_acf1
- [ ] diff2_acf10
- [ ] seas_acf1
- [ ] ARCH.LM
- [ ] crossing_point
- [ ] entropy
- [ ] flat_spots
- [ ] arch_acf
- [ ] garch_acf
- [ ] arch_r2
- [ ] garch_r2
- [ ] alpha
- [ ] beta
- [ ] hurst
- [ ] lumpiness
- [ ] nonlinearity
- [ ] x_pacf5
- [ ] diff1x_pacf5
- [ ] diff2x_pacf5
- [ ] seas_pacf
- [ ] nperiods
- [ ] seasonal_period
- [ ] trend
- [ ] spike
- [ ] linearity
- [ ] curvature
- [ ] e_acf1
- [ ] e_acf10
- [ ] se
- [ ] peak
- [ ] trough
- [ ] stability
- [ ] hw_alpha
- [ ] hw_beta
- [ ] hw_gamma
- [ ] unitroot_kpss
- [ ] unitroot_pp
- [ ] series_length

**Comment by mloning** [comment]
Hey @ltsaprounis I'm not sure if the dependency issues have been resolved? Are you still thinking of finishing this PR? I may close this, of course you can always reopen if you want to pick it up again.

**Comment by ltsaprounis** [comment]
@mloning - the maintainers solved the dependencies shortly after I raised the issue but I forgot to get back to it. I'm not planning to work on this in the near future so makes sense to close it.

**Comment by AJarman** [comment]
@fkiraly I'd like to pick this up if possible

**Comment by fkiraly** [comment]
feel free to go ahead, @ajarman! Please post in the original issue #905, and have a look at the new transformers extension template. There´s also a rough tutorial for transformers, still work in progress, in this PR: https://github.com/alan-turing-institute/sktime/pull/1705 (feedback is appreciated)

**Comment by fkiraly** [comment]
PS @ajarman, I see you´re helping out in `pycaret` with interval forecasts, so you may also be interested to contribute to work in `sktime` on interval and probabilistic forecasting?

**Comment by AJarman** [comment]
> PS @AJarman, I see you´re helping out in `pycaret` with interval forecasts, so you may also be interested to contribute to work in `sktime` on interval and probabilistic forecasting?

All really did was implement croston inside a container, as it only had one parameter it wasn't a complicated implementation! I am still quite new to open source so working through 'first issues' at the moment, I've also applied to the mentorship program.a

**Comment by FedericoGarza** [comment]
Hi @AJarman! Are you still working on this issue? Let me know if I can help in any wat :)

**Pull request closed without merging**
