### PR TITLE
Added forecasting docstring examples

### PR DESCRIPTION
**Pull request by aiwalter**
#### What does this implement/fix? Explain your changes.
Added some docstring examples for the forecasting module
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

### CODE REVIEW

**Review by mloning — COMMENTED** [review]
Looks all good to me!

We just have to add the expected output to the tests.  

For BATS/TBATS could we also make sure they run reasonably fast by adding the same config as in `sktime/tests/_config.py `

**Comment by aiwalter** [comment]
@mloning there is an issue here with a test, it seems it runs  on an older commit. I have already fixed this and commited but test still seems to run on an older commit? 😕 

the test runs e.g. on the docstring..
```python
040     >>> from sktime.datasets import load_airline
041     >>> from sktime.forecasting.trend import PolynomialTrendForecaster
042     >>> y = load_airline()
043     >>> forecaster = PolynomialTrendForecaster(degree=1)
044     >>> forecaster.fit(y)
```
and this is giving an error because the output was not defined, so I replaced this with...
```python
    >>> from sktime.datasets import load_airline
    >>> from sktime.forecasting.trend import PolynomialTrendForecaster
    >>> y = load_airline()
    >>> forecaster = PolynomialTrendForecaster(degree=1)
    >>> forecaster.fit(y)
    >>> y_pred = forecaster.predict(fh=[1,2,3])
```
so basically just added the last line. Do you know why its running on this old commit?
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by mloning** [comment]
@aiwalter not sure, I restarted the tests now

**Comment by mloning** [comment]
@aiwalter seems like you have to include any expected print out for doctests - let's see if they pass now.

**Comment by mloning** [comment]
Now merged! 🎉

**Pull request merged**
