### PR TITLE
Implement a simple version of FlatTransformer

### PR DESCRIPTION
**Pull request by oleskiewicz**
#### What does this implement/fix?

Following the DSG Easter 2019, and sktime hackathon, we wanted `sktime` to have a way to extract a "flat" feature from timeseries -- a continuous ssgment in which values do not change.  Originally only for NaN values, this implementation works for NaNs, infinities and ay numbers.

#### Any other comments?

This is a draft implementation, and has a pretty serious bug: it does not correctly extract starting points & lengths for segments which "touch" endpoints of the series.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi, thanks very much for this, we will take a look. I'm not sure of the name, as FlatTransformer may sound like the concatenating Transformer

**Comment by oleskiewicz** [comment]
I'm glad I could contribute.  Originally the transformer was meant to be
looking for segments of missing values, but @mloning suggested it's more
general and useful if an arbitrary value can be given instead.  What other name
would you suggest?  I considered "ConstantTransformer" (sounds ambiguous) or
"PlateauTransformer" (couldn't spell it without a dictionary).

**Comment by mloning** [comment]
Maybe PlateauFinder or TimeSeriesPlateauFinder?

**Comment by oleskiewicz** [comment]
> Maybe PlateauFinder or TimeSeriesPlateauFinder?

I considered PlateauFinder but I personally found it hard to remember and
spell.  If everyone finds it ok I'll rename it in the next push.

Naming things really *is* the hard part.

**Pull request merged**
