### PR TITLE
Additions to docs-dev (PR #1205)

### PR DESCRIPTION
**Pull request by RNKuhns**
#### Reference Issues/PRs

Add on to #1205. 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by RNKuhns** [comment]
@mloning this has the updates to docs-dev that I've already pushed to Github.

**Comment by mloning** [comment]
@RNKuhns feel free to merge this whenever you think it's good to go

**Comment by RNKuhns** [comment]
@mloning I've updated the glossary and get started content. I've also added the shell of the documentation page in the dev guide and added the panels to `index.rst` and `developers.rst`. 

Just need time to make sure things are rendering as expected tomorrow. 

Note that we probably want to add the panels to the "about" page, but it is in markdown. We can figure out how to do that or convert it to a `about.rst`.

**Comment by mloning** [comment]
Converting about to rst seems like the easier solution. I'd like to avoid md files as much as possible since they don't support the cross-references as far as I understand.

**Comment by RNKuhns** [comment]
@mloning everything looks reasonable to me about this except for the links on the "panels" on the about page aren't working. Turns out I can't just convert the about.md to about.rst. I've got to do the sub-pages too. 

I'll push that shortly. Then once checks pass, I'll merge into docs-dev tonight and clear any code quality issues that remain (hopefully this PR will fix the ones in docs-dev).

**Comment by RNKuhns** [comment]
Actually, @mloning we could also just leave that as an easy item for someone during the docsprint. 

That way I can make the PR with the documentation guide. Probably more important to get that in. What are your thoughts?

**Comment by mloning** [comment]
Yes happy to leave that for the doc sprint. Let me know when you're happy with this PR or merge it directly!

**Pull request merged**
