### PR TITLE
Rotation Forest

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Implementation of the Rotation Forest algorithm and refactoring some of the contrib directories. 

I have grouped RotationForest and the previous ContinuousIntervalTree into `vector_classifiers` and grouped the temporal importance curves and critical difference diagram files into `diagram_code`.

This PR removes the previous rotation forest files, if @mloning or @ABostrom are against this I can put them back in, however.

### CODE REVIEW

**Comment by MatthewMiddlehurst** [comment]
doc-quality test failues are just deleted files.

**Comment by mloning** [comment]
Removing my attempt at it is fine!

**Review by TonyBagnall — APPROVED** [review]
contrib based and failure due to a known problem with deleted files, so I will push it in

**Comment by ABostrom** [comment]
@MatthewMiddlehurst kill mine with fire

**Pull request merged**
