### PR TITLE
Correct ReducedRegressionForecaster to ReducedForecaster

### PR DESCRIPTION
**Pull request by Proteusiq**
ReducedRegressionForecaster -> ReducedForecaster with `scitype="regressor"` parameter

I have updated all places where `ReducedRegressionForecaster` was used to capture the change of API. Rerunning the whole notebook from top to bottom introduced other changes from perhaps due to scikit-learn versions:

```bash
System:
    python: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
executable: /home/pwd/miniconda3/envs/series/bin/python
   machine: Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.10

Python dependencies:
          pip: 20.3.3
   setuptools: 52.0.0.post20210125
      sklearn: 0.24.1
        numpy: 1.20.1
        scipy: 1.6.0
       Cython: 0.29.17
       pandas: 1.2.1
   matplotlib: 3.3.4
       joblib: 1.0.0
threadpoolctl: 2.1.0

Built with OpenMP: True
```

### CODE REVIEW

**Comment by mloning** [comment]
Great, thanks @Proteusiq, seems like a few style checks didn't pass, you can see them here: https://github.com/alan-turing-institute/sktime/pull/706/checks?check_run_id=1960862031

If you set up precommit as described [here](https://github.com/alan-turing-institute/sktime/blob/79ac80ab65adb30fdf233e98433646c1989da2fc/CONTRIBUTING.md), it shouldn't be a problem.

**Comment by Proteusiq** [comment]
> Great, thanks @Proteusiq, seems like a few style checks didn't pass, you can see them here: https://github.com/alan-turing-institute/sktime/pull/706/checks?check_run_id=1960862031
> 
> If you set up precommit as described [here](https://github.com/alan-turing-institute/sktime/blob/79ac80ab65adb30fdf233e98433646c1989da2fc/CONTRIBUTING.md), it shouldn't be a problem.

I will fix that tomorrow

**Comment by Proteusiq** [comment]
image
Hurrah! It passed the precommits

**Comment by mloning** [comment]
Seems like someone made changes to the notebook already, @Proteusiq could you try to resolve the conflicts?

**Comment by Proteusiq** [comment]
> Seems like someone made changes to the notebook already, @Proteusiq could you try to resolve the conflicts?

I will do that tomorrow!

**Comment by Proteusiq** [comment]
It appears that the new changes I pulled down introduce some issues. GridSearchCV is taking forever and through lots of UserWarning: update is running recursively. :) I will take time in the afternoon to figure what is causing the issue:
Cell 32-33

**Comment by aiwalter** [comment]
I like the idea of renaming `ReducedRegressionForecaster`, what do you guys think about naming it `SupervisedForecaster`? Just as an idea

**Comment by mloning** [comment]
@aiwalter we actually call a [different learning task](https://github.com/sktime/enhancement-proposals/blob/master/steps/04_supervised_forecasting_api/step.md) "supervised forecasting"

**Comment by Proteusiq** [comment]
I will just get a clean project

**Pull request closed without merging**
