### PR TITLE
Added multivariate NaiveForecaster

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
Related #1399 

#### What does this implement/fix? Explain your changes.
Made `NaiveForecaster` multivariate by means of `ColumnsEnsembleForecaster`

also fixes a bug in `OnlineEnsembleForecaster` which was not completely refactored and overrode `update_predict` with an old version

### CODE REVIEW

**Comment by aiwalter** [comment]
@fkiraly is the fix for this "`pd.Series` in, `pd.DataFrame` out issue" contained in one of your PRs? So I could already cross-merge to test it here.

**Comment by fkiraly** [comment]
>@fkiraly is the fix for this "pd.Series in, pd.DataFrame out issue" contained in one of your PRs?

Ah, no, not yet. All my new PR concern the testing framework refactor.

**Comment by fkiraly** [comment]
Here it is, @aiwalter - local tests are still running but good so far; any checks failing due to the change in return type behaviour are yours to fix, as agreed.
https://github.com/alan-turing-institute/sktime/pull/1410

**Comment by aiwalter** [comment]
@fkiraly could you have a look into this pls? There seems to be an issue with the performance, the following test makes issues:
```python
hedge_expert = NormalHedgeEnsemble(n_estimators=3, loss_func=mean_squared_error)
forecaster = OnlineEnsembleForecaster([
    ("av5", NaiveForecaster(strategy="mean", window_length=5)),
    ("av10", NaiveForecaster(strategy="mean", window_length=10)),
    ("av20", NaiveForecaster(strategy="mean", window_length=20)),
],
ensemble_algorithm=hedge_expert,
)

forecaster.fit(y_train)
```
I get `RuntimeError: Failed to converge after 100 iterations.` , when I replace `NaiveForecaster` with `_NaiveForecaster` it works as before ofc. Might it come from some data type transformations which happen internally? But I have set `"y_inner_mtype": ["pd.Series", "pd.DataFrame"]` so not sure if there is a type convertion when I give a `pd.Series` in?

**Comment by aiwalter** [comment]
I fixed `update_predict` in `OnlineEnsembleForecaster` by removing it and using the new one from base class. Tests and notebook adjusted accordingly.

**Review by fkiraly — APPROVED** [review]
Looks good to me now!

@mloning, do you also want to have a quick look?

**Pull request merged**
