### PR TITLE
[DOC] Replaced youtube link with recent PyData Global

### PR DESCRIPTION
**Pull request by aiwalter**

### CODE REVIEW

**Review by fkiraly — COMMENTED** [review]
can we somehow also count the views on the old video?

**Comment by aiwalter** [comment]
what do you mean with count?

**Comment by fkiraly** [comment]
> what do you mean with count?

View count, which for the old video is at 80k or so, and for the new video at 2k?

**Comment by aiwalter** [comment]
yes, but who cares about that if its old content? Also the new one was PyData Global and the other one "only" PyData Amsterdam.

**Comment by fkiraly** [comment]
>yes, but who cares about that if its old content?

Well, if there´s a way to link the up-to-date content and cumulative view counts on the sktime channel, instead of an individual video? Because the alternative would reset the view count shown to zero each time we update the basic tutorial.

**Comment by fkiraly** [comment]
sth like this, random google?
https://github.com/ntec-io/Youtube-Channel-Badge

**Review by fkiraly — APPROVED** [review]
(happy with this)

**Pull request merged**
