### PR TITLE
datetime: Construct Timedelta from parsed pandas frequency

### PR DESCRIPTION
**Pull request by ckastner**
Add support for non-unit frequencies (eg: 30 minutes) by parsing the pandas frequency and extracting the relevant values to pass on to pd.Timedelta().

This works for frequencies like `D` and `3D`, as demonstrated by the test.

This does not work with [anchored offsets](https://pandas.pydata.org/docs/user_guide/timeseries.html#anchored-offsets), like the `W-SUN` mentioned in #866, as it's not immediately obvious to me how one would construct a correct Timedelta from this. I suspect that the anchor can simply be dropped (7 days are 7 days, no matter whether they start on Sunday or Monday), but I'm not entirely sure, and I had a hard time constructing a test example.

Fixes: #868

### CODE REVIEW

**Review by mloning — COMMENTED** [review]
Thanks for the PR @ckastner - much appreciated! Make sure you add yourself to the contributors (otherwise I can do that too if that's easier). 

Please also take a look at the CONTRIBUTING.md to set up precommit for code quality checks. Let me know if you need any help or have questions.

**Comment by ckastner** [comment]
@mloning, I fixed the issue that pyflake8 complained about earlier. I also added myself to .all-contributorsrc.

I previously had issues running the full test suite (now, it's even segfaulting), but running the single test file wtih my local version of pytest worked fine.

**Comment by mloning** [comment]
@ckastner thanks - failures seem unrelated to the changes in this PR, I'll check back later (they usually sort themselves out).

**Review by mloning — APPROVED** [review]
Changes look good to me. Thanks @ckastner!

**Comment by mloning** [comment]
Thanks @ckastner - now merged!

**Pull request merged**
