### PR TITLE
[ENH] hierarchical mtype generator 

### PR DESCRIPTION
**Pull request by ltsaprounis**
#### Reference Issues/PRs

See also #1738

#### What does this implement/fix? Explain your changes.

Implements a synthetic data generator for the hierarchical mtype

#### TO-DOs: 
- [X] Unequal length 
- [X] Docstring
- [ ] Unit tests

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Looks great!

Can you write a docstring, please?
(some things I really have to guess...)

**Comment by danbartl** [comment]
Hi thanks looks great and really helpful!

Just as an idea: Do we want the total column h0 to be included, since it is in principle redundant?
```
_make_hierachical(hierarchy_levels = (1, 4))
                            c0
`...`
h0   h1   time                
h0_0 h1_0 2000-01-01  1.000000
          2000-01-02  4.804243
```
 
Also regarding the naming: For multtiindex we have instances and timepoints as name, maybe here have the time column also be named timepoints?

Regarding time series to have unequal time index: Guess it could make sense, since hierarchical reconciliation does not really care about different lengths (as long as fh is the same)

**Comment by ltsaprounis** [comment]
Addressed the comments from @fkiraly and @danbartl. 
Will add some unit tests before requesting the next round of reviews.

**Review by fkiraly — APPROVED** [review]
Looks great, very useful, thanks!

**Pull request merged**
