### PR TITLE
Refactor the factory method for reduction forecasters

### PR DESCRIPTION
**Pull request by Lovkush-A**
#### Reference Issues/PRs
Refactors #757 

#### What does this implement/fix? Explain your changes.
Refactoring the factory method in reduction forecasters.
* creating new method which includes helper functions to check user inputs
* keeping the old method (and reintroducing an even older method) but adding deprecation warning
* updating various files and test with new methods name
* updating forecasting tutorial notebook

### CODE REVIEW

**Comment by Lovkush-A** [comment]
@mloning What was the reason for adding ReducedRegressionForecaster in your PR? It looks identical to ReducedForecaster, and seems redundant.

**Comment by mloning** [comment]
I included it again because we didn't deprecate it properly when we removed it and a lot of tutorials are based on it.

**Comment by Lovkush-A** [comment]
Alright. Can you point me to an example tutorial, to check the latest deprecation works as expected?

**Comment by mloning** [comment]
Can't think of a tutorial on deprecation. We could add additional warning if the signature changed. But this way at least user don't get a `ModuleNotFound` error but a somewhat more helpful invalid input argument error and can then look up the new signature.

**Comment by Lovkush-A** [comment]
@mloning Sorry, I meant an example sktime tutorial in which ReducedRegressionForecaster is used. I will then locally run the sktime tutorials and see if the error message/deprecation message makes sense.

**Comment by mloning** [comment]
Ah - the forecasting tutorial in the examples folder uses it.

**Comment by Lovkush-A** [comment]
@mloning I looked at the forecasting notebook in examples. `ReducedRegressionForecaster` had already been updated to `ReducedForecaster`. 

More importantly, the deprecation warning did come up for `ReducedForecaster`, so looks like that works fine, and it should work similarly for `ReducedRegressionForecaster`.  However, the notebook will need to be updated as the scitype names have changed. I will update it now (and update it to `make_reduction`)

**Comment by fkiraly** [comment]
a common motif is to print a warning message "is deprecated in v.123 and will be removed in future major release v.234", see also
https://docs.python.org/3/library/exceptions.html#DeprecationWarning

**Comment by mloning** [comment]
Closed in favour of #757

**Pull request closed without merging**
