### PR TITLE
refactors HCrystallBall Forecaster

### PR DESCRIPTION
**Pull request by thayeylolu**
Reference : https://github.com/alan-turing-institute/sktime/issues/955

We need to slowly re-factor all forecasters to be compliant with the new interface (see PR #912). i.e., no overrides of fit etc and descendant classes only implementing core logic, while the BaseForecaster implements check etc logic.

Currently this is running due to various downwards compatibility workarounds, which should be removed once all forecasters are ready (in "no-override" state)

The forecasters that still need a downstream refactor are:

  

- [x] HCrystalBallForecaster

### CODE REVIEW

**Comment by thayeylolu** [comment]
Hello @mloning @fkiraly @aiwalter . I would like to request for review. For some reason, I cannot do that on the reviewer menu. Did I raise the pull request wrongly?

**Review by mloning — APPROVED** [review]

**Review by fkiraly — APPROVED** [review]
looks good to me!

**Comment by thayeylolu** [comment]
Hello @fkiraly , I cannot see the option to merge this. Would you be able to merge it?

**Comment by fkiraly** [comment]
>I cannot see the option to merge this. Would you be able to merge it?

Yes, I guess this relates to earlier discussion with @mloning - you need push access to the repo to merge it.
https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request

So I guess the modification of GitHub flow is that repo collaborators have to merge if the PRer is not a collaborator.
FYI, @mloning - you were right.

**Pull request merged**
