### PR TITLE
Comment removal for individual classifier tests

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Removes commented out methods from all my tests and removes replace_X_y.

Reintroduces contracting tests but with no comparison to previous results/accuracy.

Moves all code relating to result generation for individual classifier result reproduction tests to `contrib/_classification_test_reproduction.py`.

Part of #1765.

### CODE REVIEW

**Comment by fkiraly** [comment]
Since this touches the tests module and I´m asked to review, would you kindly mind being a bit more explicit about the changes? E.g., what does "Centralises results generation" mean, practically?

**Comment by MatthewMiddlehurst** [comment]
It doesn't touch the tests module, just individual classifier tests and contrib. You set yourself as code owner for the whole repo, so you probably will get requested to review everything along with Martin and Tony.

I have moved all the previously commented code to re-generate the results used for comparison in these tests into a single file in contrib for now.

**Comment by fkiraly** [comment]
> You set yourself as code owner for the whole repo, so you probably will get requested to review everything along with Martin and Tony.

Yes, all CC members are owners for the entire repo.
This touches 34 files, so some details would be appreciated.

**Comment by TonyBagnall** [comment]
@fkiraly you requested this change, it simply moves commented out code into contrib

**Comment by fkiraly** [comment]
ah, I see - makes sense.

**Pull request merged**
