### PR TITLE
[BUG] Knn bugfix to allow GridsearchCV and usage with column ensemble.

### LINKED ISSUE #578: [BUG] ColumnEnsembleClassifier fails fitting KNN classifiers
**Describe the bug**
I am trying to classify a multivariate dataset using a ColumnEnsembleClassifier. I use the same classifier for all dimensions.
It fails to fit the dataset when I use KNN classifiers, but works when I use TimeSeriesForestClassifier.

I tried KNN with different metrics ('msm, 'dtw' 'euclidean' -> imported from scipy'), all of them fail
I tried it with AtrialFibrillation and BasicMotions datasets, it fails for both.

**To Reproduce**
```python
from sktime.utils.data_io import load_from_arff_to_dataframe as load_arff
X_train, y_train = load_arff(path_to_dataset_TRAIN.arff')

from sktime.classification.compose import ColumnEnsembleClassifier
from sktime.classification.distance_based._time_series_neighbors import KNeighborsTimeSeriesClassifier
from sktime.classification.compose import TimeSeriesForestClassifier

########## This one works fine ##########
clf= ColumnEnsembleClassifier(estimators=[
                                       ('TSF_0',TimeSeriesForestClassifier(verbose=0,n_jobs=-1),[0]),
                                       ('TSF_1',TimeSeriesForestClassifier(verbose=0,n_jobs=-1),[1])
                                     ])
clf.fit(X_train, y_train)
ColumnEnsembleClassifier(estimators=[
                                       ('TSF_0',TimeSeriesForestClassifier(n_jobs=-1),[0]),
                                       ('TSF_1',TimeSeriesForestClassifier(n_jobs=-1),[1])
                                     ])


########## This one fails ########## 
clf= ColumnEnsembleClassifier(estimators=[
                                       ('1NN-MSM_0', KNeighborsTimeSeriesClassifier(metric='msm'), [0]),
                                       ('1NN-MSM_1', KNeighborsTimeSeriesClassifier(metric='msm'), [1])
                                     ])
clf.fit(X_train, y_train)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\Desktop\OVGU\DKE Subjects\Master Thesis\Code\run.py in <module>
----> 1 clf.fit(X_train, y_train)

~\.virtualenvs\Code-OH4xsw-D\lib\site-packages\sktime\classification\compose\_column_ensemble.py in fit(self, X, y)
    157         for name, estimator, column in self._iter(replace_strings=True):
    158             estimator = clone(estimator)
--> 159             estimator.fit(_get_column(X, column), transformed_y)
    160             estimators_.append((name, estimator, column))
    161

~\.virtualenvs\Code-OH4xsw-D\lib\site-packages\sktime\classification\distance_based\_time_series_neighbors.py in fit(self, X, y)
    243             check_array.__code__ = _check_array_ts.__code__
    244
--> 245         fx = self._fit(X)
    246
    247         if hasattr(check_array, "__wrapped__"):

~\.virtualenvs\Code-OH4xsw-D\lib\site-packages\sklearn\neighbors\_base.py in _fit(self, X, y)
    362             if not isinstance(X, (KDTree, BallTree, NeighborsBase)):
    363                 X, y = self._validate_data(X, y, accept_sparse="csr",
--> 364                                            multi_output=True)
    365
    366             if is_classifier(self):

~\.virtualenvs\Code-OH4xsw-D\lib\site-packages\sklearn\base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    413             if self._get_tags()['requires_y']:
    414                 raise ValueError(
--> 415                     f"This {self.__class__.__name__} estimator "
    416                     f"requires y to be passed, but the target y is None."
    417                 )

ValueError: This KNeighborsTimeSeriesClassifier estimator requires y to be passed, but the target y is None.
```

**Expected behavior**
ColumnEnsembleClassifier should fit the training data

**Versions**
<details>

System:
    python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
executable: C: ...\\....\\.virtualenvs\Code-OH4xsw-D\Scripts\python.exe
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
          pip: 20.3.1
   setuptools: 50.3.2
      sklearn: 0.24.0
       sktime: 0.5.0
  statsmodels: 0.12.1
        numpy: 1.19.4
        scipy: 1.5.4
       Cython: 0.29.21
       pandas: 1.1.5
   matplotlib: 3.3.3
       joblib: 1.0.0
        numba: 0.52.0
     pmdarima: None
      tsfresh: 0.17.0

</details>

### LINKED ISSUE #1057: [BUG] Cross validation has no effect on KNeighborsTimeSeriesClassifier distance measure parameters
**Describe the bug**

Using scikit-learn cross validation functions on sktime's KNN classifier to set the distance measure hyperparameters always produces the same score.

**To Reproduce**

```python
from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier
from sktime.datasets import load_basic_motions

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

import pandas as pd

X, y = load_basic_motions(return_X_y = True)
x_train, x_test, y_train, y_test = train_test_split(X.iloc[:, [0]], y)

param_matrix = {
                "distance_params": [{"w": x / 100} for x in range(0, 100)]
            }
grid = GridSearchCV(
                estimator=KNeighborsTimeSeriesClassifier(
                    distance="dtw", n_neighbors=1
                ),
                param_grid=param_matrix,
                cv=10,
                scoring="accuracy",
            )

grid.fit(x_train, y_train)

print(pd.DataFrame(grid.cv_results_))

    mean_fit_time  std_fit_time  mean_score_time  std_score_time param_distance_params  ... split8_test_score  split9_test_score  mean_test_score  std_test_score  rank_test_score
0        0.003862      0.000397         0.033888        0.001333            {'w': 0.0}  ...               1.0                1.0              1.0             0.0                1
1        0.003609      0.000302         0.033037        0.000653           {'w': 0.01}  ...               1.0                1.0              1.0             0.0                1
2        0.003663      0.000329         0.033945        0.002118           {'w': 0.02}  ...               1.0                1.0              1.0             0.0                1
3        0.003961      0.000472         0.034648        0.001769           {'w': 0.03}  ...               1.0                1.0              1.0             0.0                1
4        0.003810      0.000332         0.033339        0.000514           {'w': 0.04}  ...               1.0                1.0              1.0             0.0                1
..            ...           ...              ...             ...                   ...  ...               ...                ...              ...             ...              ...
95       0.003410      0.000301         0.033238        0.001309           {'w': 0.95}  ...               1.0                1.0              1.0             0.0                1
96       0.003910      0.000375         0.033840        0.001541           {'w': 0.96}  ...               1.0                1.0              1.0             0.0                1
97       0.003459      0.000270         0.032236        0.000451           {'w': 0.97}  ...               1.0                1.0              1.0             0.0                1
98       0.003660      0.000230         0.032135        0.000351           {'w': 0.98}  ...               1.0                1.0              1.0             0.0                1
99       0.003659      0.000230         0.032436        0.000898           {'w': 0.99}  ...               1.0                1.0              1.0             0.0                1

[100 rows x 19 columns]
```

**Expected behavior**

Using different parameters should produce different scores.

**Additional context**

I've tested this bug using multiple different datasets and distance measures, and all produced the same issue. I believe this issue is caused by the use of both "distance_params" and "metric_params" to store the distance measure parameters. Only the value in metric_params is actually passed to the distance measures, but when using cross validation, this is never set as the constuctor is not called, but rather the inital classifier is cloned, so the default value is always used. 

This could be fixed by removing "distance_params" entirely and replacing with "metric_params", which does lead to different scores for different hyperparameters, as shown in the results below.
```python
    mean_fit_time  std_fit_time  mean_score_time  std_score_time param_metric_params  ... split8_test_score  split9_test_score  mean_test_score  std_test_score  rank_test_score
0        0.003861      0.000395         0.017496        0.000875          {'w': 0.0}  ...          0.333333           0.833333         0.600000        0.213437              100
1        0.004018      0.000502         0.018389        0.000853         {'w': 0.01}  ...          1.000000           0.833333         0.933333        0.110554               99
2        0.003804      0.000402         0.018915        0.000394         {'w': 0.02}  ...          1.000000           0.833333         0.950000        0.076376               98
3        0.004018      0.000325         0.021227        0.003138         {'w': 0.03}  ...          1.000000           0.833333         0.966667        0.066667               97
4        0.004812      0.001080         0.022917        0.002269         {'w': 0.04}  ...          1.000000           0.833333         0.983333        0.050000               94
..            ...           ...              ...             ...                 ...  ...               ...                ...              ...             ...              ...
95       0.003760      0.000336         0.033539        0.000612         {'w': 0.95}  ...          1.000000           1.000000         1.000000        0.000000                1
96       0.003957      0.000815         0.035548        0.002654         {'w': 0.96}  ...          1.000000           1.000000         1.000000        0.000000                1
97       0.003910      0.000301         0.033188        0.000201         {'w': 0.97}  ...          1.000000           1.000000         1.000000        0.000000                1
98       0.003609      0.000201         0.033138        0.000351         {'w': 0.98}  ...          1.000000           1.000000         1.000000        0.000000                1
99       0.003762      0.000248         0.033348        0.000860         {'w': 0.99}  ...          1.000000           1.000000         1.000000        0.000000                1

[100 rows x 19 columns]
```

I am raising this as an issue as there may be better solutions whilst keeping the variable names clear.
**Versions**
<details>

System:
    python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
executable: C:\Users\XXX\AppData\Local\Programs\Python\Python37\python.exe
   machine: Windows-10-10.0.16299-SP0

Python dependencies:
          pip: 20.2.3
   setuptools: 56.2.0
      sklearn: 0.24.2
       sktime: 0.6.1
  statsmodels: 0.12.2
        numpy: 1.20.3
        scipy: 1.5.3
       Cython: 0.29.14
       pandas: 1.1.3
   matplotlib: 3.3.2
       joblib: 0.17.0
        numba: 0.52.0rc3
     pmdarima: 1.7.1
      tsfresh: 0.17.0

### LINKED ISSUE #1713: [ENH] new version of KNeighborsTimeSeriesClassifier
with the numba distances in place (except for MSM) we can adapt KNN to use them and address other long standing issues. 
https://github.com/alan-turing-institute/sktime/pull/1664

1. Adapt KNN to use numba
2. Assess the potential for restructuring (no 2D arrays, default more to sklearn)
3. Address outstanding issues
https://github.com/alan-turing-institute/sktime/issues/589
https://github.com/alan-turing-institute/sktime/issues/578 (although column ensembler has its own issues)
https://github.com/alan-turing-institute/sktime/issues/654 (probably solved)
https://github.com/alan-turing-institute/sktime/issues/646 (probably solved)
https://github.com/alan-turing-institute/sktime/issues/645
https://github.com/alan-turing-institute/sktime/issues/1057

### PR DESCRIPTION
**Pull request by TonyBagnall**
#### Reference Issues/PRs
Fixes #1713  
Fixes #578
Fixes #1057 

#### What does this implement/fix? Explain your changes.

Simple fix to allow for correct parameter setting with GridCV. It removes a temporary measure to allow KNN to pass tests and fixes thanks to the new distance factory. Note we should do some work on making the valid parameters clearer for the different distance measures

Below code all works

## code 
knn = KNeighborsTimeSeriesClassifier(distance="dtw", n_neighbors=1, distance_params={
    "window":0.5})
knn2 = KNeighborsTimeSeriesClassifier(distance="dtw", n_neighbors=1)

param_matrix = {"distance_params": [{"window": x/10.0} for x in range(0,10)]
                }

### CV Parameter search
grid = GridSearchCV(knn2, param_grid=param_matrix, cv=2, scoring="accuracy")
grid.fit(x_train, y_train)
print(pd.DataFrame(grid.cv_results_))
print(grid)
print(" params after CV = ",knn2.get_params())
knn4 = KNeighborsTimeSeriesClassifier(distance="dtw", n_neighbors=1, distance_params={
    "window":0.0})

estimators = [
    ("knn", knn, [0, 1, 2]),
    ("knn2", knn2, [3, 4]),
    ("knn4", knn4, [5]),
]
x_train, y_train = load_basic_motions(split="train")
x_test, y_test = load_basic_motions(split="test")

### train column ensemble
col_ens = ColumnEnsembleClassifier(estimators=estimators)
col_ens.fit(x_train, y_train)
print(" Score = ",col_ens.score(x_train, y_train))

### CODE REVIEW

**Comment by fkiraly** [comment]
stupid question - what metric do you tune a clustering algorithm for?

**Review by chrisholder — APPROVED** [review]

**Comment by chrisholder** [comment]
It's a classifier @fkiraly

**Comment by TonyBagnall** [comment]
> stupid question - what metric do you tune a clustering algorithm for?

number of clusters usually, but this is classification, just closing some very old issues

**Comment by fkiraly** [comment]
ah, I misread knn for kmeans

**Pull request merged**
