### PR TITLE
[Bug] Fix override/defaulting of "prediction intervals" adders 

### LINKED ISSUE #3009: [ENH] check override/defaulting of "prediction intervals" adders
From the presentation of @bethrice44:

if we take a "prediction intervals adder" wrapper, e.g., one adding `predict_intervals`, to add prediction intervals to an estimator that already has a *different* probabilistic prediction method implemented, this may lead to unexpected behaviour.

For example, assume the inner method has `predict_quantiles` implemented, and `predict_intervals` uses the default method which calls `predict_quantiles`. 

The wrapper overwrites `predict_intervals`, and it might not overwrite `predict_quantiles`. Then, the predictoins from `predict_intervals` and `predict_quantiles` will be inconsistent.

Instead, the wrapper perhaps should (?) overwrite `predict_quantiles` with the base class default?

### PR DESCRIPTION
**Pull request by bethrice44**
#### Reference Issues/PRs
Fixes #3009 

#### What does this implement/fix? Explain your changes.

This adds the base class `_predict_quantiles` method into `conformal.py` to ensure that the `_predict_quantiles` method for the forecaster that is wrapped with `conformal.py` is consistent with `_predict_interval`.

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

I have just copied and pasted the base class `_predict_quantiles` method and removed the `implements_interval` check . Should this be amended at all? 

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Makes sense!

Question, should this perhaps be an explicit call to `BaseForecaster._predict_quantiles` instead?

Because if we fix a bug in that, it would not propagate to here.

This is very non-hypothetical, see this bug in the default `_predict_quantiles`!
https://github.com/alan-turing-institute/sktime/pull/3106

**Comment by bethrice44** [comment]
> Makes sense!
> 
> Question, should this perhaps be an explicit call to `BaseForecaster._predict_quantiles` instead?
> 
> Because if we fix a bug in that, it would not propagate to here.
> 
> This is very non-hypothetical, see this bug in the default `_predict_quantiles`! #3106

Good shout - I'll call directly to `BaseForecaster`

**Review by fkiraly — APPROVED** [review]
Thanks!

**Comment by fkiraly** [comment]
CI failures unrelated, see https://github.com/alan-turing-institute/sktime/issues/3103

**Comment by fkiraly** [comment]
Failures unrelated, caused by #3103

**Pull request merged**
