### PR TITLE
basic classifier result setup

### PR DESCRIPTION
**Pull request by chrisholder**
#### Reference Issues/PRs

#1123 

#### What does this implement/fix? Explain your changes.

Basic implementation of the result collation for classifiers. So far it is reading the results from the timeseriesclassification website and is placing them in dataframes. Waiting for instructions on how to continue with this.

#### Any other comments?

Let me know where you want me to continue @TonyBagnall 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
"httpx - this will be a soft dependency. If it is to much hassel I can just go to built in python request. 

I think remove the dependency, soz :)

**Review by TonyBagnall — COMMENTED** [review]
does it deal with the case when the results are not on the website?

**Comment by chrisholder** [comment]
So it would just return nothing in those instances - I can add some more explicit error messaging to it. Currently it hits the website 3 times:

1) Gets a list of problems: "https://timeseriesclassification.com/JSON/datasetTable.json?order=asc"
2) Get a list of classifiers:  "https://timeseriesclassification.com/JSON/algorithmTable.json?order=asc"
3) Get the results: "https://timeseriesclassification.com/results/ResultsByClassifier/TSF_TESTFOLDS.csv

So the first two I could add a fall back to 1 and 2. Just as an fyi the reason I figured it would be a good idea to generate the list of potential algorithms and datasets by hitting the website is so someone doesn't have to come change the code everything a new classifier or dataset is added. But I can just write a list for now and that can act as a fallback.

Number 3 if that fails then no result will be got.

So im going to add three things.
1) Better error messaging if the request fails to the website
2) Retry hitting the website a couple times befor accepting defeat
3) Adding falls backs where I can i.e. 1 and 2 above.

**Comment by TonyBagnall** [comment]
hi chris Id like to get this in because I would like to start using it. Is it good to go?

**Comment by fkiraly** [comment]
>Is it good to go?

Well, it's still a draft, so needs review once it's a full PR.

**Comment by TonyBagnall** [comment]
> > Is it good to go?
> 
> Well, it's still a draft, so needs review once it's a full PR.

yes hence why I was asking him it is good to be  not draft. FYI, it is in the contrib directory

**Comment by chrisholder** [comment]
@TonyBagnall yep Ill make this a full pr

**Pull request closed without merging**
