### PR TITLE
changed dashes in every "tag_name" to underscores

### PR DESCRIPTION
**Pull request by tensorflow-as-tf**
This PR aims to address #1397.

All dashes in tags are replaced by underscores so that a vanilla call to `set_tags` with `tag_name=tag_value` will not break as `tag_name` does not contain any dash symbol.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi, I know its a small change but I'm worried this may cause conflicts with other ongoing PRs thus causing others grief. Might it be better to do it module by module (forecasting as one PR, then transformations, etc)?

**Comment by TonyBagnall** [comment]
hi, I think the code has gone beyond this, it is probably worth doing this more incrementally when the classification refactor is complete. Can I close this PR?

**Comment by fkiraly** [comment]
@TonyBagnall, not sure - pending fixes in the merge conflicts, might be worth doing this before the release?

**Comment by fkiraly** [comment]
out of sync since 1 y old, closing. Let´s try the renaming separately.

**Pull request closed without merging**
