### PR TITLE
Implement multi-output reduction strategy for ReducedRegressionForecaster

### LINKED ISSUE #403: Implement multi-output reduction strategy for ReducedRegressionForecaster
We currently support the following strategies for reduction from forecasting to regression (see this [file](https://github.com/alan-turing-institute/sktime/blob/master/sktime/forecasting/compose/_reduce.py)): 

- [x] direct
- [x] recursive
- [ ] dirrec (see #226)
- [ ] multi-output (see #440)

For an overview of forecasting strategies for multi-step forecasting horizons see this [paper](https://d1wqtxts1xzle7.cloudfront.net/41231210/Machine_Learning_Strategies_for_Time_Ser20160114-28513-1pqgoe9.pdf20160115-19908-phg1xc.pdf?1452888125=&response-content-disposition=inline%3B+filename%3DMachine_Learning_Strategies_for_Time_Ser.pdf&Expires=1602491710&Signature=V6cHqybz3g9idBMTkbC4kwDMppSA4FnO9cd~R0VY8JVmVUKrK28MGRJlKhMfODdsSxcWsT5wvu2y3elqoES3ILHn1vlka20fO9z~dYmKB4oPsV04fG3lRhDe1Sx5QKgSmU4PMpWxa3bAwE8DKC4dlDcuLY7wequBDkTlItBFeYqOrJUhc91tMJxMpJ7gVtDzmAFyP58Fw5iXQN19fhCe2RoMtQ2uLRJrWvmlEdRvOhrffgnOR1g9N71Nt01I3X5~DON8gmKEmaGKYWv1wYg7JrSmLXnyZ2gVBUgdhERUxZ7VKSOMp-z0KFsuPV1bL7MbIZrHs7eHMnXK9v4vqT47ig__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA).  This issue is about the multi-output strategy. Some models can directly predict multiple outputs, see e.g. LinearRegression:
```python
import numpy as np
from sklearn.linear_model import LinearRegression

y = np.random.normal(size=(10, 3))  # target has multiple columns
X = np.random.normal(size=(10, 5))

estimator = LinearRegression()
estimator.fit(X, y)
y_pred = estimator.predict(X)  # we predict multiple columns
print(y_pred.shape)
>>> (10, 3)
```
 
We need to enable the multi-output prediction strategy by adding a "multioutput" option to the "strategy" kwarg in the [`ReducedRegressionForecaster`](https://github.com/alan-turing-institute/sktime/blob/master/sktime/forecasting/compose/_reduce.py).

We could check the estimator by checking if it inherits from scikit-learn's `MultiOutputMixin`.

### PR DESCRIPTION
**Pull request by NikeNano**
#### Reference Issues/PRs
Fixes  #403

#### What does this implement/fix? Explain your changes.

This PR aims to implement multi-output reduction strategy for ReducedRegressionForecaster. Currently there are some duplication of code that could be factored out depending on how we like to structure the code, I can continue the work on this but would like to get some early feedback. 

#### Does your contribution introduce a new dependency? If yes, which one?
No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by mloning — COMMENTED** [review]
Hi @NikeNano, thanks for working on this, really appreciated! 

Some initial feedback: 
* There seem to be some conflation of the "recursive" and "multi-output" strategy, but both as separate strategies as I understand it
* So you correct in creating a `_MultiOutputReducer` class but don't need the `_RecursiveReducerMultiOutput` and the `allowed_strategies` should be `("direct", "recursive", "multioutput")
* You should not have to change anything in the base forecaster classes or shared validation functionality, as the "multi output" reduction strategy is still a forecaster which forecasts a single/univariate series (i.e. a pd.Series and not a pd.DataFrame)

Hope this helps, let me know if you have any questions!

**Comment by NikeNano** [comment]
I have sadly got to much to do and have to down priorities this for the moment, will try to comeback to this later @mloning :(

**Comment by mloning** [comment]
@NikeNano Thanks for letting us know!

**Comment by mloning** [comment]
Closed by #659

**Pull request closed without merging**
