### PR TITLE
Add pydocstyle to precommit

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
#752 

#### What does this implement/fix? Explain your changes.
* Adds pydocstyle test to precommit rather than running them as separate CI checks
* Updates pre-commit hooks
* Remove pydoctests from GitHub Actions CI checks

### CODE REVIEW

**Comment by mloning** [comment]
Using pre-commit is stricter than using (optional) CI tests and potentially frustrates new contributors, so let's wait before we add this until the docstrings in most files have been fixed.

**Comment by aiwalter** [comment]
could we maybe already merge this? Bcz now the `pydocstyle` is anyway running at CI/CD as far as I see?

**Comment by mloning** [comment]
@aiwalter yes, I see what you mean, was thinking the same the other day. As you say, I see the docstring tests currently as optional, whereas the other precommit checks are mandatory. Adding them to precommit, will make it hard to see whether it's failing due to docstrings or other formatting issues. Perhaps that's something we can do at the beginning of the doc sprint?

**Comment by RNKuhns** [comment]
@aiwalter and @mloning I think we are closer to being able to do this than we have been. The branch docs-dev we've been working on also includes tons of small documentation tweaks to fix warnings generated by `numpydoc` when parsing docstrings. That meant I had to fix the `pydocstyle` errors for those files. In many cases this touched a lot of files in the module, so I made the minor fixes to pass `pydocstyle` checks for other files in those modules.

**Comment by mloning** [comment]
From some discussions with @aiwalter and @RNKuhns, the idea is to merge this after the docsprint to make doc-quality checks a more integral part of the dev work after we've hopefully cleaned up most docstrings.

**Review by aiwalter — APPROVED** [review]

**Review by RNKuhns — APPROVED** [review]
@mloning I agree that we should go ahead with this.

**Pull request merged**
