### PR TITLE
[ENH] verbose output for `linux` and `mac` tests

### LINKED ISSUE #1947: [ENH] verbose CI/CD test for mac and unix
In our current GitHub actions CI/CD, the windows tests are verbose, i.e., logs per test are printed out, which is very useful for diagnosing on remote.

This is not the case for mac and unix (only "dots" are printed and percentages) - it would be great if it were.

Not sure what would have to be changed, but perhaps a good first issue for someone with CI/CD and/or GitHub actions experience.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
#### Reference Issues/PRs
Fixes #1947

#### What does this implement/fix? Explain your changes.
Adds verbose output to the tests running on `linux` and `macOS` in the `CI/CD` pipeline.

#### Does your contribution introduce a new dependency? If yes, which one?
--

#### What should a reviewer concentrate their feedback on?
--

#### Any other comments?
--

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Oh, we forgot the `-v` flag in the `Makefile`?
In hindsight, makes a lot of sense... I did get confused since `test.yml` does have it!

**Comment by fkiraly** [comment]
PS, feel free to add the `infra` tag if you'd like.

**Comment by Saransh-cpp** [comment]
> I did get confused since `test.yml` does have it!

Yes, this was confusing for me too. Took me some time to realize that `-v` was present only in the `Windows` test command. `Linux` and `macOS` tests were being executed using `make tests` which pointed me to the `Makefile`!
https://github.com/alan-turing-institute/sktime/blob/c02c0997123a5fdb4986817ed0765bc309cd6433/.github/workflows/test.yml#L120-L121

**Review by fkiraly — APPROVED** [review]
Thanks again!

**Pull request merged**
