### PR TITLE
Add example to _tsf.py

### PR DESCRIPTION
**Pull request by tabhishek432**
Adding Example to _tsf.py (TimeSeriesForestClassifier)
    Example
    ----------
    >>> from sktime.classification.interval_based import TimeSeriesForestClassifier
    >>> from sklearn.model_selection import train_test_split
    >>> from sktime.datasets import load_arrow_head
    >>> X, y = load_arrow_head(return_X_y=True)
    >>> X_train, X_test, y_train, y_test = train_test_split(X, y)
    >>> clf = TimeSeriesForestClassifier(n_estimators=100)
    >>> clf.fit(X_train, y_train)
    >>> clf.score(X_test, y_test)

#### Reference Issues/PRs
Fixing #932

#### What does this implement/fix? Explain your changes.
An example of fixing the issue #932

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

If example is written properly

#### Any other comments?
No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by tabhishek432** [comment]
Hi, Can anyone please explain why the three checks above failed?

**Review by mloning — APPROVED** [review]

**Review by mloning — APPROVED** [review]
Thanks @tabhishek432 - changes look good, but I'd suggest you set up the dev environment for the correct formatting with pre-commit.

**Comment by TonyBagnall** [comment]
hi @tabhishek432, I'm hoousekeeping. This has been inactive for some time, can I close it? Happy to reopen later if you want to continue

**Comment by RNKuhns** [comment]
@TonyBagnall I think it is probably okay to close this one for now.

**Pull request closed without merging**
