### PR TITLE
Feature & Performance improvements of SFA/WEASEL

### PR DESCRIPTION
**Pull request by patrickzib**
This pull requests adds some features and performance improvements for SFA:

- fixed Chi-squared test for WEASEL
- add kmeans discretization for SFA
- fixed handling of std-dev in SFA
- add joblib parallelization for WEASEL
- add skip-grams to SFA
- minor bugfixes

### CODE REVIEW

**Comment by mloning** [comment]
Hi @patrickzib, thanks again for the updates! Please ignore the current failure on manylinux1 (see #456), will hopefully sort it out later today!

**Comment by patrickzib** [comment]
@mloning ok, thank you :)  I was wondering what is going wrong.

**Review by TonyBagnall — APPROVED** [review]
all looks good to me

**Comment by TonyBagnall** [comment]
This is fine, Markus is just sorting out some Dev ops issues!

**Review by mloning — APPROVED** [review]

**Comment by patrickzib** [comment]
thank you :)

**Pull request merged**
