### PR TITLE
[DOC] Added example to plot_series & fixed example for plot_lags

### PR DESCRIPTION
**Pull request by shagn**
This PR adds an example for the `plot_series` function and adds a missing import statement for the example of `plot_lags`.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Comment by fkiraly** [comment]
thanks!

**Review by fkiraly — DISMISSED** [review]

**Comment by fkiraly** [comment]
looks ok, but still a draft.

We could merge it like that. Or, suggestions:
* add yourself to the contributors file, all-contsributorsrc
* add a line of explanation in the `all_estimators` example, what does it do?

**Comment by shagn** [comment]
Sure, I will do that

**Comment by shagn** [comment]
I just realised I made a mistake. I did merge the main branch of sktime directly and now the meanwhile introduced changes are also shown. I am not sure how to untangle that the best way... I will have a look tomorrow.

**Comment by fkiraly** [comment]
??

merging regularly from `main` to keep your PR branch updated is what you are expected to do in best practice GitHub flow, so all is good!

**Review by fkiraly — APPROVED** [review]
Looks good, thanks a lot!

**Comment by shagn** [comment]
Yes, I know. But I thought I should have done it differently, but it is fine. Sorry for the confusion @fkiraly.

**Comment by fkiraly** [comment]
no probs, all great, and thanks for your contribution!

**Pull request merged**
