### PR TITLE
[MNT] Remove hcrystalball dependency

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
#2675 

#### What does this implement/fix? Explain your changes.
Remove `hcrystalball `. To be merged before release v0.13.0 and after v0.12.0

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
I think `hcrystalball` interfaces are still useful (as interfaces) and we don't have a good reason to remove them except arguments of taste and/or popularity.

We should at least tag the maintainers of `hcrystalball` to inform them and give them an opportunity to contribute to the discussion.

I would be in favour of not remove a working module that might be useful to some.

**Comment by aiwalter** [comment]
See referenced PR. @MichalChromcak I pinged you on Slack some days ago

**Comment by aiwalter** [comment]
Which changes are requested? @fkiraly

**Comment by fkiraly** [comment]
>Which changes are requested? @fkiraly

First instance, making aware and giving an opportunity to comment, to users of this and to `hcrystalball` devs.

**Comment by aiwalter** [comment]
Sure everybody can comment, but then its not a change request

**Comment by MichalChromcak** [comment]
> See referenced PR. @MichalChromcak I pinged you on Slack some days ago

Sorry @aiwalter, I don't see the message anywhere. Which space this slack message went into?

> I think `hcrystalball` interfaces are still useful (as interfaces) and we don't have a good reason to remove them except arguments of taste and/or popularity.
> 
> We should at least tag the maintainers of `hcrystalball` to inform them and give them an opportunity to contribute to the discussion.
> 
> I would be in favour of not remove a working module that might be useful to some.

I would also be interested in the reasons why it should be removed - are there any issues with it? 

Regarding the transfer of the logic to `hcrystalball` - the logic seems to me close to having `sktime` wrapper in facebook's `prophet` code base, yet I believe the idea of the relationship should rather be vice-versa (if I want to use some tool, I write a wrapper/adapter for it).

**Comment by aiwalter** [comment]
> Sorry @aiwalter, I don't see the message anywhere. Which space this slack message went into?

This was at `sktime` Slack space.

> I would also be interested in the reasons why it should be removed - are there any issues with it?


Just to give a bit background, there was a core developer vote about deprecating `hcrystalball`. The reasons are mainly:
- The models that are covered in `hcrystalball` are now all directly availbale in `sktime`, so no need to wrap them again via `hcrystalball`.
- We couldnt see other features that are available in `hcrystalball` that we dont have.
- Minimizing our dependencies

> Regarding the transfer of the logic to hcrystalball - the logic seems to me close to having sktime wrapper in facebook's prophet code base, yet I believe the idea of the relationship should rather be vice-versa (if I want to use some tool, I write a wrapper/adapter for it).

This is not correct bcz `prophet` implements a particular algorithm whereas `hcrystalball` is just wrapping to other algorithms similar as `sktime` also does for some models. In the longer strategy, we however try to aim for that other packages provide interface to `sktime` on their end similar to `sklearn` where `keras`, `xgboos` or `light-gbm` provide `sklearn` interfaces.

Let me know if I can help with the [issue ](https://github.com/heidelbergcement/hcrystalball/issues/71) I opened on your repo.

**Comment by aiwalter** [comment]
well I dont want do discuss this again and again, there was a core dev vote on it. Othwerwise we can just stop voting and @fkiraly will always decide what to do

**Comment by fkiraly** [comment]
> well I dont want do discuss this again and again, there was a core dev vote on it. Othwerwise we can just stop voting and @fkiraly will always decide what to do

@aiwalter, we need to follow process.

We have not voted on this formally. Especially in a case like this we should follow our own rules and not handwave through them.

Excerpt from our rules:

image

Vote needs to be announced *in public*. People need to cast votes *in public*.

https://www.sktime.org/en/latest/get_involved/governance.html#stage-2-voting

Ok?

Next steps we would need to do:

* announce the vote start/end time here, and inform the core developers
* then core developers cast votes
* 2/3 of votes cast, including yours, wins

**Comment by aiwalter** [comment]
there already was a vote on core dev channel, I only didnt write the end date. As we usually do this 1 week, this is already more than a week ago.

**Comment by fkiraly** [comment]
*start and end time must be announced in the core dev channel and on the PR*

That should also allow for third parties to chime in with arguments, e.g., @MichalChromcak, or users of the `hcrystalball` plugin.

> there already was a vote on core dev channel

*votes take place on the related public issue or pull request*

A secret vote is, hence, at most an indicative vote.

**Comment by aiwalter** [comment]
Why should the vote be public? We never voted public. Also all your core dev appointment votes were not public

**Comment by fkiraly** [comment]
I have now announced the vote on the sktime/core-developers channel. It will end 6pm UTC on May 30.

If I'm outvoted, as in the indicative internal vote, I will of course accept the result and deprecating `hcrystalball` is what we do.

**Comment by MichalChromcak** [comment]
> > Sorry @aiwalter, I don't see the message anywhere. Which space this slack message went into?
> 
> This was at `sktime` Slack space.
> 
> > I would also be interested in the reasons why it should be removed - are there any issues with it?
> 
> Just to give a bit background, there was a core developer vote about deprecating `hcrystalball`. The reasons are mainly:
> 
> * The models that are covered in `hcrystalball` are now all directly availbale in `sktime`, so no need to wrap them again via `hcrystalball`.
> * We couldnt see other features that are available in `hcrystalball` that we dont have.
> * Minimizing our dependencies
> 
> > Regarding the transfer of the logic to hcrystalball - the logic seems to me close to having sktime wrapper in facebook's prophet code base, yet I believe the idea of the relationship should rather be vice-versa (if I want to use some tool, I write a wrapper/adapter for it).
> 
> This is not correct bcz `prophet` implements a particular algorithm whereas `hcrystalball` is just wrapping to other algorithms similar as `sktime` also does for some models. In the longer strategy, we however try to aim for that other packages provide interface to `sktime` on their end similar to `sklearn` where `keras`, `xgboos` or `light-gbm` provide `sklearn` interfaces.
> 
> Let me know if I can help with the [issue ](https://github.com/heidelbergcement/hcrystalball/issues/71) I opened on your repo.

@aiwalter thank you for the clarification. I understand the reasons and also the long term strategy. I am not certain when I will find time to do the move and proper testing though.

**Comment by MichalChromcak** [comment]
> I have now announced the vote on the sktime/core-developers channel. It will end 6pm UTC on May 30.
> 
> If I'm outvoted in the formal vote according to our governance document (as in the indicative internal vote), I will of course accept the result and deprecating `hcrystalball` is what we do.

@fkiraly thank you for trying to make things as much transparent as possible. I better understand the motivation now and will follow the decision which sktime core devs make.

**Comment by aiwalter** [comment]
carrying over 6 votes from Slack:
image

**Comment by fkiraly** [comment]
@aiwalter, this only counts if @Lovkush-A, @lmmentel, @TonyBagnall, @GuzalBulatova, @MatthewMiddlehurst confirm before the end of the vote that it is meant as a +1 (support)

**Comment by MatthewMiddlehurst** [comment]
confirmed

**Comment by TonyBagnall** [comment]
confirmed, how are you actually meant to vote? Just comment here?

**Comment by chrisholder** [comment]
Im also voting in favour of this issue - remove hcrystalball dependency

**Comment by Lovkush-A** [comment]
confirmed

**Comment by Lovkush-A** [comment]
> The logic would be the same as saying "let's destroy all US-to-EU power plug adapters", based on the observation that there are EU washing machines, EU toasters, EU microwaves, EU TV sets.

I think the logic is more like this: there is a third country (india, say) which produces washing machines. if I am in the EU, all I need is an india to EU adapter. I would not use an india to US and then US to EU adapter.

**Comment by GuzalBulatova** [comment]
I confirm, let's remove the hcrystalball dependency

**Comment by Lovkush-A** [comment]
> Wait, I did not understand the analogy here. Can you kindly outline your argument?

- washing machines produced by india = prophet produced by facebook.
- sktime = EU. sktime has wrapper for prophet = we have india to EU adapter.
- hcrystalball = US. hcrystalball has wrapper for prophet = they have india to US adapter.

the argument: why do we need a wrapper for hcrystalball, when we already wrap the things they wrap? In the analogy: why would i import an indian washing machine from the US, instead of directly from the india (given that I have india to EU adapters)?

key assumption: the things we want to wrap in hcrystalball, we now wrap directly in sktime / implement directly in sktime. they currently wrap prophet, sarimax, sklearn, statsmodel and tbats. https://github.com/heidelbergcement/hcrystalball/tree/master/src/hcrystalball/wrappers.

**Comment by fkiraly** [comment]
> the argument: why do we need a wrapper for hcrystalball, when we already wrap the things they wrap? In the analogy: why would i import an indian washing machine from the US, instead of directly from the india (given that I have india to EU adapters)?

Maybe you got a discount on indian washing machines, or you have inherited them from your grandparents. Maybe the indian washing machine brand has the specific feature you need.

= maybe you are already running a deployment where components follow the hcrystalball interface. Maybe you need to rely on components that work specifically with hcrystalball interface.

Generally, one wants to avoid using power plug adapters, but they exist because they have their uses.

That you want to avoid using them does not mean they should be purged from existence, because you might need them.

**Comment by Lovkush-A** [comment]
> Maybe you got a discount on indian washing machines, or you have inherited them from your grandparents. Maybe the indian washing machine brand has the specific feature you need.

I think you have misunderstood my analogy. The choice is between using *two power plugs* (india to US *and* US to EU) rather than one (india to EU). The functionality, an indian washing machine, is constant. (indian washing machine = facebook prophet in my analogy)

> Having said that, I don't want to invest time in reviewing and listing functionality that they have and we don't vs functionality we have and they don't.

I think this is precisely what you need to do to argue that adapter is worth keeping. (Actually, all you need to do is find *one* example, which you have not yet done.)

Anyway, i looked at this PR and the only thing we were wrapping from hcrystalball were their forecasters. Furthermore, as far as I can tell, everything hcrystalball can do with forecasters, we can do too. My question is: why would an end user want to create something in hcrystalball and *then* wrap it in sktime, rather than just creating it in sktime directly.

**Comment by fkiraly** [comment]
>I think this is precisely what you need to do to argue that adapter is worth keeping. 

Alright, since you insist.

`hcrystalball` has a holiday transformer, `sktime` does not have a holiday transformer.
https://github.com/heidelbergcement/hcrystalball/blob/master/src/hcrystalball/feature_extraction/_holiday_transformer.py
https://github.com/alan-turing-institute/sktime/issues/1675

`hcrystalball` has a wrapper of `statsmodels` `ThetaModel` and `Holt`,  which `sktime` does not have
https://github.com/heidelbergcement/hcrystalball/blob/master/src/hcrystalball/wrappers/_statsmodels.py
(the `sktime` theta model is a custom implementation, not an interface to the `statsmodels` one)

**Comment by fkiraly** [comment]
> My question is: why would an end user want to create something in hcrystalball and then wrap it in sktime, rather than just creating it in sktime directly.

Maybe they like the `hcrystalball` interface better, but want access to some `sktime` functionality, like benchmarking. Maybe they have legacy code they open source, and it's a really useful estimator, but they don't have the time to invest to change the interfaces. Maybe it's a new feature that will be released in 2023.

**Comment by fkiraly** [comment]
(just to ensure formal correctness here: I'm still *against* this PR. Outvoted at the moment, but for the record)

**Comment by Lovkush-A** [comment]
Alright, thanks for giving the couple of examples, Franz. Having those explicit examples does reduce the conviction with which I say 'yes' to this PR, but does not change it.

**Comment by fkiraly** [comment]
> I have now announced the vote on the sktime/core-developers channel. It will end 6pm UTC on May 30.

For the record, the vote has ended with a larger than 2/3 majority in favour of this PR.
@aiwalter, if you would like to merge this, you no longer need to consider my change request blocking.

**Comment by aiwalter** [comment]
We have to merge it after next release, gling to merge the deprecation warning PR now

**Comment by fkiraly** [comment]
> We have to merge it after next release, gling to merge the deprecation warning PR now

Ah, makes sense. Let´s ensure we schedule this as a "must have" for 0.13.0.
It should appear when searching the code for the string `0.13.0` due to deprecation in the other PR.

**Review by lmmentel — APPROVED** [review]

**Pull request merged**
