### PR TITLE
[BUG] TESTING branch to reproduce proximity forest test bug

### PR DESCRIPTION
**Pull request by fkiraly**
TESTING - NOT FOR MERGE

This PR is for convenience to reproduce the proximity forest test bug discussed in #1114, arising from #1026.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
@MatthewMiddlehurst is just pushing a change to proximity forest to refactor, and has we think fixed this problem https://github.com/alan-turing-institute/sktime/issues/598
I'll revisit all the distance based problems when the refactor is finished

**Comment by mloning** [comment]
Can this be closed?

**Comment by TonyBagnall** [comment]
Leave it for now, we are hopefully getting to PF soon

**Comment by TonyBagnall** [comment]
This PR cannot now be run since it uses the cython vesion. I think the problem is fixed, I just put PF back into the orchestration test, and it passed.

**Pull request closed without merging**
