### PR TITLE
[ENH] Dictionary classifiers speedup

### PR DESCRIPTION
**Pull request by patrickzib**
#### What does this implement/fix? Explain your changes.

This implements:
- Parallelization for the predict methods for WEASEL and MUSE.
- Parallelization for MUSE in fit()
- Small bug with WEASEL in feature selection (wrong indent)

### CODE REVIEW

**Review by MatthewMiddlehurst — APPROVED** [review]

**Comment by MatthewMiddlehurst** [comment]
Sorry this took so long to look at, changes look good to me.

I have restarted the failed test, it seems unrelated to this PR.

**Comment by patrickzib** [comment]
@MatthewMiddlehurst that is just fine. Thanks for looking into it. There seems to be an issue with Forecasting right now anyways?

**Review by fkiraly — CHANGES_REQUESTED** [review]
Not sure where this is coming from, but the test failure seems like the pmdarima issue.
I thought that was solved, kindly check that all tests pass on updated `main`.

**Comment by MatthewMiddlehurst** [comment]
Oh dear, the only one failing when I restarted it was a single catch22 test. Will merge main into this and see if it fixes.

**Pull request merged**
