### PR TITLE
[DOC] fix docstring in Feature Union

### PR DESCRIPTION
**Pull request by AreloTanoh**
#### Reference Issues/PRs
See #1148 

#### What does this implement/fix? Explain your changes.
* Fixed rendering on docstring
* Added description of "preserve_dataframe"  argument.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by AreloTanoh** [comment]
@mloning, seems all pre-commit checks are OK. Awaiting your approval

**Comment by AreloTanoh** [comment]
PR runs keep failing

**Review by fkiraly — APPROVED** [review]
Looks good, failure is appveyor which is acting up again for no reason (nothing to do with your additions).

**Review by mloning — APPROVED** [review]
Yes good work @AreloTanoh!

**Pull request merged**
