### PR TITLE
[MNT] Update codecov github action from v2 to v3

### PR DESCRIPTION
**Pull request by miraep8**
Just trying some stuff out.  Will ping if it works.

### CODE REVIEW

**Comment by miraep8** [comment]
Seems like codecov is passing on simple test with v3 instead of v2.  I am adding back all the other tests I deleted just to see if the version change addressed the codecov problem, so lets see if that works

**Comment by fkiraly** [comment]
it works again, but maybe we still like to change the version

**Comment by miraep8** [comment]
They probably re-requested certifications! :) But yea, from what I can tell a lot of the "breaking changes" from v2 to v3 aren't really relevant to us, and seems like the packages are more up to date in v3 vs v2?

**Comment by fkiraly** [comment]
> But yea, from what I can tell a lot of the "breaking changes" from v2 to v3 aren't really relevant to us, and seems like the packages are more up to date in v3 vs v2?

The latter would be an argument to upgrade. The argument to not upgrade is "don´t change a working setup", but we also know via CI that v3 is working too. Thoughts, @lmmentel, @freddyaboulton?

**Review by lmmentel — APPROVED** [review]

**Comment by lmmentel** [comment]
Let's merge it.

**Pull request merged**
