### PR TITLE
[BUG] remove `alpha` arg from `_boxcox`, remove private method dependencies, ensure scipy 1.8.0 compatibility

### PR DESCRIPTION
**Pull request by fkiraly**
This PR fixes https://github.com/alan-turing-institute/sktime/issues/1994, what I think is the last issue that prevents sktime from being compatible with `scipy` 1.8.0.

The fix is to remove the otherwise unused `alpha` arg from `_boxcox`, which allows to remove the `_boxcox_conf_interval dependency` entirely

### CODE REVIEW

**Comment by fkiraly** [comment]
This PR fixes https://github.com/alan-turing-institute/sktime/issues/1994, what I think is the last issue that prevents sktime from being compatible with `scipy` 1.8.0.

The fix consists of the following:
* remove the otherwise unused `alpha` arg from `_boxcox`, which allows to remove the `_boxcox_conf_interval dependency` entirely
* move the imported `_calc_uniform_order_statistic_medians` which is no longer available from `scipy` 1.8.0 onwards into `sktime`

**Review by lmmentel — APPROVED** [review]
LGTM

**Comment by fkiraly** [comment]
tests don't run yet - why is everything stuck, @lmmentel?

**Comment by lmmentel** [comment]
There was an incident with GHA recently which might've created a queue? :shrug:

**Pull request merged**
