### PR TITLE
[MNT] Add shellcheck to pre-commit

### PR DESCRIPTION
**Pull request by mloning**
#### What does this implement/fix? Explain your changes.
- yml formatting to precommit-config
- add shellcheck to precommit
- update precommit
- run shellcheck on shell scripts

#### Does your contribution introduce a new dependency? If yes, which one?
Just a pre-commit dependency:
* https://github.com/shellcheck-py/shellcheck-py
* https://github.com/koalaman/shellcheck (web version: https://github.com/koalaman/shellcheck)

#### Comments
* VS Code extension: https://github.com/vscode-shellcheck/vscode-shellcheck

### CODE REVIEW

**Comment by mloning** [comment]
This improves shell scripts, this is ready to go in - perhaps someone you could find someone to review @fkiraly?

**Comment by fkiraly** [comment]
looks straightforward, may I quickly ask to confirm: is any diff besides adding `shellcheck` linting/formatting related?

**Comment by fkiraly** [comment]
looks ok to me - @lmmentel, can you kindly have a look at this, whether there would be any problems with your refactor?

**Comment by lmmentel** [comment]
Looks good to me, and it shouldn't affect anything that I've touched so far.

**Review by chrisholder — APPROVED** [review]

**Pull request merged**
