### PR TITLE
HIVE-COTE 1.0 fix

### PR DESCRIPTION
**Pull request by MatthewMiddlehurst**
Fixes to the HIVE-COTE 1.0 classifier and additional functionality. See #674.

Documentation updates for other classifiers.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
so HC doesnt coerce to numpy, but each component does? Do they do it differently?

**Review by TonyBagnall — APPROVED** [review]

**Review by mloning — APPROVED** [review]
Thanks @MatthewMiddlehurst for the quick fixes!

**Comment by MJimitater** [comment]
Thanks @MatthewMiddlehurst for the fixes! 
Can this be merged yet?

**Comment by MJimitater** [comment]
Dear @mloning , @TonyBagnall and @MatthewMiddlehurst , thank you for your quick support on this issue!
I tested it, the execution on my small dataset (500x10) now doesn't run limitlessly +30h anymore and there are some verbose outputs! So thanks again!!

hive_cote_1

**Pull request merged**
