### PR TITLE
[ENH] make _fit and _predict abstract in BaseClassifier

### LINKED ISSUE #1708: [ENH] Make BaseClassifier abstract with ABC
**Is your feature request related to a problem? Please describe.**

both _fit and _predict should be properly abstract using ABC, rather than just raising an error. 

This cannot be done until all classifiers conform to _fit/fit model. This is linked here

- #1609
- #1608
- #1607
- #1606

this is complicated by the fact that it seems TimeSeriesForestClassifier is used in annotation, benchmarking, forecasting, series_as_features, transformations and utils.

### PR DESCRIPTION
**Pull request by TonyBagnall**
this PR makes _fit and _predict abstract with ABC, and nothing else.

#### Reference Issues/PRs
fixes #1708

#### What does this implement/fix? Explain your changes.

 I do not think this is contentious or requires a core developer meeting to approve, for the following reasons

1. The methods are already conceptually abstract, this just allows us to enforce it, implicitly checking all classifiers properly extend the base class. There is no design change. 
2. Using ABC is a completely standard way of making abstract methods in python.
3. ABC is already used in forecasting, benchmarking, clustering and distances. 

any debate about possible other uses of ABC, or changes in the current design utilising ABC, are, in my opinion, secondary to this PR.

#### Does your contribution introduce a new dependency? If yes, which one?

no

### CODE REVIEW

**Review by chrisholder — APPROVED** [review]

**Review by fkiraly — DISMISSED** [review]
apologies for blocking this.

I feel a little contentious and wouldn´t like to move `ABC` in too quickly in a stable module.
I would like to understand the answers to my questions in https://github.com/alan-turing-institute/sktime/issues/1923 first.

Downwards compatibility is quite important, and I can't fully grasp the consequences currently.

Would you mind, at least, doing it after 0.10.0, where we have more time to deal with unintended consequences if arising?

**Comment by fkiraly** [comment]
Re contention:

> I do not think this is contentious or requires a core developer meeting to approve, for the following reasons

Well, contention is subjective, but also quite clearly defined via people having different opinions...

> The methods are already conceptually abstract, this just allows us to enforce it, implicitly checking all classifiers properly extend the base class. There is no design change.

I do think there is - it's subtle, but it's one: a change of decoration vs default method with error handling.
Does not need to be bad - see #1923, could we discuss these Q please?

> Using ABC is a completely standard way of making abstract methods in python.

Yes, and so is the current, implicit way of defining abstract methods.

> ABC is already used in benchmarking, clustering and distances.

These are unstable/experimental modules, while classification and forecasting are stable, and do not use ABC.
I feel we need to be more careful with changes to the stable modules.
The base class inheritance tree is so fundamental that we really can't take a chance to get this wrong imo.

**Comment by TonyBagnall** [comment]
> Re contention:
> 
> > I do not think this is contentious or requires a core developer meeting to approve, for the following reasons
> 
> Well, contention is subjective, but also quite clearly defined via people having different opinions...
> 
> > The methods are already conceptually abstract, this just allows us to enforce it, implicitly checking all classifiers properly extend the base class. There is no design change.
> 
> I do think there is - it's subtle, but it's one: a change of decoration vs default method with error handling. Does not need to be bad - see #1923, could we discuss these Q please?
> 
> > Using ABC is a completely standard way of making abstract methods in python.
> 
> Yes, and so is the current, implicit way of defining abstract methods.
> 
> > ABC is already used in benchmarking, clustering and distances.
> 
> These are unstable/experimental modules, while classification and forecasting are stable, and do not use ABC. I feel we need to be more careful with changes to the stable modules. The base class inheritance tree is so fundamental that we really can't take a chance to get this wrong imo.

I have honestly nothing else to add, other than I think properly abstract methods are better than skeletons that raise errors. I think 99% of programmers would agree with me. But I guess it is not very important. I'll close this and the related issue, if you change your mind let me know

**Comment by fkiraly** [comment]
> I'll close this and the related issue, if you change your mind let me know

I would very much appreciate to hear what you think about the points I raised in #1923.
I´m not against the idea in general, but would like to have a discussion first.
I've put a couple points in #1923, I hope it isn't too much to ask to engage in discussion about a PR before we merge it?

**Review by lmmentel — APPROVED** [review]

**Review by fkiraly — APPROVED** [review]
Happy with this after our discussion - but why do the mac tests fail?

**Comment by TonyBagnall** [comment]
> Happy with this after our discussion - but why do the mac tests fail?

I cancelled the tests until some other minor PRs go in, will sort it tomorrow

**Pull request merged**
