### PR TITLE
[ENH] TWE switch to use euclidean distance

### PR DESCRIPTION
**Pull request by chrisholder**
#### What does this implement/fix? Explain your changes.

This pr switches the distance metric TWE uses to euclidean. This is because the minkowski distance (original proposed for use with TWE) was causing issues with large datasets. Therefore Euclidean is now being used.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Why not, but you need to deprecate due to a change in default.

**Comment by TonyBagnall** [comment]
I would not use **2 to square I think it may be slow on numba

**Review by TonyBagnall — APPROVED** [review]

**Comment by TonyBagnall** [comment]
> Why not, but you need to deprecate due to a change in default.

also dont think TWE is in 11.0 anyway

**Comment by TonyBagnall** [comment]
> oh, is it experimental? How do I see that?

You classified distances module as experimental this not needing deprecation. If you insist I'll add back parameter but it's holding up experiments I want to set off over the weekend

**Comment by TonyBagnall** [comment]
I'm going to put this in when it passes as I need to set them off, unless @fkiraly seriously objects

**Comment by fkiraly** [comment]
> You classified distances module as experimental thus not needing deprecation. If you insist I'll add back parameter but it's holding up experiments I want to set off over the weekend

Yes, you are right, @TonyBagnall! Just checked.
Consider my comment non-blocking then.

**Comment by TonyBagnall** [comment]
> > You classified distances module as experimental thus not needing deprecation. If you insist I'll add back parameter but it's holding up experiments I want to set off over the weekend
> 
> Yes, you are right, @TonyBagnall! Just checked. Consider my comment non-blocking then.

Thanks, could you unblock this or then please?

**Pull request merged**
