### PR TITLE
Add basic parallel support for `ElasticEnsemble`

### PR DESCRIPTION
**Pull request by xuyxu**
#### What does this implement/fix? Explain your changes.

* This PR improves the training efficiency of `sktime.classification.distance_based.ElasticEnsemble` by ingesting `n_jobs` to the internal grid search module, which is a valid input [(See explaination)](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) but not added in the current  implementation.

* This PR also coverts the docstrings into Numpy style for better readability on Readthedocs.

#### Does your contribution introduce a new dependency? If yes, which one?

No.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).

### CODE REVIEW

**Comment by AaronX121** [comment]
Hi  @TonyBagnall @jasonlines @mloning, congratulations on the version 0.5! I would like to ask that whether this PR meets the requirement ? If not, I will close it :-)

**Comment by mloning** [comment]
@AaronX121 Thanks for the PR - I think they are just very busy at the moment and will come back to you soon if you leave it open a bit longer.

**Comment by AaronX121** [comment]
> @AaronX121 Thanks for the PR - I think they are just very busy at the moment and will come back to you soon if you leave it open a bit longer.

Thanks for your reply @mloning

**Review by TonyBagnall — APPROVED** [review]
hi, looks good to me, I've just asked george and jason to take a look, so maybe leave it a bit before merging

**Comment by AaronX121** [comment]
Thanks! @TonyBagnall

**Comment by mloning** [comment]
@TonyBagnall so can I merge this?

**Comment by mloning** [comment]
Now merged - thanks again @xuyxu for the PR!

**Comment by xuyxu** [comment]
Great! Thanks all of you for your efforts @TonyBagnall, @mloning :-)

**Pull request merged**
