### PR TITLE
[ENH] test for correct return type of `load_basic_motions`

### PR DESCRIPTION
**Pull request by fkiraly**
Under `pandas 1.5.0`, it seems that `load_basic_motions` returns a non-mtype-compliant object for `nested_univ` return, see https://github.com/alan-turing-institute/sktime/actions/runs/3101253841/jobs/5022506912.

This is not caught by a dedicated test but only by accident, because we did not test this.

Oddly, the test for the generic loader `_load_provided_datast` seems to pass.

To diagnose this further and to improve test coverage, I have added a test for `load_basic_motions`.

Contains bugfix #3463 as this change uncovers a bug in the case where `return_X_y=True` and scalar columns are present.

FYI @achieveordie, you worked on these a while ago - any good ideas? This seems to be the last issue with `pandas` 1.5.0.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
I ran into this yesterday with a new install of version sktime 0.13.2
image
for me it is happening when resampling, the experiment on the default resample works fine. load_basic_motions also merges the data, so it has to be something with combining dataframes. It does not happen with sktime version 0.12.0 (just verified this, and I have run through newarly all classifiers/datasets with 0.12). I will look closer now

**Comment by TonyBagnall** [comment]
I cant reproduce precisely atm as an experiment is running on the machine where it occurs and its fine with pandas 1.4.2. I'll look closer but I suspect it is related to pd.concat, which is used in both _load_provided_dataset (when TRAIN or TEST are not specified)
        # extract data from corresponding indices
        train_instances = all_data.iloc[train_indices, :]
        test_instances = all_data.iloc[test_indices, :]
        train_labels = all_labels[train_indices]
        test_labels = all_labels[test_indices]
        # concat onto current data from previous loop iterations
        X_train = pd.concat([X_train, train_instances])
        X_test = pd.concat([X_test, test_instances])

 and in resample
        # take the first lot of instances for train, remainder for test
        train_indices = indices[0:num_instances]
        test_indices = indices[num_instances:]
        del indices  # just to make sure it's not used!
        # extract data from corresponding indices
        train_instances = all_data.iloc[train_indices, :]
        test_instances = all_data.iloc[test_indices, :]
        train_labels = all_labels[train_indices]
        test_labels = all_labels[test_indices]
        # concat onto current data from previous loop iterations
        X_train = pd.concat([X_train, train_instances])
        X_test = pd.concat([X_test, test_instances])

**Comment by TonyBagnall** [comment]
I can reproduce this error with pandas 1.4.4 and sktime 13.1, works with version 13.0.  I'm not sure what changed in the datatypes module, but I believe all other code was the same between versions

```python
from sktime.datasets import load_basic_motions
from sktime.datasets import load_from_tsfile_to_dataframe
from sktime.utils.sampling import stratified_resample
from sktime.classification.kernel_based import RocketClassifier
X, y = load_basic_motions()
trX, trY = load_from_tsfile_to_dataframe(
    full_file_path_and_name="C:\Code\sktime\sktime\datasets\data\BasicMotions"
                            "\BasicMotions_TRAIN.ts")
testX, testY = load_from_tsfile_to_dataframe(
    full_file_path_and_name="C:\Code\sktime\sktime\datasets\data\BasicMotions"
                            "\BasicMotions_TEST.ts")

newTrainX, newTrainY, newTestX,newTestY = stratified_resample(
                trX, trY, testX, testY, 2)
from sktime.datatypes import check_is_mtype, MTYPE_LIST_PANEL
from sktime.datatypes._panel._registry import MTYPE_REGISTER_PANEL
print(MTYPE_LIST_PANEL)
print(MTYPE_REGISTER_PANEL)
cls = RocketClassifier()
cls.fit(trX, trY)
p1 = cls.predict(testX)
cls.fit(newTrainX, newTrainY)
p2 = cls.predict(newTestX)
cls.fit(X,y)
print(p1.shape)
print(p2.shape)
print(p3.shape)
```
working version, sktime 13.0
image


datatypes error thrown versions 13.1
image

**Comment by TonyBagnall** [comment]
Internally, it seems a bit odd, since check_is_scitype is failing a standard dataframe. This is the one check_is_scitype passes

image

and this one fails! 

image

seems there is problem in check_is_scitype introduced between 13.0 and 13.1

**Comment by fkiraly** [comment]
@TonyBagnall, can you elaborate what makes you think it is the checker and not the loader where something has changed? Both have dependencies that could have changed, and direct changes.

**Comment by TonyBagnall** [comment]
> 

my thinking on why its the datatypes: the data is loaded correctly into a dataframe, it all looks fine before it is passed to the classifier (and internally (see debugger); the bug is caused by resampling an already loaded dataframe, and resampling has not to my knowledge changed; it seems unlikely the loaders would have changed much between 13.0 and 13.1. I'm afraid that I'm not sure what changed from 13.0 to 13.1, that would narrow it down

**Review by khrapovs — APPROVED** [review]

**Comment by TonyBagnall** [comment]
bug recreated without a data loader https://github.com/alan-turing-institute/sktime/issues/3471

**Pull request merged**
