### PR TITLE
Fix MultiplexForecaster example

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
#821

### CODE REVIEW

**Comment by ngupta23** [comment]
By the way `pmdarima` had a new release today so that is breaking a lot of stuff for us as well for `pycaret`. We got the same error messages from our CI.

**Comment by aiwalter** [comment]
@ngupta23 thx for letting me know, however there is also an other issue @mloning . Seems since the last CI/CD changes, I cant edit a notebook as it starts looking for the kernel I was running it and then fails?
```
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python373jvsc74a57bd06578b10b79245f195e9cdbb1f9e6d50322bfd49c7734f1c30ca23249261b6bde
```
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by aiwalter** [comment]
@ngupta23 
opened a bug issue at `pmdarima`:
https://github.com/alkaline-ml/pmdarima/issues/423
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Review by mloning — APPROVED** [review]

**Comment by aiwalter** [comment]
I tried to use Jupyter directly instead of the VSCode integration, however the kernel issue remains.
___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by mloning** [comment]
@aiwalter is this still relevant or can we close it? Let me know if I can help in any way.

**Comment by aiwalter** [comment]
I tried to change sth in the notebook, but seems there is an issue. We can also close it, its not so important 😅

**Pull request closed without merging**
