### PR TITLE
[MrSEQL] Fix speed issue 

### PR DESCRIPTION
**Pull request by lnthach**
#### Reference Issues/PRs
See #264 

#### What does this implement/fix? Explain your changes.
Fix dataframe issue that slow down the symbolic transformation.

### CODE REVIEW

**Comment by mloning** [comment]
Thanks for the quick patch! 

One other question: Do you think MrSEQL rather belongs into the `sktime/classification/dictionary_based` submodule since it uses the SFA transform and so on, instead of the `shapelet_based` module?

**Comment by lnthach** [comment]
Indeed, from our point of view, it lies somewhere between the two groups because a SAX/SFA word can be seen as a shapelet as well. [This paper](https://arxiv.org/pdf/1911.12008.pdf) pointed out because Mr-SEQL based on the presence of absence of the words, it's more on the shapelet side:

`The only other candidate we know of for possible inclusion is Mr-SEQL [14].
Mr-SEQL uses words from sliding windows and discretisation in a dictionarylike way, but it is designed to classify based on the presence or absence of words
rather than their frequency. Thus it more properly belongs in the Shapelet
camp and shall appear in that chapter.`

**Comment by mloning** [comment]
Hi @lnthach, I'm confused about whether we need the `mrseql.cpp` file in git or whether we can ignore it (put it in `.gitignore`)? By the way, you're not on our slack, are you?

**Comment by lnthach** [comment]
Hi @mloning, I can confirm it's safe to ignore the file. It is produced by Cython when installing sktime in editable mode. Sorry I should put it in .gitignore myself.
No, I am not on your slack. But will be very happy to be included. My email is thach.lenguyen@insight-centre.org.

**Pull request merged**
