### PR TITLE
[ENH] Refactor dataset loader

### PR DESCRIPTION
**Pull request by achieveordie**
#### Reference Issues/PRs

As per #2697, reduced some boilerplate code in the loader functions

#### What does this implement/fix? Explain your changes.

- In the `_data_io.py` file,  Private functions `_load_provided_dataset()` and `_load_dataset()` were refactored in a manner that `_load_dataset()` takes care extraction of data and then calls the former to load the provided data.
- Only use `load_from_tsfile()` as the sole entrypoint. Initially, both `load_from_tsfile()` and `load_from_tsfile_to_dataframe()` were used in private functions mentioned above which is un-necessary since the former calls later anyways. This also gives more control over how data is to be returned.
- Owing to above changes, three default parameters were introduced in both functions combined. Namely, `return_type=None` in `load_dataset()` and `local_module`, `local_dirname` in `_load_provided_dataset()` with the default values as the global variable `MODULE` and `DIRNAME` respectively.

#### Does your contribution introduce a new dependency? If yes, which one?

None

#### What should a reviewer concentrate their feedback on?

None

#### Any other comments?

None

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Yes, this is exactly what I meant! Thanks!

Now, a minor - but still blocking - point:
you need to ensure you adhere to the code formatting requirements, or the CI tests will not run.

See here how you can set this up:
https://www.sktime.org/en/latest/developer_guide/coding_standards.html#setting-up-local-code-quality-checks

**Comment by achieveordie** [comment]
Apologies for having missed that before, all code format checks pass locally now.

**Comment by achieveordie** [comment]
Why are some builds failing, while some don't? @fkiraly Is there anything I can do regarding it?

**Comment by fkiraly** [comment]
> Why are some builds failing, while some don't? @fkiraly Is there anything I can do regarding it?

Might be this unrelated problem: https://github.com/alan-turing-institute/sktime/issues/3103

I´ll just restart the CI, let´s see

**Review by fkiraly — APPROVED** [review]
Nice contributionn, thanks!

**Pull request merged**
