### PR TITLE
[MNT] Add a script to generate changelog in rst format

### PR DESCRIPTION
**Pull request by lmmentel**
##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
Thank you! THANK YOU!

This was getting really tedious!

**Comment by fkiraly** [comment]
linting is failing, would be great to have this for next release

**Comment by lmmentel** [comment]
@fkiraly linting is passing but my local pre-commit is broken because of shellcheck-py so I sprinkled `# noqa` around the script instead of fixing the issues

**Review by fkiraly — APPROVED** [review]
Fine with me - this is for occasional use by developers, so no need for it to win a beauty contest.

**Pull request merged**
