### PR TITLE
Suggested changes to PR 912

### PR DESCRIPTION
**Pull request by mloning**
#### Reference Issues/PRs
#912

### CODE REVIEW

**Comment by mloning** [comment]
Hi @fkiraly, here are my suggested changes, let me know what you think!

**Comment by fkiraly** [comment]
I think this will mess up the tags, since assignments of the `_tags` class variable will override each other and not give you the set union of dictionary elements.

I would really really like to go with the current, working workaround, and we make changes like this later on?

**Comment by mloning** [comment]
@fkiraly I prefer this solution, this way, when we remove the mixins, we only have to copy the tags to the concrete forecasters,  plus we don't change the constructor. Note that tags are not overridden, that's handled in `_all_tags`.

**Comment by mloning** [comment]
@fkiraly this is part of your current work around, but introduces less unnecessary intermediate code and instead uses the tags as we would use them later, no?

**Comment by mloning** [comment]
So I suggest to merge this and then go ahead with the refactoring of the concrete forecasters.

**Comment by fkiraly** [comment]
hm, but then, you would have to change the "tags" inspection in `_set_fh` to `_all_tags`, no?

**Comment by mloning** [comment]
that's what's happening inside `_has_tag`

**Comment by fkiraly** [comment]
not sure I understand what you mean, but I mean that current line 524, `optfh = self._tags["fh_in_fit"] == "optional"` would have to use `_all_tags` instead, no?

**Comment by fkiraly** [comment]
oh, I see, that's already happening *inside* `_has_tag`, got it.

**Review by fkiraly — APPROVED** [review]
fine with this (see above)

**Comment by mloning** [comment]
I changed that line in this PR, take a look at the suggested changes in this PR. They would be merged into your branch. Does that help?

**Comment by fkiraly** [comment]
yes, I just overlooked the change in line 524, all fine

**Pull request merged**
