### PR TITLE
[ENH] Changing function names in datatypes check to lower_snake_case

### PR DESCRIPTION
**Pull request by chicken-biryani**
#### Reference 

Tries to fix Issues #1817 

#### What does this implement/fix? Explain your changes.

The pull request changes the names of the functions in datatypes to `lower_snake_case.`

#### Does your contribution introduce a new dependency? If yes, which one?

No it doesn't.

#### What should a reviewer concentrate their feedback on?

Please check whether the deprecation has been done properly. If there are any changes needed to be done for the same.

#### Any other comments?
--

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
> Couldn't find any private functions in check that aren't in lower_snake_case.

As discussed, there are a couple in the sub-folders, the `_check` modules.
(just recording here summary of our slack discussion)

**Comment by fkiraly** [comment]
Thanks, looks good!
Before I merge this: can you confirm that none of these functions is referenced outside the `datatypes` module?

**Comment by chicken-biryani** [comment]
@fkiraly I had a look. And no. The functions aren't referenced outside `datatypes`.

**Review by fkiraly — APPROVED** [review]
Alright, thanks!
Useful contribution!

**Pull request merged**
