### PR TITLE
[ENH] Elbow class selection/pairwise dimension selection for multivariate time series classification

### PR DESCRIPTION
**Pull request by TonyBagnall**
#### Reference Issues/PRs
This PR subsumes this one
https://github.com/alan-turing-institute/sktime/pull/1821
it is a joint effort between @a-pasos-ruiz and @haskarb. Draft PR, will add more details shortly. 

implementation of three dimension/channel selection algorithm sdescribed here
https://link.springer.com/chapter/10.1007/978-3-030-91445-5_3
algorithms named ECP/ECS and kmeans in the paper. These have been relocated to a file dimension_selection in transformations/panel, and will have classes ElbowChannelSelection, ElbowChannelPairwise and ClusterBasedChannelSelection.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [x ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
@TonyBagnall, I think you need to clean up the `_contrib` folder before you continue putting more random things in there.

When did that even start? Therer are duplications of data loading, random algorithms, and so on.

Please make a proposal of where things could go or what can be removed. We shouldn't be shipping this.

**Comment by fkiraly** [comment]
> We are moving to using a sub package model and reducing the content going into the main package, which I believe is the model you prefer and makes sense as sktime matures

Who is "we"? This seems to refer to major changes to `sktime` functionality, so it needs to be accompanied by a STEP and discussion with other core developers. You will also need to engage with core developers outside your research group.

**Comment by TonyBagnall** [comment]
@haskarb hi Bhaskar, your work is here, we still need to write tests and add to the documentation. Feel free to have a go and PR into this branch, otherwise, I'm away next week, but should be able to help out the week after

**Comment by fkiraly** [comment]
merged here now.
https://github.com/alan-turing-institute/sktime/pull/3248

**Pull request closed without merging**
