### PR TITLE
[ENH] [DOC] Execution of tests in Docker env

### PR DESCRIPTION
**Pull request by RISHIKESHAVAN**
#### What does this implement/fix? Explain your changes.
This PR contains the changes to enable execution of tests in a docker container in local. The documentation for the same have also been added.

#### What should a reviewer concentrate their feedback on?
- Makefile changes
- Documentation

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

### CODE REVIEW

**Comment by fkiraly** [comment]
Does this duplicate https://github.com/alan-turing-institute/sktime/pull/2249 ?

FYI @lmmentel

**Comment by RISHIKESHAVAN** [comment]
@fkiraly @lmmentel would it make sense to edit the GitHub workflows as well to execute the tests in docker containers if this change is fine?

**Comment by lmmentel** [comment]
> @fkiraly @lmmentel would it make sense to edit the GitHub workflows as well to execute the tests in docker containers if this change is fine?

Not sure I understand what you mean by this?

**Comment by lmmentel** [comment]
Can you say what benefits would there be over the current solution?

**Comment by RISHIKESHAVAN** [comment]
> Can you say what benefits would there be over the current solution?

I believe the workflow actions need to carry out testing in the same way that users do. And moving forward if the docker tests are going to be the way of executing tests then it is better for the workflows as well to do the same. Also, it will help in testing future changes to docker as well.

**Comment by RISHIKESHAVAN** [comment]
Will update the existing PR #2249 with the changes. Closing this.

**Pull request closed without merging**
