### PR TITLE
Add handling of exogeneous data to forecasting reductions

### PR DESCRIPTION
**Pull request by Lovkush-A**
#### Reference Issues/PRs

see #345 

#### What does this implement/fix? Explain your changes.

Allow reduction of forecasting to regression to handle exogenous data

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/master/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/master/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by Lovkush-A** [comment]
@mloning I have started creating a new BaseReducer class that can handle exogenous data. Please have a look and see if this is s sensible start.

As far as I could tell, there was no way to do this by modifying the classes that are already there, which is why I am creating a new BaseReducer.

**Comment by mloning** [comment]
Thanks for starting to work on this. Feel free to make changes to existing code. The simplest starting point would be to simply apply the same transformation to both the endogenous and exogenous variable, ignoring other possible customisations.

**Comment by Lovkush-A** [comment]
@mloning

Here is my current stab at creating DirectReductionClassifier that has exogenous variables. Some questions:

1) Are variable names ok?
2) Tests regarding last_window or predict_last_window fail, and I am not sure how I should fix it. Any tips?
```    def _get_last_window(self):
        """Select last window"""
        # get the start and end points of the last window
        cutoff = self.cutoff
>       start = _shift(cutoff, by=-self.window_length_ + 1)
E       TypeError: bad operand type for unary -: 'NoneType'
```

```
    @pytest.mark.parametrize("Forecaster", WINDOW_FORECASTERS)
    def test_last_window(Forecaster):
        f = _construct_instance(Forecaster)
        # passing the same fh to both fit and predict works
        f.fit(y_train, fh=FH0)
    
>       actual, _ = f._get_last_window()
```

**Comment by mloning** [comment]
Closed in favour of #757

**Pull request closed without merging**
