### PR TITLE
[DOC] Text changes example notebooks

### PR DESCRIPTION
**Pull request by lbventura**
#### What does this implement/fix? Explain your changes.

First contribution to get a feel of the pull request process. Applied minor text changes - upper-case in section headers and at the start of bullet points - to 01_forecasting.ipynb and 01a_forecasting_sklearn.ipynb and added an image displaying the difference between supervised regression and forecasting. No changes in text nor code content.

#### Does your contribution introduce a new dependency? If yes, which one?
No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by fkiraly** [comment]
@lbventura, thanks for helping out with the notebooks!

Three things:

* can you please give a summary, in your PR message, what the main changes are? I can spot capitalization of headers, bullet points, etc.
* Kindly reset the notebook before making a PR, i.e., without cell outputs. This is how it currently is (although it is under discussion whether it should be this way long-term)
* I merged earlier changes to the notebook, so I´d kindly ask you to reconcile these with your changes. If you are using visual studio code, it should be easy - let us know if it gets fiddly and we can look at this jointly.

**Comment by lbventura** [comment]
No problem Franz, it was quite insightful. Thanks for the comments, I'll
update accordingly.

**Comment by lbventura** [comment]
Hi @fkiraly,

I have tackled points 1/2 that you wrote above. However, when I open the `Review NB` app, I do not see the changes that you have merged. Maybe I am comparing with the wrong branch? Thanks!

**Comment by fkiraly** [comment]
> I do not see the changes that you have merged. Maybe I am comparing with the wrong branch? Thanks!

You need to attempt a merge-update of the `text-changes-example-notebook` branch from an up-to-date `main` branch in your local repository - this will result in conflicts which you should be able to resolve in an editor (vs code has convenient functionality).

If unsure what this means, feel free to join the Fri collab session and we can show you.

**Comment by fkiraly** [comment]
need any help with the merge?

**Comment by lbventura** [comment]
Hi Franz,

Currently traveling so I didn't not have time to pick this up. Could we see
it during the week if you have time? If I manage to solve it, I'll let you
know.

**Comment by lbventura** [comment]
@fkiraly , I think I managed to merge your changes following the instructions you describe above. Do you mind taking a look? Thanks!

**Comment by fkiraly** [comment]
Looks ok, but the notebook is failing formatting checks. Could you kindly run `nqba-black` on the notebook?

Afaik that should be automatic if you have `precommit` properly set-up, so you probably haven´t. Let us know if you need help setting it up!

**Comment by lbventura** [comment]
Thanks for the info. Followed the steps above and got this. All the other checks are passed.
nbqa-black

**Comment by lbventura** [comment]
I think it should be all good now @fkiraly 
image

**Review by aiwalter — APPROVED** [review]

**Comment by aiwalter** [comment]
@lbventura I have created a related issue, in case you are interested: https://github.com/alan-turing-institute/sktime/issues/2746
Would be ideally a separate PR.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Looks great!

Re the image, I think there are a few issues to discuss:

* can you confirm that you own the copyright, or is taken from a permissive license source?
* I think it is not exactly the `sktime` model. You are missing the fact that exogeneous variables can also be known in the future (e.g., at `x_t`).
* you should write a figure legend, including surrounding text defining and explaining the mathematical symbols.
* recommended symbols for time series are `y(t)` etc, i.e., with brackets, for consistency.
* I was also going to write a scientific reference (to which symbols should be consistent), but that's on the back-burner.

Could we remove the image from this PR and discuss the illustration and its context, separately, in another PR? I think we'll need a few days back/forth. Just to not block the other changes which could go in already.

**Comment by lbventura** [comment]
@fkiraly 
- I own the copyright as I made it myself.
- True. This makes the representation slightly less intuitive, but we can perhaps put a box with $x_t$ under $y_t$ and have an arrow directed to $y_t$.
- Agreed.
- I was using indices rather than parenthesis to keep the notation simpler and because it seems more consistent with the figure in Section 3.1 of _01_forecasting.ipynb_, but happy to change.

Sure, it is better to have a narrower scope on the PR, I'll update accordingly.

**Pull request merged**
