### PR TITLE
[DOC] Link to extension_templates folder

### LINKED ISSUE #2602: [DOC] "extension template" section of "implementing estimators" guide should directly point to `extension_templates` folder
The developer guide on implementing new estimators
https://www.sktime.net/en/stable/developer_guide/add_estimators.html
explains extension templates and how to use them, but does not directly point to the `extension_templates` folder in the same subsection.

There should be a pointer and perhaps even a link to the folder, possibly repeating the signposting in the previous section ("what is my estimator type").

I would suggest one pointer to the folder in "what are extension templates", and then another one in "how to use extension templates", but of course there may be a better idea how to structure the pointers.

### PR DESCRIPTION
**Pull request by Ris-Bali**
#### Reference Issues/PRs
Fixes #2602 

#### What does this implement/fix? Explain your changes.
Added link to extension_templates in github repo

#### Does your contribution introduce a new dependency? If yes, which one?

No

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by Ris-Bali** [comment]
@fkiraly I think one link on a single page should be okay ; max two links but more than that will be a bit weird imo .

**Comment by fkiraly** [comment]
@Ris-Bali, thanks.

I think the link you added is broken, kindly check.

**Comment by Ris-Bali** [comment]
okay I'll make the correction

**Comment by Ris-Bali** [comment]
@fkiraly is there any way to test these .rst files . Like to see whether they work

**Comment by fkiraly** [comment]
> @fkiraly is there any way to test these .rst files . Like to see whether they work

Yes, look at the readthedocs build based on the PR, by clicking "details" next to the readthedocs check.

**Comment by Ris-Bali** [comment]
@fkiraly  link fixed now . Pls Review

**Review by fkiraly — APPROVED** [review]
works now, thanks!

**Pull request merged**
