### PR TITLE
Numba distance module

### PR DESCRIPTION
**Pull request by chrisholder**
#### Reference Issues/PRs

 #1538 #1547 

#### What does this implement/fix? Explain your changes.

This pr takes all the current distance metrics in sktime and converts them to numba. The distances can be used in the exact same way they were before (params are consistent). Furthermore, a multitude of bugs/errors were found and fixed.

In addition there are 3 new features that come along with this. The first is pairwise distance. This allows you to perform a distance computation across a dataset of timeseries or between two timeseries with massive performance gains.

The second (a much demanded request) both distance and pairwise distance now support 1d and 2d arrays.

The third new feature is the ability to create a numba compiled function for your specific use case via a factory method. This then allows you to embed your created function directly into another numba function  (you can't call non numba compiled functions from inside another numba meaning you have to exit effectivly removing any potential performance gains). This will allow for many other modules to more easily be converted to numba (i.e. classification and clustering) and find massive performance gains.

Finally there were no docstrings or tests for the previous distances and this pr adds a huge amount of testing and validation and well as docstrings to everything.

There is also custom logic to create LowerBounding matrices compatiable with the module.

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

There is a lot stuff here (sorry). Normally i'd split this up but the intention of the pr was to swap the old distances out all at the same time and so we never have to touch cython again. Most of the 'new' stuff is really docstrings and tests that the previous distances were severily lacking (there were no docstrings or tests at all).

When looking at the code there are going to be a couple of things that will appear a 'weird' way of doing something. 90% of the time it's will have something to do with working around a restriction with numba so please ask about anything you see.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by chrisholder** [comment]
I forgot to add there are 3 more distances coming Ill finish them tomorrow.

**Comment by chrisholder** [comment]
As an addition because someone is going to bring up the location of it being in sktime/dist-kernels/numba/distance/... I put it in here just because @fkiraly suggested it would be a good location, but we need to have a discussion about the 'dist-kernels' name and just renaming this whole directory to 'distances' now we're replacing the cython stuff. But ill let you disucss I have no preference.

**Review by TonyBagnall — COMMENTED** [review]
hi chris,

awesome. Couple of points
1. I think this should be in distances. My requests to change dists_kernels name were ignored, but I just dont like it. Refactoring takes an age these days, so better to put it where it belongs now, in distances directory
2. The dtw_based directory is not required. ERP and LCSS are not dtw based, and generally there is too much nesting of directories. Jusat put them directly in distances. Also the name distance is redundant in the private files
distances/_euclidean
distances/_dtw
etc. Similar redundancy in the private function names, 
3. They do not take 1D arrays, which you said they would. This is essential. I could do without all the callable stuff, I just wanted 1D distance functions.

**Comment by TonyBagnall** [comment]
also we are using github IDs not full names **__author__ = ["Chris Holder"]**

**Comment by TonyBagnall** [comment]
update CODEOWNERS

**Comment by TonyBagnall** [comment]
I think these should all be accessed via an init rather than directly?
image

**Comment by TonyBagnall** [comment]
this test failing is something we see all the time when refactoring, I'm not sure if its a bug or not, maybe we should raise an issue? @MatthewMiddlehurst has the same on the distance_based  refactor. 
image

**Comment by TonyBagnall** [comment]
thats a strange error!

**Comment by TonyBagnall** [comment]
image

**Comment by TonyBagnall** [comment]
great, simple use case of full DTW seems to work fine, I will run it through the lot later to compare to cython and tsml. Questions to address prior to approval are
1) setting parameters (how do you do it and is it equivalent)
2) tuning parameters in the way done in knn (is it still fast)

**Comment by TonyBagnall** [comment]
I think we will get this lot in then raise an issues for MSM, KNN and PF.

**Comment by chrisholder** [comment]
The results I know will differ from the previous knn are for:

ddtw - changed the derivative algorithm to match the original papers implementation
wdtw - this I may have implemented wrong but I know it gives a different answer
wddtw - as derivative algorithm changed will give different (and depending on if wdtw is correct
edr - this is new (I accidently implemented this one as I missread erp 😂. erp is also implemented as well)

**Review by fkiraly — APPROVED** [review]
Looks good to me - clean and well-structured imo.
Implements the changes we discussed earlier verbally.

**Comment by fkiraly** [comment]
I'm going to merge this to unlock the CI/CD refactor, I assume it's "done" and there are no objections?

**Comment by TonyBagnall** [comment]
hi @fkiraly there is still work in progress, but it can go in and we can refine in a new PR

**Comment by TonyBagnall** [comment]
lol, ok then, 2 mins to answer!

**Comment by fkiraly** [comment]
whoops, sorry - I thought this was done (according to statements of @chrisholder).
I thought worst case we can unmerge, but if you're fine to have increments in another PR, I would prefer that too since the "big chunk of work" is now in.

**Comment by TonyBagnall** [comment]
Yes it all good, just a bit surprising :)

**Pull request merged**
