### PR TITLE
Add example notebook Window Splitters

### PR DESCRIPTION
**Pull request by juanitorduz**
This partially contributes to [issue 477](https://github.com/alan-turing-institute/sktime/issues/477). I included in a notebook some plots based on @mloning plot's shared in [issue 477](https://github.com/alan-turing-institute/sktime/issues/477) to explain the `SlidingWindosSplitter`. 

There is still some repeated code (e.g. how the plots are generated), but I want to get feedback on whether this notebook is worth having and suggestions on the content.

### CODE REVIEW

**Comment by juanitorduz** [comment]
ok that was embarrassing 🙈 ..I do not have much experience with back formatting in Jupyter notebooks. Anyway, this is just a suggestion for the content of the notebook...we can then fix the code style ...

**Comment by aiwalter** [comment]
@did you install `pre-commit`? Actually black should then format everything for you or at least tell you what to do when doing a commit :)

**Comment by juanitorduz** [comment]
No...lazy me thought I did not need it for this 🙈... but lesson learned 😅 Thanks!

**Review by mloning — APPROVED** [review]
Thanks @juanitorduz - happy to include that! I made some minor changes and added you as a contributor. 

Adding it as a method to the CV classes would be very nice too 😉

**Comment by mloning** [comment]
@juanitorduz let me know if you're happy with it, I'll merge it once you confirm!

**Comment by mloning** [comment]
@juanitorduz seems like you've removed my changes from this [commit](https://github.com/alan-turing-institute/sktime/blob/d769a0b9964f1e85b56bd5a6c19a7dcbb3389369/examples/window_splitters.ipynb)! I think all I added was the fh option for `temporal_train_test_split` and the grid of grey dots in the plots. Let me know if you agree with these changes - I'm happy to add them back once you're happy with everything, working collaboratively on a notebook is always a mess 😄

**Comment by juanitorduz** [comment]
> @juanitorduz seems like you've removed my changes from this [commit](https://github.com/alan-turing-institute/sktime/blob/d769a0b9964f1e85b56bd5a6c19a7dcbb3389369/examples/window_splitters.ipynb)! I think all I added was the fh option for `temporal_train_test_split` and the grid of grey dots in the plots. Let me know if you agree with these changes - I'm happy to add them back once you're happy with everything, working collaboratively on a notebook is always a mess 😄

Ups! Sorry about that! Yes...notebooks can be tricky indeed. Would you mind adding these changes back?I think the plots look much better with the grid of grey dots in the plots. :)

**Comment by juanitorduz** [comment]
Then feel free to merge it.

**Comment by mloning** [comment]
Thanks again @juanitorduz

**Pull request merged**
