### PR TITLE
Refactoring Reducer

### PR DESCRIPTION
**Pull request by thayeylolu**
Reference : https://github.com/alan-turing-institute/sktime/issues/955
We need to slowly re-factor all forecasters to be compliant with the new interface (see PR #912). i.e., no overrides of fit etc and descendant classes only implementing core logic, while the BaseForecaster implements check etc logic.

Currently this is running due to various downwards compatibility workarounds, which should be removed once all forecasters are ready (in "no-override" state)

The forecasters that still need a downstream refactor are:

 
- [ ] _Reducer and related code

### CODE REVIEW

**Comment by fkiraly** [comment]
this should probably be a draft until the tests run?

**Comment by Lovkush-A** [comment]
@thayeylolu Taiwo, may we delete or close this PR? Two reasons are:
* It is easier for me to make changes in a new PR, than to make changes in somebody elses PR
* The discussion with tags means that many of the changes in this PR might not be valid

Let me know what you think! Thanks

**Comment by thayeylolu** [comment]
Yes, please @Lovkush-A

**Comment by fkiraly** [comment]
where is the new PR?

**Comment by thayeylolu** [comment]
I was hoping @Lovkush-A would like to work on it

**Pull request closed without merging**
