### PR TITLE
[DOC] Fixes broken links/estimator overview

### LINKED ISSUE #1438: [DOC] Broken links on 'Estimator Overview' page
#### Describe the issue linked to the documentation

There was a new doc page added in recent update called 'Estimator Overview'.
`https://www.sktime.org/en/latest/estimator_overview.html`
image

While it is very useful, there's an issue with it: all links to pages of estimators are broken.
Problem is that all links contain additional `/modules` path in it, where an actual link to a page doesn't have such part.
See below:
`n = "https://www.sktime.org/en/latest/api_reference/modules/auto_generated/sktime.forecasting.arima.ARIMA.html"`
`m = "https://www.sktime.org/en/latest/api_reference/auto_generated/sktime.forecasting.arima.ARIMA.html"`
where `n` - link from 'estimator overview' page, `m` - actual link.

#### Suggest a potential alternative/fix

Potential fix would be to remove `/modules` from the path.
But I see that this page is auto-updating so I don't know if there's an actual way to fix this or how it's done at all.

UPD: I tried to look through codebase and doc auto-generator files but found nothing. I guess without any experience w/ Sphinx it's impossible to find the root of the issue.

### PR DESCRIPTION
**Pull request by afzal442**
#### Reference Issues/PRs

Fixes #1438

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by mloning** [comment]
Thanks @afzal442 

Something still isn't quite right. When looking at the [generated online docs](https://sktime--1445.org.readthedocs.build/en/1445/index.html), some estimators now work (e.g. `ARIMA`), but others still don't (e.g. `Differencer`). I'm not sure yet why.

**Comment by mloning** [comment]
@afzal442 I think I found what was wrong and fixed it. I pushed directly onto this branch, hope that's okay!

**Review by mloning — APPROVED** [review]
I think it's all fixed now. 

On the website generated from the PR, the link for the `Differencer` is still broken, but that's because it points to the live website (rather than the one generated based on the PR) which doesn't have the page yet. There may be some ReadTheDocs environment variables that could fix that, but I think it's good to be merged for now.

**Review by fkiraly — APPROVED** [review]
yes, thanks!

**Pull request merged**
