### PR TITLE
estimator tests to allow objects, not just classes

### PR DESCRIPTION
**Pull request by fkiraly**
This PR addresses #1027 and part of #1032.
The post-PR state allows testing of concrete objects, not just classes, using the current test suite.

This is achieved by modifying the `estimator_checks._construct_instance` utility:

* pre-PR, this always assumes the argument `Estimator` is a class, and creates an object after lookup of default parameters from the default parameter registry, using those parameters. This object is then returned.
* post-PR, it first checks whether the argument is a class or an object. If an object, it just returns the argument; if a class, it proceeds as pre-PR.

Since `_construct_instance` is called at the start of every estimator related test, this change enables all those tests to take objects as well as classes.

For the user, this allows convenient command line testing of newly written estimators without first having to deposit default parameters in the default parameter registry, or changing the registry file to test with different parameter settings.

### CODE REVIEW

**Comment by mloning** [comment]
Would you want to run your estimator object through `check_estimator` function? I think that would still break as at least one of the other functions assumes the input to be a class (see `check_inheritance`), not sure if there are more.

**Comment by fkiraly** [comment]
>Would you want to run your estimator object through check_estimator function?

Good idea - I think I have now tracked down all functions that were class (not object) related that needed to turn objects back into classes.

**Comment by fkiraly** [comment]
this is ready for review again

**Review by mloning — COMMENTED** [review]
In general, I do not think that adding these conversions in every test isn't the right way of changing the tests. I'd prefer separating tests that run on classes and tests that run on objects. 

But wouldn't veto the PR if you think this needs to go in now.

**Comment by mloning** [comment]
There was a typo: I do not think that adding the object/class conversions at the beginning is the right way of handling this, but don't have a strong preference.

**Comment by mloning** [comment]
The better way may be to replace the name of the required hyper-parameters in the `_required_parameters` class attribute with the actual hyper-parameters used in testing (as you suggested somewhere else).

**Comment by mloning** [comment]
Can this be closed?

**Comment by mloning** [comment]
Closed due to inactivity.

**Pull request closed without merging**
