### PR TITLE
Refactor the `_diff_transform` function to be compatible with pandas 1.3.4

### LINKED ISSUE #1642: [BUG] NaNs returned by transformations.series.difference.Differencer
**Describe the bug**
this was spotted by Lukasz Mentel (@lmmentel) thanks for this. The anomaly arises when running transformations testing locally. Strangely, this is not picked up with the repo tests. Differencer in transformations.series.difference return the same size data frame as input, which means for first order difference it returns nans in the first row
 
**To Reproduce**

```python
from sktime.transformations.series.difference import Differencer
df = pd.DataFrame({'a': [1, 2, 3, 4, 5, 6],
                   'b': [1, 1, 2, 3, 5, 8],
                   'c': [1, 4, 9, 16, 25, 36]})
diff = Differencer()
print(df.diff())
```
outputs 
image
 Is it meant to have nans? If so, the tests need changing. If you run the test function in transformations/tests/test_all_transformers locally you get this output

image

**Expected behavior**

**Additional context**

image

**Versions**
<details>

</details>

### PR DESCRIPTION
**Pull request by lmmentel**
#### Reference Issues/PRs

Fixes #1642 

#### What does this implement/fix? Explain your changes.

Added a conversion from `numpy.int64` to python `int` in a call to `pandas.diff` since otherwise the type check fails.

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### What should a reviewer concentrate their feedback on?

Run the test locally to make sure they pass.

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

### CODE REVIEW

**Comment by fkiraly** [comment]
Would you mind taking care of the linting? A new line is missing again :-)

I would really recommend getting the linting set up locally.

**Comment by lmmentel** [comment]
> Would you mind taking care of the linting? A new line is missing again :-)

No problem!

**Comment by lmmentel** [comment]
Should be fixed now

**Comment by fkiraly** [comment]
appveyor is failing, and the macos tests are blocked due to overload.
But manylinux passes, which indicates that this is all fine.

**Review by fkiraly — APPROVED** [review]
looks good now.

**Pull request merged**
