### PR TITLE
Add toggle button to make examples easy to copy

### PR DESCRIPTION
**Pull request by RNKuhns**
#### Reference Issues/PRs

#1565 

#### What does this implement/fix? Explain your changes.

It adds  a layout.html template to extend the pydata-sphinx-theme when building our docs. We need to run a javascript script after the content of pages is loaded. This script will identify example code blocks (e.g. blocks with python highlighting) and add a toggle button so we can turn on/off the text that makes the examples difficult to copy (e.g. >>>, ...,  example output, etc). 

It also adds css styling for the new button. Changes to the conf.py should just be to add the css styling file.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

### CODE REVIEW

**Comment by RNKuhns** [comment]
@aiwalter and @mloning we should go through and make sure it seems like this is working on every page after the docs build (it appears to work locally). 

Note that there is likely a way to have the javascript script in a separate file (in _static/js/) but I've had trouble getting that to load into the layout.html template update and work correctly, so I went with what is working.

**Review by TonyBagnall — APPROVED** [review]
A nice improvement +1 from me

**Review by aiwalter — APPROVED** [review]
Great thx

**Review by mloning — APPROVED** [review]
Nice work @RNKuhns

**Pull request merged**
