### PR TITLE
Added ForecastingPipeline

### PR DESCRIPTION
**Pull request by aiwalter**
#### Reference Issues/PRs
https://github.com/sktime/enhancement-proposals/pull/10

#### What does this implement/fix? Explain your changes.
Draft for multivariate pipelining.
Example:
```python
pipe = ForecastingPipeline(steps=[
    ("imputer", Imputer(), ["y"]),
    ("scaler", TabularToSeriesAdaptor(MinMaxScaler()), ["y", "X"]),
    ("forecaster", NaiveForecaster())
    ]
)
pipe.fit(y_train, X_train)
```
To do:
- [ ] Enable grid search: solve issues with `get_params` and `set_params`
- [ ] Add validation for the `identifier` like `["y", "X"]` has to be checked if `X` is given at all and if `identifier` contains valid strings.

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

___
Martin Walter <martin_friedrich.walter@daimler.com>, Mercedes-Benz AG on behalf of Daimler TSS GmbH.
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

### CODE REVIEW

**Comment by RNKuhns** [comment]
@aiwalter I was excited when you proposed about the ForecastingPipeline that type of functionality is super-useful.  I just opened up #874 since I keep running into cases where it would be easier (and more elegant) if I had a `TransformerPipeline` hanging about for exploratory data analysis and the like. 

Your approach already has the the transformer part built into it, but also has the additional functionality to fit/predit based on a forecaster, which got me thinking what if that was separated into a `TransformerPipeline` and a `ForecastingPipepline` that takes a forecasting model and a `TransformerPipeline`?

In your framework that would be something users would call like:

```python
processing_pipe = TransformerPipeline(
    [
        ('boxcox', BoxCoxTransformer(...), ["y"]), 
        ('detrend', DeTrender(...), ["y"]), 
        ("scaler", TabularToSeriesAdaptor(MinMaxScaler()), ["y", "X"]),
    ]
)
yt, xt = processing_pipe.fit_transform(y, x)

# Do some exploratory data analysis like checking stationarity, acf/pacf plots 
# and examining cross-correlation functions
...

# Then re-use the TransformerPipeline to fit the model
forecasting_pipe = ForecastingPipeline(forecaster, transformer_steps=processing_pipe)
```
If you think it would be a reasonable approach, I can help refactor in any way you think would be useful.

**Comment by fkiraly** [comment]
@rnkuhns, @aiwalter, I would hope that at the end we can have a scitype polymorphic pipeline, just like `sklearn`'s - if the last bit is a transformer, it behaves like a transformer; if it's a forecaster, it behaves like a forecaster.

**Comment by mloning** [comment]
I agree, polymorphic would be nice. 

The `TransformedTargetForecaster` works like this already too: 
```python
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.datasets import load_airline
from sktime.transformations.series.detrend import Detrender
from sktime.transformations.series.boxcox import BoxCoxTransformer

y = load_airline()
pipeline = TransformedTargetForecaster(
    [
        ('boxcox', BoxCoxTransformer()), 
        ('detrend', Detrender()), 
        ('naive', NaiveForecaster())
    ]
)
yt = pipeline.fit_transform(y)
```
It complains if the last step is not a forecaster, but the transformation seems to work as expected, would be nice to work without the forecaster though.

**Comment by RNKuhns** [comment]
The polymorphic solution also sounds good to me -- nice to have one way to solve the problem. That's interesting @mloning and potentially useful until this gets fully implemented.

Once the main functionality is up and running, would also be interested to have a method to add additional steps to the pipeline (similar to appending to the end of a list). 

The example below shows adding a forecaster to the pipeline. But I could see this being useful during EDA where you want to apply a portion of the pipeline and do some analysis (maybe see if things are stationary and such) and then add additional processing steps to the pipeline based on the interim results. Then finally add the forecaster step at the end. 

```python
pipeline= ForecastingPipeline(
    [
        ('boxcox', BoxCoxTransformer(...), ["y"]), 
        ('detrend', DeTrender(...), ["y"]), 
        ("scaler", TabularToSeriesAdaptor(MinMaxScaler()), ["y", "X"]),
    ]
)
yt, xt = pipeline.fit_transform(y, x)

... # Do some EDA

pipeline.add_steps(
    steps=[('forecaster', NaiveForecaster())]
)
```

**Comment by aiwalter** [comment]
I will close this PR and open a new one in June.
@RNKuhns @mloning yes we could probably rather fix the issue that `TransformedTargetForecaster` and the new `ForecastingPipeline` should also work as a transformer pipeline in case there is no forecaster given. Would you like to open a PR for `TransformedTargetForecaster` @RNKuhns to fix this?

**Pull request closed without merging**
